
const assert = require('assert');
const crypto = require('crypto');
const { spawn } = require('child_process');
const path = require('path');
const fs = require('fs');
const os = require('os');
const port = 3961;
const base = `http://127.0.0.1:${port}`;
const tempStorage = fs.mkdtempSync(path.join(os.tmpdir(), 'smarter-justice-smoke-'));
const server = spawn(process.execPath, ['server.js'], { cwd: path.join(__dirname, '..'), env: { ...process.env, PORT: String(port), ADMIN_TOKEN: 'test-token', APP_BASE_URL: base, SMARTER_JUSTICE_STORAGE_DIR: tempStorage, STRIPE_WEBHOOK_SECRET: 'whsec_test_secret' } });
let log = '';
server.stdout.on('data', d => log += d.toString());
server.stderr.on('data', d => log += d.toString());
function wait(ms){ return new Promise(r => setTimeout(r, ms)); }
async function fetchJson(url, opts){ const r = await fetch(url, opts); const j = await r.json(); if (!r.ok) throw new Error(JSON.stringify(j)); return j; }
(async () => {
  try {
    for (let i=0;i<30;i++){ if(log.includes('listening')) break; await wait(100); }
    const health = await fetchJson(`${base}/health`);
    assert.equal(health.ok, true);
    assert.equal(health.version, '1.0.6');
    assert.equal(health.features.formReadinessLevels, true);
    assert.equal(health.features.firstFormDraftStarterPackage, true);
    assert.equal(health.features.secureContinuationTokens, true);
    assert.equal(health.features.optionalPostgresPersistence, true);
    assert.equal(health.features.guidedHomepageStepFlow, true);
    assert.equal(health.features.focusedPracticeLandingPages, 15);
    assert.equal(health.features.conversionReadyPricingPage, true);
    assert.equal(health.features.uploadNoticePrimaryCta, true);
    assert.equal(health.features.practiceSpecificSmartQuestions, true);
    assert.equal(health.features.noticeUploadEntryPage, true);
    assert.equal(health.features.stripeCheckoutFoundation, true);
    assert.equal(health.features.stripeWebhookFoundation, true);
    assert.equal(health.features.requestMoreInformationWorkflow, true);
    assert.equal(health.features.launchReadinessChecklist, true);
    assert.equal(health.features.reviewPackageDownload, true);
    assert.equal(health.features.verifiedFormPathRegistry, true);
    assert.equal(health.features.adminAuditLogFoundation, true);
    assert.equal(health.features.humanReviewSeparateFromAttorneyReview, true);
    assert.equal(health.features.taxAttorneyReviewOption, true);
    assert.equal(health.features.offerInCompromiseIncluded, true);
    assert.equal(health.features.adminTokenRequiredNoDefault, true);
    assert(health.features.practiceAreas >= 40);
    const home = await fetch(`${base}/`).then(r=>r.text());
    assert(/Start free/.test(home));
    assert(/maxlength="2500"/.test(home));
    const practices = await fetchJson(`${base}/api/practice-areas`);
    assert(practices.practiceAreas.some(p => p.slug === 'medical-malpractice'));
    const schema = await fetchJson(`${base}/api/intake-schema/taxes`);
    assert(schema.ok && /Tax preparation/.test(schema.schema.title));
    const submitted = await fetchJson(`${base}/api/free-question`, { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ practiceArea:'taxes', subcategory:'Offer in compromise', state:'New York', county:'Queens', city:'New York City', documentType:'Tax notice', deadlineDate:'2026-07-15', dateReceived:'2026-06-18', amountInvolved:'12000', question:'I received an IRS notice and need help with an offer in compromise, lien, and deadline next month.', fullName:'Test User', email:'test@example.com', consentToContact:true, attachments:[{name:'irs-notice.pdf', mimeType:'application/pdf', dataBase64: Buffer.from('test pdf placeholder').toString('base64')}]} ) });
    assert(submitted.ok);
    assert(/tax/i.test(submitted.case.practiceName));
    assert(/tax attorney|CPA|accountant|enrolled/i.test(submitted.case.professionalReviewLane));
    assert(submitted.case.attachments.length === 1);
    assert(submitted.case.analysis.formReadiness);
    assert((submitted.case.verifiedFormPaths || []).some(p => p.id === 'tax-resolution-oic-starter'));
    assert((submitted.case.missingInformation || []).length >= 1);
    assert(submitted.case.formPathEvaluation && submitted.case.formPathEvaluation.completionPercent >= 0);
    assert.equal(submitted.case.documentType, 'Tax notice');
    const loaded = await fetchJson(`${base}/api/cases/${encodeURIComponent(submitted.case.id)}`);
    assert.equal(loaded.case.id, submitted.case.id);
    const pkg = await fetch(`${base}/api/cases/${encodeURIComponent(submitted.case.id)}/review-package`).then(r=>r.text());
    assert(/organized review package/i.test(pkg));
    const draftPkg = await fetch(`${base}/api/cases/${encodeURIComponent(submitted.case.id)}/draft-package`).then(r=>r.text());
    assert(/form-draft starter package/i.test(draftPkg));
    const checkout = await fetchJson(`${base}/api/checkout`, { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ caseId: submitted.case.id, serviceType:'tax_review' }) });
    assert(checkout.ok && checkout.stripeConfigured === false);
    const launch = await fetchJson(`${base}/api/launch-readiness?token=test-token`);
    assert(launch.ok && launch.checklist.items.some(i => i.key === 'stripeWebhook'));
    const event = { id:'evt_test', type:'checkout.session.completed', data:{ object:{ id:'cs_test_123', client_reference_id: submitted.case.id, payment_status:'paid', status:'complete', amount_total:19900, currency:'usd', metadata:{ caseId: submitted.case.id } } } };
    const raw = JSON.stringify(event);
    const ts = Math.floor(Date.now()/1000);
    const sig = crypto.createHmac('sha256','whsec_test_secret').update(`${ts}.${raw}`).digest('hex');
    const webhook = await fetchJson(`${base}/webhooks/stripe`, { method:'POST', headers:{'Content-Type':'application/json','Stripe-Signature':`t=${ts},v1=${sig}`}, body: raw });
    assert(webhook.received && webhook.handled && webhook.foundCase);
    const afterWebhook = await fetchJson(`${base}/api/cases/${encodeURIComponent(submitted.case.id)}`);
    assert(/webhook/.test(afterWebhook.case.paymentStatus));
    const linkEmail = await fetchJson(`${base}/api/cases/${encodeURIComponent(submitted.case.id)}/email-link`, { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ email:'test@example.com' }) });
    assert(linkEmail.ok);
    const partner = await fetchJson(`${base}/api/community-partners/register`, { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ name:'Test Community Center', email:'partner@example.com' }) });
    assert(partner.ok && partner.partner.code);
    const update = await fetchJson(`${base}/api/admin/cases/${encodeURIComponent(submitted.case.id)}?token=test-token`, { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ status:'More information needed', userActionNeeded:'Need one more document', userFacingNote:'Please upload the full IRS notice.', formDraftStatus:'starter facts incomplete' }) });
    assert(update.ok && /IRS notice/.test(update.case.userFacingNote));
    const admin = await fetchJson(`${base}/api/admin/cases?token=test-token`);
    assert(admin.cases.length >= 1);
    assert(Array.isArray(admin.auditLog) && admin.auditLog.length >= 1);
    console.log('smoke.test.js passed');
  } finally { server.kill(); try { fs.rmSync(tempStorage, { recursive:true, force:true }); } catch {} }
})().catch(err => { console.error(err); server.kill(); process.exit(1); });
