'use strict';
const assert=require('assert');
const launch=require('../lib/allApprovedPortalLaunch');
const validation=launch.validatePolicy();
assert.equal(validation.ok,true,validation.errors.join(','));
assert.ok(validation.approvedPortalCount>=20);
for(const id of ['real-estate-law-aid','landlord-tenant-aid','civil-rights-law-aid','domestic-violence-aid'])assert.ok(launch.APPROVED_IDS.includes(id),id);
for(const id of ['immigration-oasis','coverednyc','justice-truck','stop-sign-project','attorneyride'])assert.ok(!launch.APPROVED_IDS.includes(id),id);
const ready={product_id:'estate-law-aid',version:'1.1.93',artifact_name:'estate-law-aid-v1.1.93.zip',artifact_sha256:'a'.repeat(64),readiness_state:'DEPLOYMENT_REVIEW_READY',exact_blockers:[],deployment_authorized:false,production_request_sent:false};
const blocked={product_id:'contract-creator',version:'0.53.0',artifact_name:'contractcreator-v0.53.0.zip',artifact_sha256:'b'.repeat(64),readiness_state:'BLOCKED_WITH_EXACT_REASON',exact_blockers:['Canonical owned replacement domain remains pending.'],deployment_authorized:false,production_request_sent:false};
const aggregate=launch.aggregate([ready,blocked]);
assert.equal(aggregate.crossBlockingApplied,false);
assert.equal(aggregate.initialCohortPriorityApplied,false);
assert.equal(aggregate.parallelPreparationAllowed,true);
assert.equal(aggregate.productionReleaseOneProductAtATime,true);
assert.equal(aggregate.deploymentAuthorized,false);
assert.ok(aggregate.independentlyEligibleProductIds.includes('estate-law-aid'));
assert.ok(!aggregate.independentlyEligibleProductIds.includes('contract-creator'));
assert.equal(launch.aggregate([]).summary.evidenceRequired,validation.approvedPortalCount);
console.log('all-approved-portals-launch-v1785.test.js passed');
