const assert=require('assert');
const fs=require('fs');
const path=require('path');
const os=require('os');
process.env.SMARTER_JUSTICE_STORAGE_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'sj-build-program-'));
const program=require('../lib/buildProgram');
const data=program.getData();
assert.equal(data.programVersion,'1.0.0');
assert.equal(data.items.length,240,'all master-list items should be visible through the v1.7.20 additions');
assert(data.items.some(x=>x.id==='SJ-MASTER-001'));
assert(data.items.some(x=>x.status==='exact artifact tested'));
assert(data.items.some(x=>x.id==='SJ-MASTER-164'),'v1.7.3 wrapped-format items should be imported');
assert(data.items.some(x=>x.id==='SJ-MASTER-182'),'all v1.7.4 additions should be imported');
assert(data.items.some(x=>x.id==='SJ-MASTER-194'),'all v1.7.5 additions should be imported');
assert(data.items.some(x=>x.id==='SJ-MASTER-240'),'all v1.7.20 additions should be imported');
assert(data.releases.some(x=>x.id==='SJ-REL-1.7.6' && x.status==='exact artifact tested'),'v1.7.6 rollback release record should remain visible');
assert(data.releases.some(x=>x.id==='SJ-REL-1.7.7'),'v1.7.7 corrective release record should be visible');
assert(data.releases.some(x=>x.id==='SJ-REL-1.7.8'),'v1.7.8 customer-experience release record should be visible');
assert(data.releases.some(x=>x.id==='SJ-REL-1.7.9' && x.status==='exact artifact tested'),'v1.7.9 governance release record should be visible');
assert(data.items.some(x=>x.id==='SJ-MASTER-181' && /Public Paid Human Review Standard/.test(x.title)),'public paid Human Review standard item should be imported');
let saved=program.upsertItem({id:'JTS-FORM-001',portalSlug:'justice-tax-solutions',type:'portal specific',title:'Track official form edition',priority:'high',status:'planned',targetRelease:'v0.1.94',category:'forms',acceptanceCriteria:['Edition date recorded'],requiredTests:['Form mapping test']});
assert(!saved.error);
let after=program.getData();
assert(after.items.some(x=>x.id==='JTS-FORM-001'));
program.upsertItem({id:'SJ-MASTER-006',title:'Confirm Render plan',status:'blocked',blockers:['Owner must verify billing privately']});
after=program.getData();
assert.equal(after.items.find(x=>x.id==='SJ-MASTER-006').status,'blocked');
assert(after.summary.blocked>=1);
program.addRecord('evidence',{title:'Exact artifact test',status:'passed',itemIds:['SJ-MASTER-005']});
program.addRecord('decision',{title:'Use staged releases',status:'approved'});
program.addRecord('risk',{title:'Temporary database expires',status:'open'});
after=program.getData();
assert.equal(after.evidence.length,1); assert.equal(after.decisions.length,1); assert.equal(after.risks.length,1);
assert(program.exportMarkdown().includes('SJ-MASTER-001'));
console.log('Build Program Control Center tests passed.');
