'use strict';
const assert=require('assert');const fs=require('fs');const path=require('path');const os=require('os');const http=require('http');
const root=path.join(__dirname,'..');process.env.NODE_ENV='test';process.env.SMARTER_JUSTICE_STORAGE_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'sj-pack-oca-v1767-'));process.env.OWNER_CONTROL_CENTER_TOKEN='owner-pack-oca-v1767-token-123456789';
const pack=require('../lib/coordinatedPromptPack');const registry=require('../lib/professionalIdentityEvidenceRegistry');const truth=require('../lib/currentReleaseTruth');const reusable=require('../lib/reusableBuildGovernance');const store=require('../lib/store');const server=require('../server');
function request(base,pathname,headers={}){return new Promise((resolve,reject)=>{const req=http.request(new URL(pathname,base),{headers},res=>{const chunks=[];res.on('data',c=>chunks.push(c));res.on('end',()=>{let data=null;try{data=JSON.parse(Buffer.concat(chunks).toString('utf8'));}catch{}resolve({status:res.statusCode,data});});});req.on('error',reject);req.end();});}
(async()=>{
 const pkg=require('../package.json');const manifest=require('../portal-manifest.json');assert.equal(pkg.version,'1.7.83');assert.equal(pkg.scripts.test.split(' && ').length,145);assert.equal(manifest.currentDevelopmentVersion,'1.7.83');assert.equal(manifest.latestZipName,'smarter-justice-v1.7.82.zip');assert.equal(manifest.dependencyIndependentTestParts,145);assert.equal(manifest.testSuiteParts,146);
 const pv=pack.validate();assert.equal(pv.ok,true,pv.errors.join('\n'));assert.equal(pv.packId,'SJP-2026-08-02-C15-P37-D11-V13');assert.equal(pv.ruleCount,86);assert.equal(pv.canonicalCommitProven,false);
 const rv=registry.validate();assert.equal(rv.ok,true,rv.errors.join('\n'));assert.equal(rv.credentialNamespace,'NY-OCA-{seven-digit registration number}');assert.equal(registry.jurisdictionCredential('1234567'),'NY-OCA-1234567');assert.throws(()=>registry.jurisdictionCredential('123'));
 const obs=registry.normalizeObservation({registration_number:'7654321',first_name:'Test',last_name:'Lawyer',company_name:'Example Firm',street_1:'10 Home Road',city:'New York',state:'NY',registration_status:'Currently registered'},{sourceSnapshotId:'TEST-SNAPSHOT',observedAt:'2026-08-01T12:00:00-04:00'});const pub=registry.publicBusinessContact(obs);assert.equal(pub.street1,null);assert.equal(pub.streetSuppressed,true);assert.equal(obs.registrationObservation.goodStanding,null);assert.equal(obs.registrationObservation.absenceOfDisciplineClaim,null);
 const held=registry.publicationEligibility({observation:obs,directoryRecheck:{state:'STALE'},specialtyAcceptance:{state:'PENDING'}});assert.equal(held.eligible,false);assert(held.reasons.includes('TARGETED_OCA_DIRECTORY_RECHECK_REQUIRED'));const eligible=registry.publicationEligibility({observation:obs,directoryRecheck:{state:'CURRENT_EXACT_RECHECK'},specialtyAcceptance:{state:'ACCEPTED'}});assert.equal(eligible.eligible,true);assert.equal(eligible.goodStandingInferred,false);
 const packet=registry.createPortalCandidatePacket({portalId:'estate-law-aid',sourceSnapshotId:'TEST-SNAPSHOT',candidates:[obs]});assert.equal(packet.publicationImplied,false);assert.equal(packet.automaticPortalWriteBack,false);assert.equal(registry.reconcilePortalReceipt(packet,{packetId:packet.packetId,state:'ACCEPTED'}).centralIdentityMutated,false);
 const ledger=require('../DURABLE_OWNER_RULES_LEDGER_V1.7.75.json');const baseline=require('../DURABLE_RULE_BASELINE_MANIFEST_V1.7.75.json');assert.equal(ledger.ruleCount,86);assert.equal(baseline.orderedActiveRuleIds.length,86);assert.equal(baseline.baselineId,'DRB-2026-08-02-DUR001-DUR086-V13');
 const tv=truth.validate();assert.equal(tv.ok,true,tv.errors.join('\n'));assert.equal(tv.sourceVersion,'1.7.82');const gv=reusable.validate();assert.equal(gv.ok,true,gv.errors.join('\n'));
 const cont=fs.readFileSync(path.join(root,'CONTINUATION_PROMPT_V1.7.75.md'),'utf8');assert(cont.includes('EXPECTED NEXT VERSION IF BASE REMAINS CURRENT: v1.7.76'));assert(cont.includes('SJP-2026-08-02-C15-P37-D11-V13'));assert(cont.includes('smarter-justice-v1.7.73.zip'));assert(cont.trimEnd().endsWith('END OF SMARTER JUSTICE CENTRAL MASTER FIFTEENTH-PASS SUNDAY LAUNCH-DAY ORCHESTRATION FINAL CONTINUATION'));
 await store.init();await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;try{assert.equal((await request(base,'/api/owner/coordinated-prompt-pack')).status,403);assert.equal((await request(base,'/api/owner/professional-identity-evidence-registry')).status,403);const h={'x-owner-control-token':process.env.OWNER_CONTROL_CENTER_TOKEN};const p1=await request(base,'/api/owner/coordinated-prompt-pack',h);assert.equal(p1.status,200);assert.equal(p1.data.coordinatedPromptPack.validation.ok,true);const p2=await request(base,'/api/owner/professional-identity-evidence-registry',h);assert.equal(p2.status,200);assert.equal(p2.data.professionalIdentityEvidenceRegistry.validation.ok,true);const cc=await request(base,'/api/owner/control-center',h);assert.equal(cc.status,200);assert.equal(cc.data.version,'1.7.83');assert.equal(cc.data.coordinatedPromptPack.validation.ok,true);assert.equal(cc.data.professionalIdentityEvidenceRegistry.validation.ok,true);}finally{await new Promise(r=>server.close(r));}
 console.log('coordinated-pack-oca-registry-v1767.test.js passed');
})().catch(err=>{console.error(err);try{server.close(()=>{});}catch{}process.exit(1);});
