'use strict';
const assert=require('assert');const fs=require('fs');const path=require('path');
const root=path.join(__dirname,'..');
const {buildCapabilityRegistry}=require('../data/crossPortalCapabilities');
const registry=buildCapabilityRegistry([]);const l=registry.learningSystem;
assert.equal(registry.version,'2.0.0');assert.equal(l.version,'1.0.0');assert.equal(l.generatedForRelease,'1.7.28');
assert.equal(l.sourceArtifacts.length,6);assert.equal(l.learningRecords.length,12);assert.equal(l.adoptionDecisions.length,20);
const valid=new Set(['adopted','adopt-now','adapt-specialty','verify-first','defer','reject','not-applicable']);
assert(l.adoptionDecisions.every(x=>valid.has(x.status)&&x.portalId&&x.capabilityId&&x.reason));
const sj=l.sourceArtifacts.find(x=>x.portalId==='general-smarter-justice-start');assert.equal(sj.sha256,'3a627d1c5775b79e309605c1d74582d995314e8229805e9b6a954283eb985b46');assert.equal(sj.sizeBytes,2894831);
const bld=l.sourceArtifacts.find(x=>x.portalId==='business-launch-desk');assert.equal(bld.version,'0.2.39');
const tax=l.sourceArtifacts.find(x=>x.portalId==='justice-tax-solutions');assert.equal(tax.version,'0.1.107');
const io=l.sourceArtifacts.filter(x=>x.portalId==='immigration-oasis');assert.equal(io.length,2);assert(io.some(x=>x.version==='1.10.254'&&x.deploymentStatus.includes('must never be clean-deployed')));assert(io.some(x=>x.version==='1.10.162'));
assert(l.adoptionDecisions.some(x=>x.portalId==='immigration-oasis'&&x.capabilityId==='full-lean-official-asset-overlay'&&x.status==='adopted'));
assert(l.adoptionDecisions.some(x=>x.portalId==='justice-tax-solutions'&&x.capabilityId==='full-lean-official-asset-overlay'&&x.status==='verify-first'));
for(const f of ['CROSS_PORTAL_CAPABILITY_REGISTRY_V1.7.28.json','PORTAL_CAPABILITY_ADOPTION_STATUS_V1.7.28.json','CROSS_PORTAL_LEARNING_AND_ADAPTATION_STANDARD_V1.7.28.md','CROSS_PORTAL_LEARNING_V1.7.28.md'])assert(fs.existsSync(path.join(root,f)),f);
const serialized=JSON.stringify(l).toLowerCase();for(const forbidden of ['social security number','bank account number','medical record content','privileged communication content'])assert(!serialized.includes(forbidden));
const control=require('../lib/controlCenter').getControlCenterData();assert.equal(control.crossPortalLearning.version,'1.0.0');assert.equal(control.summary.learningRecordsTracked,12);assert.equal(control.summary.adoptionDecisionsTracked,20);
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');assert(server.includes("'/api/owner/cross-portal-learning'"));assert(server.includes("'/api/owner/cross-portal-learning/export'"));
const html=fs.readFileSync(path.join(root,'public/control-center.html'),'utf8');const app=fs.readFileSync(path.join(root,'public/app.js'),'utf8');assert(html.includes('cross-portal registry'));assert(app.includes('renderCapabilityRegistry'));assert(app.includes('learning'));
console.log('cross-portal-learning-v1728.test.js passed');
