'use strict';
const assert=require('assert');const fs=require('fs');const path=require('path');const os=require('os');const http=require('http');const root=path.join(__dirname,'..');
process.env.NODE_ENV='test';process.env.SMARTER_JUSTICE_STORAGE_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'sj-fifth-pass-v1762-'));process.env.OWNER_CONTROL_CENTER_TOKEN='owner-fifth-pass-v1762-token-123456789';
const fifth=require('../lib/fifthPassGovernance');const authority=require('../lib/initialPortalAuthority');const reusable=require('../lib/reusableBuildGovernance');const store=require('../lib/store');const server=require('../server');
function request(base,pathname,headers={}){return new Promise((resolve,reject)=>{const req=http.request(new URL(pathname,base),{headers},res=>{const chunks=[];res.on('data',c=>chunks.push(c));res.on('end',()=>{let data=null;try{data=JSON.parse(Buffer.concat(chunks).toString('utf8'));}catch{}resolve({status:res.statusCode,data});});});req.on('error',reject);req.end();});}
(async()=>{const pkg=require('../package.json'),manifest=require('../portal-manifest.json'),intake=require('../REUSABLE_MASTER_COMMAND_INTAKE_V1.7.75.json');assert.equal(pkg.version,'1.7.83');assert.equal(pkg.scripts.test.split(' && ').length,145);assert.equal(manifest.dependencyIndependentTestParts,145);assert.equal(manifest.testSuiteParts,146);assert.equal(manifest.releaseEvidence,'RELEASE_EVIDENCE_V1.7.83.json');assert.equal(manifest.durableOwnerRulesLedger,'DURABLE_OWNER_RULES_LEDGER_V1.7.75.json');
assert.equal(intake.prompt.sha256,'5dad361bae18b25dc8193ce32ca4263a72b12ce90316d6b97dbd191ce2b74223');assert.equal(intake.prompt.sizeBytes,383921);assert.equal(intake.prompt.lineCount,8204);assert.equal(intake.implementationTruthSource,'smarter-justice-v1.7.73.zip');assert.equal(intake.nextVersionDerived,'1.7.75');
const f=fifth.validate();assert.equal(f.ok,true,f.errors.join('\n'));assert.equal(f.durableRuleCount,41);assert.equal(f.languageToggleCount,0);assert(f.researchSourceCount>=8);assert(f.generatorCount>=7);assert.equal(reusable.validate().ok,true,reusable.validate().errors.join('\n'));
const a=authority.validate();assert.equal(a.ok,true,a.errors.join('\n'));assert.equal(a.advancedCount,0);assert.equal(a.unchangedCount,4);assert.equal(a.completeIdentityCount,3);assert.equal(a.versionOnlyCount,1);const expected={'divorce-law-aid':'0.44.0','estate-law-aid':'1.1.67','personal-injury-law-aid':'0.66.0','domestic-violence-aid':'0.49.0'};for(const [id,v] of Object.entries(expected))assert.equal(authority.artifactFor(id).version,v);
for(const file of fs.readdirSync(path.join(root,'public')).filter(x=>x.endsWith('.html'))){const html=fs.readFileSync(path.join(root,'public',file),'utf8');assert(!html.includes('data-lang-toggle'),file);}
const app=fs.readFileSync(path.join(root,'public/app.js'),'utf8');assert(!app.includes('initNav(); initLanguage(); initCounters();'));const cont=fs.readFileSync(path.join(root,'CONTINUATION_PROMPT_V1.7.75.md'),'utf8');assert(cont.includes('EXPECTED NEXT VERSION IF BASE REMAINS CURRENT: v1.7.76'));assert(cont.includes('DUR-086'));assert(cont.includes('END OF SMARTER JUSTICE CENTRAL MASTER FIFTEENTH-PASS SUNDAY LAUNCH-DAY ORCHESTRATION FINAL CONTINUATION'));
await store.init();const addr=await new Promise(r=>server.listen(0,'127.0.0.1',()=>r(server.address())));const base=`http://127.0.0.1:${addr.port}`;try{assert.equal((await request(base,'/api/owner/fifth-pass-governance')).status,403);const h={'x-owner-control-token':process.env.OWNER_CONTROL_CENTER_TOKEN};const allowed=await request(base,'/api/owner/fifth-pass-governance',h);assert.equal(allowed.status,200);assert.equal(allowed.data.appVersion,'1.7.83');assert.equal(allowed.data.fifthPassGovernance.validation.ok,true);assert.equal((await request(base,'/api/owner/reusable-build-governance',h)).data.reusableBuildGovernance.validation.ok,true);}finally{await new Promise(r=>server.close(r));}
console.log('fifth-pass-governance-v1762.test.js passed');})().catch(err=>{console.error(err);try{server.close(()=>{});}catch{}process.exit(1);});
