'use strict';
const assert=require('assert');
const fs=require('fs');
const os=require('os');
const path=require('path');
const root=path.join(__dirname,'..');
const tempStorage=fs.mkdtempSync(path.join(os.tmpdir(),'smarter-justice-v1751-'));
process.env.SMARTER_JUSTICE_STORAGE_DIR=tempStorage;
process.env.NODE_ENV='test';
for(const key of ['PUBLIC_FREE_LAUNCH_APPROVED','ATTORNEY_APPLICATIONS_LAUNCH_APPROVED','PROFESSIONAL_GROWTH_LAUNCH_APPROVED','PROFESSIONAL_PILOT_ACTIVATION_APPROVED','DOMESTIC_VIOLENCE_AID_DESTINATION_VERIFIED']) delete process.env[key];
(async()=>{try{
  const store=require('../lib/store');await store.init();
  const registry=require('../data/fourPortalLaunchV1751');
  const pilots=require('../data/initialLaunchPilots');
  const aliases=require('../data/professionalPortalAliases');
  const standards=require('../data/initialPortalProfileStandards');
  const contracts=require('../data/portalIntegrationContracts');
  const activation=require('../lib/launchActivation');
  const cohort=require('../lib/launchCohortOperations');
  const operating=require('../lib/legalPortfolioOperatingSystem');
  const pkg=require('../package.json');
  const ids=['divorce-law-aid','estate-law-aid','personal-injury-law-aid','domestic-violence-aid'];
  assert.equal(pkg.version,'1.7.83');
  assert.equal(pkg.scripts.test.split(' && ').length,145);
  assert(!pkg.scripts.test.includes('storage-readiness.test.js'));
  assert.deepEqual(registry.fourPortalIds(),ids);
  assert.deepEqual(registry.HISTORICAL_THREE_PORTAL_IDS,ids.slice(0,3));
  assert.deepEqual(pilots.listInitialLaunchPilots().map(x=>x.portalId),ids);
  const dv=registry.getFourPortal('domestic-violence-aid');
  assert.equal(dv.artifact.filename,'domestic-violence-aid-v0.31.0.zip');
  assert.equal(dv.artifact.sha256,'e39ac3c2bb5952e539ff8740a107c847fbb14882deabf7c45ca852fd3546191f');
  assert.equal(dv.artifact.sizeBytes,1034010);
  assert.equal(dv.domain,'','an unconfirmed Domestic Violence Aid domain must not be invented');
  assert.equal(dv.embeddedInitiative.name,'The Stop Sign Project');
  assert.equal(dv.embeddedInitiative.automaticRecordReassignment,false);
  assert.equal(registry.DOMESTIC_VIOLENCE_SAFETY_REQUIREMENTS.length,9);
  const legacy=aliases.resolveProfessionalPortalId('domestic-violence-safety-support');
  assert.equal(legacy.state,'UNRESOLVED_LEGACY_ALIAS');
  assert.equal(legacy.canonicalPortalId,null);
  assert.equal(aliases.PILOT_COMPATIBILITY_POLICY.automaticRecordReassignment,false);
  const dvStandard=standards.getInitialPortalProfileStandard('domestic-violence-aid');
  assert.equal(dvStandard.safetyCritical,true);
  assert.equal(dvStandard.organizationAuthoritySupportedCentrally,false);
  const dvContract=contracts.PORTAL_INTEGRATION_CONTRACTS.find(x=>x.portalSlug==='domestic-violence-aid');
  assert(dvContract);
  assert.equal(dvContract.organizationAuthorityStatus,'NOT_IMPLEMENTED_CENTRALLY');
  assert.equal(dvContract.liveVerified,false);
  assert.equal(dvContract.ownerActivationApproved,false);
  assert(dvContract.publicDataBoundary.includes('no survivor narrative'));
  const view=activation.ownerView();
  assert.deepEqual(view.portals.map(x=>x.id),ids);
  for(const requirement of registry.DOMESTIC_VIOLENCE_SAFETY_REQUIREMENTS) assert(view.blockers.some(x=>x.key===requirement.key),requirement.key);
  for(const type of ['domestic-violence-safe-entry','domestic-violence-quick-exit','domestic-violence-confidential-location','domestic-violence-safe-contact','stop-sign-project-continuity']) assert(view.rehearsalSummary.requiredTypes.includes(type),type);
  assert.deepEqual(cohort.ownerView().cohort.portalIds,ids);
  assert.deepEqual(cohort.inferPortals(['Domestic violence','order of protection']),['domestic-violence-aid']);
  assert.deepEqual(operating.ownerView().summary.pilotOrder,ids);
  assert.equal(operating.ownerView().summary.openGates,0);
  const page=fs.readFileSync(path.join(root,'public','domestic-violence-aid.html'),'utf8');
  assert.match(page,/noindex,nofollow,noarchive/i);
  assert.match(page,/referrer[^>]*no-referrer/i);
  assert.match(page,/Quick Exit button leaves this page, but it does not erase/i);
  assert.match(page,/does not (?:auto)?save/i);
  assert.match(page,/The Stop Sign Project/i);
  assert.match(page,/confidential shelter/i);
  assert(!/<form\b/i.test(page));
  assert(!/\b\d{3}[-.) ]\d{3}[- ]\d{4}\b/.test(page),'no unverified hotline or service number may be embedded');
  const script=fs.readFileSync(path.join(root,'public','domestic-violence-aid.js'),'utf8');
  assert.match(script,/window\.location\.replace/);
  assert.match(script,/cache:'no-store'/);
  assert.match(script,/referrerPolicy:'no-referrer'/);
  const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
  assert(server.includes("'/domestic-violence-aid.html'"));
  assert(server.includes('DOMESTIC_VIOLENCE_AID_DESTINATION_VERIFIED'));
  const home=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
  assert.match(home,/Four focused legal portals, one central profile system/);
  assert.match(home,/Domestic Violence Aid/);
  const attorney=fs.readFileSync(path.join(root,'public','attorney-launch.html'),'utf8');
  assert.match(attorney,/Domestic Violence Aid/);
  const owner=fs.readFileSync(path.join(root,'public','launch-activation.html'),'utf8');
  assert.match(owner,/Turn the four-portal launch/);
  assert.match(owner,/value="domestic-violence-aid"/);
  console.log('four-portal-domestic-violence-v1751.test.js passed');
}finally{fs.rmSync(tempStorage,{recursive:true,force:true});}})().catch(error=>{console.error(error);process.exitCode=1;});
