'use strict';
const assert=require('assert');const fs=require('fs');const path=require('path');const os=require('os');const http=require('http');const root=path.join(__dirname,'..');
process.env.NODE_ENV='test';process.env.SMARTER_JUSTICE_STORAGE_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'sj-fourth-pass-v1761-'));process.env.OWNER_CONTROL_CENTER_TOKEN='owner-fourth-pass-v1761-token-123456789';
const authority=require('../lib/initialPortalAuthority');const discovery=require('../lib/portalAuthorityDiscovery');const commercial=require('../lib/commercialTerms');const freemium=require('../lib/publicFreemium');const governance=require('../lib/reusableBuildGovernance');const store=require('../lib/store');const server=require('../server');
function request(base,pathname,headers={}){return new Promise((resolve,reject)=>{const req=http.request(new URL(pathname,base),{headers},res=>{const chunks=[];res.on('data',c=>chunks.push(c));res.on('end',()=>{let data=null;try{data=JSON.parse(Buffer.concat(chunks).toString('utf8'));}catch{}resolve({status:res.statusCode,data});});});req.on('error',reject);req.end();});}
(async()=>{const pkg=require('../package.json'),manifest=require('../portal-manifest.json'),intake=require('../REUSABLE_MASTER_COMMAND_INTAKE_V1.7.75.json');assert.equal(pkg.version,'1.7.83');assert.equal(pkg.scripts.test.split(' && ').length,145);assert.equal(manifest.dependencyIndependentTestParts,145);assert.equal(manifest.testSuiteParts,146);assert.equal(manifest.releaseEvidence,'RELEASE_EVIDENCE_V1.7.83.json');assert.equal(manifest.initialPortalAuthority,'INITIAL_PORTAL_AUTHORITY_V1.7.75.json');
assert.equal(intake.prompt.sha256,'5dad361bae18b25dc8193ce32ca4263a72b12ce90316d6b97dbd191ce2b74223');assert.equal(intake.prompt.sizeBytes,383921);assert.equal(intake.prompt.lineCount,8204);assert.equal(intake.implementationTruthSource,'smarter-justice-v1.7.73.zip');assert.equal(intake.nextVersionDerived,'1.7.75');
const a=authority.validate();assert.equal(a.ok,true,a.errors.join('\n'));assert.equal(a.advancedCount,0);assert.equal(a.completeIdentityCount,3);assert.equal(a.versionOnlyCount,1);const expected={'divorce-law-aid':'0.44.0','estate-law-aid':'1.1.67','personal-injury-law-aid':'0.66.0','domestic-violence-aid':'0.49.0'};for(const [id,v] of Object.entries(expected))assert.equal(authority.artifactFor(id).version,v);
const cont=fs.readFileSync(path.join(root,'CONTINUATION_PROMPT_V1.7.75.md'),'utf8');assert(cont.includes('EXPECTED NEXT VERSION IF BASE REMAINS CURRENT: v1.7.76'));assert(cont.includes('END OF SMARTER JUSTICE CENTRAL MASTER FIFTEENTH-PASS SUNDAY LAUNCH-DAY ORCHESTRATION FINAL CONTINUATION'));assert.equal((cont.match(/^SMARTER JUSTICE$/gm)||[]).length,1);const master=fs.readFileSync(path.join(root,'governance/masters/Smarter_Justice_Central_Master_Fourteenth_Pass.txt'),'utf8');const d=discovery.validate(master);assert.equal(d.ok,true,d.errors.join('\n'));
assert.equal(commercial.validate().ok,true);assert.equal(commercial.quoteIndividual().monthlyTotalCents,1500);assert.equal(commercial.quoteFirm(1).monthlyTotalCents,3000);assert.equal(commercial.quoteFirm(3).monthlyTotalCents,6000);assert.equal(commercial.validatePayers([{attorneyProfileId:'a1',payerId:'p1',active:true},{attorneyProfileId:'a1',payerId:'p2',active:true}]).ok,false);assert.equal(freemium.validate().ok,true);assert.equal(governance.validate().ok,true,governance.validate().errors.join('\n'));
const pricing=fs.readFileSync(path.join(root,'public/pricing.html'),'utf8');assert(pricing.includes('$15<span>/firm/month</span>'));assert(pricing.includes('plus $15 per covered attorney each month'));assert(pricing.includes('One covered attorney: $30 per month total'));assert(!/\$150 billed annually|10% off 2|15% off 5|25% discount/.test(pricing));
await store.init();const addr=await new Promise(r=>server.listen(0,'127.0.0.1',()=>r(server.address())));const base=`http://127.0.0.1:${addr.port}`;try{for(const route of ['/api/owner/portal-authority-discovery','/api/owner/commercial-terms','/api/owner/public-freemium-floor'])assert.equal((await request(base,route)).status,403);const h={'x-owner-control-token':process.env.OWNER_CONTROL_CENTER_TOKEN};assert.equal((await request(base,'/api/owner/portal-authority-discovery',h)).data.portalAuthorityDiscovery.validation.ok,true);assert.equal((await request(base,'/api/owner/commercial-terms',h)).data.commercialTerms.validation.ok,true);assert.equal((await request(base,'/api/owner/public-freemium-floor',h)).data.publicFreemium.validation.ok,true);}finally{await new Promise(r=>server.close(r));}
console.log('fourth-pass-governance-v1761.test.js passed');})().catch(err=>{console.error(err);try{server.close(()=>{});}catch{}process.exit(1);});
