'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const pkg=require('../package.json');
const rules=require('../data/masterRulesPack');
const handoffSchema=require('../data/professionalPortalHandoffSchema');
const network=require('../lib/professionalNetwork');
const adapter=require('../lib/professionalPortalAdapter');
const portfolio=require('../lib/portfolioTruth');
assert.equal(pkg.version,'1.7.83');
assert.equal(pkg.scripts.test.split(' && ').length,145);
assert.equal(rules.MASTER_RULES_PACK_VERSION,'1.7.0');
assert.equal(handoffSchema.PROFESSIONAL_PORTAL_HANDOFF_SCHEMA_VERSION,'1.4.0');
assert.equal(handoffSchema.INTEGRATED_PORTAL_STANDARD_VERSION,'1.0.0');
const standard=fs.readFileSync(path.join(root,'LEGAL_MICRO_PORTAL_INTEGRATED_STANDARD_V1.0.0.md'),'utf8');
for(const phrase of ['DUAL MISSION','NO DECORATIVE PILLS OR OVALS','eqw2-r5nb','ATTORNEY-SPECIFIC PRACTICE EVIDENCE','REQUIRED REPORTING','FINAL TESTING AND DELIVERY'])assert(standard.includes(phrase),phrase);
for(const file of ['PORTAL_CONTINUATION_PROMPT_STANDARD.md','BUILD_PROGRAM_STANDARD.md','SMARTER_JUSTICE_MASTER_RULES_AND_SUGGESTIONS_PACK.md','CONTINUATION_PROMPT_V1.7.41.md'])assert(fs.readFileSync(path.join(root,file),'utf8').includes('LEGAL_MICRO_PORTAL_INTEGRATED_STANDARD_V1.0.0.md'),file);
const handoff=network.portalHandoff('employment-law-aid');
assert.equal(handoff.handoffVersion,'1.4.0');
assert.equal(handoff.portalBuildStandard.standardVersion,'1.0.0');
assert.equal(handoff.portalBuildStandard.dualMissionRequired,true);
assert.equal(handoff.portalBuildStandard.profileMetricsRequired,true);
assert.equal(handoff.portalBuildStandard.completeSurfaceAuditRequired,true);
assert.equal(adapter.validateHandoff(handoff,'employment-law-aid').valid,true);
const invalid=JSON.parse(JSON.stringify(handoff)); invalid.portalBuildStandard.profileMetricsRequired=false; assert.equal(adapter.validateHandoff(invalid,'employment-law-aid').valid,false);
const view=portfolio.ownerView();
assert.equal(view.releaseVersion,'1.7.75');
assert.equal(view.summary.portalCount,26);
assert.equal(view.summary.exactVerified,0);
assert.equal(view.summary.candidatePendingExactAcceptance,0);
assert.equal(view.summary.finalPackageAcceptedDetachedIdentity,1);
assert.equal(view.summary.ownerRecorded,25);
assert.equal(view.summary.missing,0);
assert.equal(view.summary.completeIdentities,18);
assert.equal(view.summary.detachedSelfIdentities,1);
assert.equal(view.portals.find(x=>x.portalId==='car-accident-law-aid').version,'0.5.0');
assert.equal(view.portals.find(x=>x.portalId==='business-launch-desk').version,'0.2.55');
assert.equal(view.portals.find(x=>x.portalId==='justice-tax-solutions').version,'0.1.121');
assert.equal(view.portals.find(x=>x.portalId==='coverednyc').version,'1.0.68');
const next=require('../NEXT_VERSION_IMPROVEMENT_LIST.json');
assert.equal(next.releaseVersion,'1.7.83');
assert.equal(next.items.length,34);
assert(next.items.every(x=>x.priority&&x.status&&x.benefit&&x.evidence&&x.dependency&&x.risk&&x.acceptanceCriteria&&x.targetPhase));
assert(next.items.some(x=>/four-portal staging/i.test(x.item)));
assert(next.items.some(x=>/Domestic Violence current emergency/i.test(x.item)));
assert.equal(require('../server-version-helper').version,'1.7.83');
console.log('integrated-portal-standard-v1737.test.js passed');
