'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const {spawnSync}=require('child_process');
const root=path.join(__dirname,'..');
const pkg=require('../package.json');
const center=require('../lib/launchCommandCenter');
const sprint=require('../data/launchSprintV1738');
assert.equal(pkg.version,'1.7.83');
assert.equal(pkg.scripts.test.split(' && ').length,145);
assert.equal(require('../server-version-helper').version,'1.7.83');
assert.equal(sprint.TARGET_RELEASE_VERSION,'1.7.75');
assert.equal(sprint.LAUNCH_SPRINT.launchLanes.length,4);
const owner=center.ownerView();
assert.equal(owner.targetReleaseVersion,'1.7.75');
assert.deepEqual(owner.lanes.map(x=>x.id),['public-free','free-professional-profiles','paid-membership','paid-professional-growth']);
assert(owner.lanes.every(x=>['GO','NO_GO'].includes(x.status)));
assert(owner.closedUnlessSeparatelyApproved.includes('Deployment'));
const publicView=center.publicStatus();
assert.equal(publicView.publicStartingHelp.available,true);
assert.equal(publicView.professionalGrowth.available,false);
assert.equal(publicView.paidMembership.available,false);
assert(/No membership payment/.test(publicView.paidMembership.detail));
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
for(const route of ['/api/public/launch-status','/api/owner/launch-command-center'])assert(server.includes(route),route);
const page=fs.readFileSync(path.join(root,'public','launch-status.html'),'utf8');
assert(page.includes('Current availability'));
assert(page.includes('data-launch-status'));
assert(!/guaranteed clients|guaranteed revenue/i.test(page));
const env=fs.readFileSync(path.join(root,'.env.launch.example'),'utf8');
for(const key of ['PUBLIC_FREE_LAUNCH_APPROVED=false','ATTORNEY_APPLICATIONS_LAUNCH_APPROVED=false','PROFESSIONAL_GROWTH_LAUNCH_APPROVED=false','PROFESSIONAL_PILOT_ACTIVATION_APPROVED=false','LAUNCH_ROLLBACK_SHA256='])assert(env.includes(key),key);
const runbook=fs.readFileSync(path.join(root,'LAUNCH_RUNBOOK_48_HOUR_V1.7.50.md'),'utf8');
for(const phrase of ['free profile claiming','paid membership','sponsored visibility','case-opportunity access','All gates default closed'])assert(runbook.includes(phrase),phrase);
const preflight=spawnSync(process.execPath,[path.join(root,'scripts','launch-preflight-v1738.js'),'--json'],{encoding:'utf8',env:{...process.env,NODE_ENV:'test'}});
assert.equal(preflight.status,0);
const parsed=JSON.parse(preflight.stdout);
assert.equal(parsed.version,'1.7.75');
assert.equal(parsed.lanes.length,4);
console.log('launch-readiness-v1738.test.js passed');
