'use strict';
const assert=require('assert');
const fs=require('fs');
const os=require('os');
const path=require('path');
const tempStorage=fs.mkdtempSync(path.join(os.tmpdir(),'smarter-justice-v1748-'));
process.env.SMARTER_JUSTICE_STORAGE_DIR=tempStorage;
process.env.NODE_ENV='test';
process.env.APP_BASE_URL='https://smarterjustice.example';
(async()=>{try{
  const store=require('../lib/store');await store.init();
  const cohort=require('../lib/launchCohortOperations');
  const outreach=require('../lib/launchOutreachOperations');
  const pkg=require('../package.json');
  assert.equal(pkg.version,'1.7.83');
  assert.equal(outreach.TARGET_RELEASE_VERSION,'1.7.75');
  const contact=cohort.createContact({professionalName:'Jordan Outreach',firmName:'Outreach Law PLLC',email:'jordan@example.test',campaignCode:'ATTORNEY-LAUNCH-NYC',portalIds:['divorce-law-aid'],status:'invite-ready'},'test-owner').contact;
  const issued=outreach.issueInvitation(contact.id,{expiresInDays:7},'test-owner');
  assert(issued.link.startsWith('https://smarterjustice.example/attorney-launch.html?'));
  assert(issued.oneTimeDisplay);
  assert(!JSON.stringify(outreach.ownerView()).includes(issued.link.split('invite=')[1]),'raw token must not be stored or returned in owner state');
  const token=new URL(issued.link).searchParams.get('invite');
  const resolved=outreach.resolveInvitation(token);
  assert.equal(resolved.invitation.professionalName,'Jordan Outreach');
  assert.deepEqual(resolved.invitation.portalIds,['divorce-law-aid']);
  assert(!('email' in resolved.invitation),'public invitation must not expose contact email');
  const opened=outreach.recordInvitationOpen(token);
  assert.equal(opened.invitation.status,'opened');
  const response=cohort.publicInterest({name:'Jordan Outreach',firmName:'Outreach Law PLLC',email:'jordan@example.test',campaignCode:'ATTORNEY-LAUNCH-NYC',portalIds:['divorce-law-aid'],consentToContact:true},{existingContactId:resolved.contactId});
  assert.equal(response.reusedExistingContact,true);
  const redeemed=outreach.redeemInvitation(token,response.confirmationId,'test-attorney');
  assert.equal(redeemed.invitation.status,'redeemed');
  assert.equal(cohort.ownerView().contacts.length,1,'personalized invitation response must reuse the existing outreach contact');

  const campaign=outreach.upsertCampaign({code:'PUBLIC-BROOKLYN-01',name:'Brooklyn public QR',audience:'public',status:'active',channel:'QR',location:'Brooklyn',landingPath:'/'},'test-owner');
  assert.equal(campaign.campaign.code,'PUBLIC-BROOKLYN-01');
  const event=outreach.recordEvent({campaignCode:'PUBLIC-BROOKLYN-01',eventType:'landing-view',audience:'public'},'test-public');
  assert(event.recorded);
  outreach.recordEvent({campaignCode:'PUBLIC-BROOKLYN-01',eventType:'public-start-submitted',portalId:'estate-law-aid',audience:'public'},'test-public');
  const owner=outreach.ownerView();
  assert.equal(owner.summary.aggregateEvents>=4,true);
  assert.equal(owner.privacyBoundary.storesLegalNarratives,false);
  assert.equal(owner.privacyBoundary.storesIpAddresses,false);
  assert.equal(owner.privacyBoundary.storesInvitationRawTokens,false);
  assert.match(outreach.exportCsv(),/PUBLIC-BROOKLYN-01/);
  assert.equal(outreach.recordEvent({campaignCode:'UNKNOWN',eventType:'landing-view'}).ignored,true);

  const root=path.join(__dirname,'..');
  const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
  for(const route of ['/api/public/launch-invitation','/api/public/launch-event','/api/owner/launch-outreach','/api/owner/launch-outreach/export.csv'])assert(server.includes(route),route);
  const attorney=fs.readFileSync(path.join(root,'public','attorney-launch.js'),'utf8');
  assert.match(attorney,/inviteToken/);
  assert.match(attorney,/Personalized free-profile invitation confirmed/);
  assert.match(attorney,/history\.replaceState/,'raw invitation token should be removed from the visible browser URL after validation');
  const home=fs.readFileSync(path.join(root,'public','home.js'),'utf8');
  assert.match(home,/public-start-submitted/);
  assert.match(home,/portal-direction-shown/);
  const activation=fs.readFileSync(path.join(root,'public','launch-activation.html'),'utf8');
  assert.match(activation,/Personalized invitations and privacy-minimized launch funnel/);
  assert.match(activation,/raw tokens are shown once and never stored/i);
  console.log('launch-outreach-conversion-v1748.test.js passed');
}finally{fs.rmSync(tempStorage,{recursive:true,force:true});}})().catch(error=>{console.error(error);process.exitCode=1;});
