'use strict';
const assert=require('assert');
const fs=require('fs');
const os=require('os');
const path=require('path');
const tempStorage=fs.mkdtempSync(path.join(os.tmpdir(),'smarter-justice-v1746-'));
process.env.SMARTER_JUSTICE_STORAGE_DIR=tempStorage;
process.env.NODE_ENV='test';
process.env.APP_BASE_URL='http://localhost:3000';
for(const key of ['PUBLIC_FREE_LAUNCH_APPROVED','ATTORNEY_APPLICATIONS_LAUNCH_APPROVED','PROFESSIONAL_GROWTH_LAUNCH_APPROVED','PROFESSIONAL_PILOT_ACTIVATION_APPROVED']) delete process.env[key];
(async()=>{try{
  const store=require('../lib/store');await store.init();
  const activation=require('../lib/launchActivation');
  const command=require('../lib/launchCommandCenter');
  const pkg=require('../package.json');
  assert.equal(pkg.version,'1.7.83');
  assert.equal(activation.TARGET_RELEASE_VERSION,'1.7.75');
  const initial=activation.ownerView();
  assert.equal(initial.launchCommand.overallStatus,'NO_GO');
  assert.equal(initial.activationBoundary.canOpenLiveGate,false);
  assert.deepEqual(initial.portals.map(x=>x.id),['divorce-law-aid','estate-law-aid','personal-injury-law-aid','domestic-violence-aid']);
  assert(initial.blockers.length>0);
  assert(initial.summary.p0Blockers>0);
  assert.equal(new Set(initial.blockers.map(x=>x.key)).size,initial.blockers.length,'blockers must be deduplicated across lanes');
  assert(initial.rehearsalSummary.requiredTypes.includes('mobile-qr'));
  assert(initial.rehearsalSummary.requiredTypes.includes('rollback'));

  const plan=activation.updatePlan({status:'evidence-in-progress',targetDate:'2026-08-03',cohortName:'First 12 NYC Attorneys',cohortCap:12,supportOwner:'Roger',incidentOwner:'Roger',launchPortals:['divorce-law-aid','estate-law-aid','personal-injury-law-aid','domestic-violence-aid']},'test-owner');
  assert.equal(plan.plan.cohortCap,12);assert.equal(plan.plan.status,'evidence-in-progress');
  const blocker=initial.blockers[0];
  const evidence=activation.recordEvidence({checkKey:blocker.key,title:'Recorded evidence only',status:'accepted',owner:'Roger',reference:'TEST-REFERENCE',evidence:['Owner-reviewed test record']},'test-owner');
  assert(evidence.evidence.id);
  assert.equal(command.ownerView().overallStatus,'NO_GO','workbench evidence must not open environment or owner gates');
  const rehearsal=activation.recordRehearsal({type:'mobile-qr',status:'passed',title:'Phone QR rehearsal',device:'narrow phone',operator:'Roger',evidence:['TEST-MOBILE-QR']},'test-owner');
  assert.equal(rehearsal.rehearsal.status,'passed');
  const issue=activation.recordIssue({title:'SMTP not configured',severity:'critical',status:'open',owner:'Roger',area:'email',pauseTrigger:true,description:'No live email delivery evidence.'},'test-owner');
  assert.equal(issue.issue.pauseTrigger,true);
  const updated=activation.ownerView();
  assert(updated.summary.acceptedWorkbenchEvidence>=1);
  assert(updated.summary.criticalIssues>=1);
  assert(updated.rehearsalSummary.passedTypes.includes('mobile-qr'));
  assert.match(activation.exportMarkdown(),/Four-Portal Launch Activation Packet/);
  assert.match(activation.exportMarkdown(),/Fail-closed status/);

  const root=path.join(__dirname,'..');
  const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
  for(const route of ['/api/owner/launch-activation','/api/owner/launch-activation/plan','/api/owner/launch-activation/evidence','/api/owner/launch-activation/rehearsals','/api/owner/launch-activation/issues'])assert(server.includes(route),route);
  assert(server.includes("'/launch-activation.html'"));
  const ownerPage=fs.readFileSync(path.join(root,'public','launch-activation.html'),'utf8');
  assert.match(ownerPage,/cannot deploy, publish profiles, open payments, or activate a live gate/i);
  const attorneyPage=fs.readFileSync(path.join(root,'public','attorney-launch.html'),'utf8');
  assert.match(attorneyPage,/No payment is required to control a basic profile/);
  assert.match(attorneyPage,/Workers’ compensation and medical malpractice remain separate/);
  const home=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
  assert.match(home,/Four focused legal portals, one central profile system/);
  assert(!/\$15|planned founding monthly price/i.test(home));
  const membership=fs.readFileSync(path.join(root,'public','professional-membership.html'),'utf8');
  assert.match(membership,/\$15<span>\/month<\/span>/);
  assert.match(membership,/plus \$15 per covered attorney each month/);
  assert(!/\$150|10% off 2|15% off 5|20% off 10|25% discount|Annual plans/i.test(membership));
  const launchStatus=fs.readFileSync(path.join(root,'public','launch-status.html'),'utf8');
  assert(!/invitation-only profile-pilot|founding-attorney applications/i.test(launchStatus));
  console.log('launch-activation-v1746.test.js passed');
}finally{fs.rmSync(tempStorage,{recursive:true,force:true});}})().catch(error=>{console.error(error);process.exitCode=1;});
