'use strict';
const assert=require('assert');const fs=require('fs');const os=require('os');const path=require('path');
process.env.NODE_ENV='test';process.env.SMARTER_JUSTICE_STORAGE_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'sj-legal-scope-v1729-'));
const legal=require('../lib/legalPortalWorkspace');const command=require('../data/legalPortalCommandCenterV1729').getLegalPortalCommandCenter();
const view=legal.ownerView();
assert.equal(view.schemaVersion,'2.4.0');
assert(/Smarter Justice/.test(view.scope));
assert(/legal micro- and mid-sized portals/i.test(view.scope));
assert.equal(view.summary.portalCount,26);
assert.equal(view.summary.outOfScopeRecords,0);
assert.equal(view.summary.neutralBoardroomConnection,'DORMANT_OPTIONAL_EXPORT_ONLY');
assert(!view.portals.some(x=>['smarter-money','smarter-health','smarter-property'].includes(x.id)));
assert(command.expresslyOutOfScope.some(x=>/Smarter Money/i.test(x)));
assert(command.expresslyOutOfScope.some(x=>/Smarter Health/i.test(x)));
assert(command.expresslyOutOfScope.some(x=>/Smarter Property/i.test(x)));
assert.equal(command.automaticCrossRepositorySynchronization,false);
assert.equal(command.automaticNeutralBoardroomWrites,false);
assert(/self-contained legal-portfolio/i.test(command.status));
assert(/self-contained/i.test(command.neutralBoardroomRelationship.topLayer));assert.equal(command.neutralBoardroomRelationship.launchCritical,false);
(async()=>{
  const rejected=await legal.updatePortal('smarter-health',{status:'testing'});assert(rejected.error);
  const server=fs.readFileSync(path.join(__dirname,'..','server.js'),'utf8');
  const html=fs.readFileSync(path.join(__dirname,'..','public','control-center.html'),'utf8');
  assert(server.includes('/api/owner/legal-portal-command-center'));
  assert(server.includes('/api/owner/legal-portal-workspace/export'));
  assert(server.includes('/api/owner/neutral-boardroom-handoff'));
  assert(!server.includes('/api/owner/ecosystem-workspace'));
  assert(!server.includes('/api/owner/ecosystem-command-center'));
  assert(html.includes('Smarter Justice Legal-Portal Control Center')||html.includes('Smarter Justice Legal-Network Control Center'));
  assert(!html.includes('Smarter Ecosystem Control Center'));
  console.log('legal-portal-scope-v1729.test.js passed');
})().catch(e=>{console.error(e);process.exit(1)});
