const assert=require('assert');
const fs=require('fs');
const os=require('os');
const path=require('path');
process.env.NODE_ENV='test';
process.env.SMARTER_JUSTICE_STORAGE_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'sj-migration-readiness-'));
process.env.DATABASE_URL='';
process.env.SENSITIVE_TRAFFIC_APPROVED='false';
process.env.PROFESSIONAL_PILOT_ACTIVATION_APPROVED='false';
process.env.SMTP_HOST='';process.env.SMTP_USER='';process.env.SMTP_PASS='';process.env.SMTP_FROM='';
process.env.STRIPE_SECRET_KEY='';process.env.STRIPE_WEBHOOK_SECRET='';
const migrations=require('../lib/migrations');
const readiness=require('../lib/operationalReadiness');
const store=require('../lib/store');
const manifest=JSON.parse(fs.readFileSync(path.join(__dirname,'..','portal-manifest.json'),'utf8'));
(async()=>{
  await store.init();
  const migrationManifest=migrations.manifest();
  assert.equal(migrationManifest.standardVersion,'1.0.0');
  assert(migrationManifest.migrations.length>=2);
  assert.equal(new Set(migrationManifest.migrations.map(item=>item.version)).size,migrationManifest.migrations.length);
  assert(migrationManifest.migrations.every(item=>/^[a-f0-9]{64}$/.test(item.checksum)));
  assert.equal(manifest.productionPaidPilotOperationalReadinessStandardVersion,'1.0.0');
  assert(fs.existsSync(path.join(__dirname,'..',manifest.productionPaidPilotOperationalReadinessStandard)));
  const checks=readiness.machineChecks();
  assert.equal(checks.ready,false,'paid-pilot activation must fail closed without external configuration and evidence');
  assert(checks.checks.some(item=>item.key==='explicit_owner_activation'&&!item.ready));
  assert(checks.checks.some(item=>item.key==='smtp_configured'&&!item.ready));
  assert(checks.checks.some(item=>item.key==='stripe_webhook'&&!item.ready));
  const source=fs.readFileSync(path.join(__dirname,'..','lib','store.js'),'utf8');
  assert(/pg_advisory_xact_lock/.test(source),'cross-instance mutations should use a PostgreSQL transaction lock');
  const server=fs.readFileSync(path.join(__dirname,'..','server.js'),'utf8');
  assert(/SENSITIVE_TRAFFIC_APPROVED/.test(server),'sensitive traffic must require an explicit activation flag');
  console.log('migrations-operational-readiness.test.js passed');
})().catch(error=>{console.error(error);process.exit(1);}).finally(()=>fs.rmSync(process.env.SMARTER_JUSTICE_STORAGE_DIR,{recursive:true,force:true}));
