'use strict';
const assert=require('assert');const fs=require('fs');const os=require('os');const path=require('path');const http=require('http');
process.env.NODE_ENV='test';process.env.SMARTER_JUSTICE_STORAGE_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'sj-ai-ops-v1778-'));process.env.OWNER_CONTROL_CENTER_TOKEN='owner-ai-ops-v1778-token-123456789';delete process.env.OPENAI_API_KEY;delete process.env.OPENAI_AI_ENABLED;process.env.AI_GLOBAL_KILL_SWITCH='true';
const governance=require('../lib/openAiLaunchGovernance');const gateway=require('../lib/centralAiGateway');const store=require('../lib/store');const server=require('../server');
function request(base,pathname,{method='GET',headers={},body=null}={}){return new Promise((resolve,reject)=>{const req=http.request(new URL(pathname,base),{method,headers},res=>{const chunks=[];res.on('data',c=>chunks.push(c));res.on('end',()=>{let data=null;try{data=JSON.parse(Buffer.concat(chunks).toString('utf8'));}catch{}resolve({status:res.statusCode,data});});});req.on('error',reject);if(body)req.write(JSON.stringify(body));req.end();});}
(async()=>{
 const pkg=require('../package.json'),manifest=require('../portal-manifest.json'),contract=require('../AI_GATEWAY_CONTRACT_V1.7.81.json'),model=require('../AI_MODEL_CONFIGURATION_V1.7.81.json'),registry=require('../AI_TOOL_AND_PROMPT_REGISTRY_V1.7.81.json'),matrix=require('../FIVE_PRODUCT_AI_CAPABILITY_MATRIX_V1.7.81.json'),checkpoint=require('../OPENAI_LAUNCH_OVERLAY_CHECKPOINT_V1.7.81.json');
 assert.equal(pkg.version,'1.7.83');assert.equal(pkg.scripts.test.split(' && ').length,145);assert.equal(manifest.dependencyIndependentTestParts,145);assert.equal(manifest.testSuiteParts,146);
 const validated=governance.validate();assert.equal(validated.ok,true,validated.errors.join('\n'));assert.equal(validated.launchBatchId,'SJP-OPENAI-LIVE-2026-08-03-BATCH-02');assert.equal(validated.registeredTools,5);assert.equal(contract.request.arbitraryPromptAccepted,false);assert.equal(model.api,'responses');assert.equal(model.storeResponses,false);assert.equal(registry.tools.length,5);assert.equal(matrix.products.length,5);assert.equal(matrix.products[4].maturity,'CLOSED_BY_DESIGN');assert.equal(checkpoint.overlaySha256,'a1d63886e22188304cff36df8ed5754169546c24fe094a4563c6c4184a6e63f4');
 const env=fs.readFileSync(path.join(__dirname,'..','.env.example'),'utf8');for(const token of ['ANTHROPIC_API_KEY','GOOGLE_API_KEY','GEMINI_API_KEY','XAI_API_KEY','AI_PROVIDER_ORDER'])assert(!env.includes(token),token);for(const token of ['OPENAI_API_KEY','OPENAI_AI_ENABLED','AI_GLOBAL_KILL_SWITCH','AI_COST_HARD_STOP','AI_PORTAL_SERVICE_TOKENS_JSON'])assert(env.includes(token),token);
 const publicStatus=gateway.publicStatus();assert.equal(publicStatus.available,false);assert.equal(publicStatus.vendor,'OpenAI only');assert.equal(publicStatus.noAttorneyClientRelationship,true);assert.equal(publicStatus.noPrivilegeCreated,true);assert.equal(publicStatus.deterministicFallback,true);assert.equal(publicStatus.launchState,'NO_GO');
 await store.init();await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;try{
  const ai=await request(base,'/api/ai-status');assert.equal(ai.status,200);assert.equal(ai.data.available,false);assert.equal(ai.data.vendor,'OpenAI only');assert.equal(ai.data.noAiOptionAvailable,true);assert.equal(ai.data.noAttorneyClientRelationship,true);assert.equal(ai.data.currentLawAnswersSupported,false);
  const unauth=await request(base,'/api/internal/ai-gateway/v1/tools/sj.starting_point_organizer.v1',{method:'POST',headers:{'content-type':'application/json'},body:{contractVersion:'sj-ai-gateway-v1.0.0',input:{}}});assert.equal(unauth.status,403);assert.equal(unauth.data.errorCode,'PORTAL_UNAUTHORIZED');
  assert.equal((await request(base,'/api/owner/ai-operations')).status,403);const headers={'x-owner-control-token':process.env.OWNER_CONTROL_CENTER_TOKEN};const owner=await request(base,'/api/owner/ai-operations',{headers});assert.equal(owner.status,200);assert.equal(owner.data.appVersion,'1.7.83');assert.equal(owner.data.aiOperations.runtime.keyConfigured,false);assert.equal(owner.data.aiOperations.runtime.globalKillSwitch,true);assert.equal(owner.data.openAiLaunchGovernance.validation.ok,true);assert.equal(owner.data.aiOperations.deploymentAuthorized,false);
  const cc=await request(base,'/api/owner/control-center',{headers});assert.equal(cc.status,200);assert.equal(cc.data.version,'1.7.83');assert.equal(cc.data.aiOperations.runtime.productionActive,false);assert.equal(cc.data.openAiLaunchGovernance.validation.launchState,'NO_GO');
 }finally{await new Promise(r=>server.close(r));}
 console.log('openai-ai-operations-v1778.test.js passed');
})().catch(error=>{console.error(error);try{server.close(()=>{});}catch{}process.exit(1);});
