'use strict';
const assert=require('assert');const http=require('http');const packet=require('../lib/ownerLaunchActionPacket');
process.env.SMARTER_JUSTICE_STORAGE_DIR=require('fs').mkdtempSync(require('path').join(require('os').tmpdir(),'sj-launch-packet-v1767-'));
process.env.OWNER_CONTROL_CENTER_TOKEN='owner-launch-packet-v1767-token-123456789';process.env.PORT='0';
function request(base,path,headers={}){return new Promise((resolve,reject)=>{const u=new URL(path,base);const req=http.request({hostname:u.hostname,port:u.port,path:u.pathname+u.search,method:'GET',headers},res=>{let body='';res.on('data',c=>body+=c);res.on('end',()=>{let data={};try{data=JSON.parse(body)}catch{}resolve({status:res.statusCode,data});});});req.on('error',reject);req.end();});}
(async()=>{const v=packet.validate();assert.equal(v.ok,true);assert.equal(v.releaseVersion,'1.7.75');assert.equal(v.requestCount,10);assert.equal(v.readyNowCount,4);assert.equal(v.qualifiedReviewCount,2);assert.equal(v.candidateDependentCount,2);assert.equal(v.deferredCount,2);
 const view=packet.ownerView();const stale=JSON.parse(JSON.stringify(view.packet));stale.sourceQueue='OWNER_ACTION_QUEUE_V1.7.60.json';assert.equal(packet.validate(stale).ok,false);assert(packet.validate(stale).errors.includes('current-source-binding'));
 const q=require('../OWNER_ACTION_QUEUE_V1.7.68.json');const bad=JSON.parse(JSON.stringify(q));bad.requests[0].ownerAction='Paste the API key into chat.';assert.equal(packet.validate(view.packet,bad,require('../OWNER_ACTION_READINESS_V1.7.68.json')).ok,false);
 const server=require('../server');await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;try{assert.equal((await request(base,'/api/owner/launch-action-packet')).status,403);const h={'x-owner-control-token':process.env.OWNER_CONTROL_CENTER_TOKEN};const allowed=await request(base,'/api/owner/launch-action-packet',h);assert.equal(allowed.status,200);assert.equal(allowed.data.appVersion,'1.7.83');assert.equal(allowed.data.ownerLaunchActionPacket.validation.ok,true);const cc=await request(base,'/api/owner/control-center',h);assert.equal(cc.status,200);assert.equal(cc.data.ownerLaunchActionPacket.validation.ok,true);}finally{await new Promise(r=>server.close(r));}
 console.log('owner-launch-action-packet-v1767.test.js passed');})().catch(err=>{console.error(err);process.exit(1);});
