const assert=require('assert');
const fs=require('fs');
const os=require('os');
const path=require('path');
process.env.NODE_ENV='test';
process.env.ALLOW_TEST_PAID_PILOT_GATE='true';
process.env.SMARTER_JUSTICE_STORAGE_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'sj-pilot-program-test-'));
const store=require('../lib/store');
const pilot=require('../lib/pilotProgram');
const marketplace=require('../lib/professionalMarketplace');
(async()=>{
 await store.init();
 store.writeJson('pilotProgram.json',null);
 const created=marketplace.createProfessional({displayName:'Test Lawyer',email:'lawyer@example.test',phone:'212-555-0199',biography:'Test Lawyer maintains a complete private professional profile for the controlled founding membership regression workflow.',officeLocations:['26 Court Street, Brooklyn, NY'],jurisdictions:['New York'],practiceAreas:['Family law'],languages:['English'],serviceRegions:['Brooklyn'],consultationModes:['video'],availabilityStatus:'accepting inquiries',portalEligibility:['digital-divorce'],credentials:[{credentialType:'Attorney registration',jurisdiction:'New York',identifier:'NY-PILOT-TEST-001',verificationSource:'https://example.test/credential'}]},'pilot-program.test');
 const professionalId=created.professional.id;
 const credentialId=created.professional.credentials[0].id;
 marketplace.recordCredentialVerification(professionalId,{credentialId,status:'active',verificationSource:'https://example.test/credential',verificationScope:['New York attorney registration']});
 marketplace.updateProfessional(professionalId,{submittedRevision:1,reviewSubmittedAt:new Date().toISOString(),reviewStatus:'submitted'},'pilot-program.test');
 const profileReviewed=marketplace.updateProfessional(professionalId,{reviewStatus:'approved',ownerApprovalStatus:'approved'},'pilot-program.test');
 assert.strictEqual(profileReviewed.professional.reviewStatus,'approved');
 const account={id:'acct-test',email:'lawyer@example.test',displayName:'Test Lawyer',accountType:'professional',membershipTarget:{kind:'professional',id:professionalId,planId:'nyc-founding-professional',seatCount:1}};
 let view=pilot.professionalView(account.id); assert.strictEqual(view.controls.applicationsOpen,false); assert.strictEqual(view.paymentGate.available,false);
 let saved=await pilot.saveApplication(account,{targetKind:'professional',targetId:professionalId,portalInterests:['digital-divorce'],goals:'Test the founding workflow.'},'save-1'); assert(saved.application); let replay=await pilot.saveApplication(account,{targetKind:'professional',targetId:professionalId},'save-1'); assert.strictEqual(replay.idempotentReplay,true);
 let closed=await pilot.submitApplication(account,{targetKind:'professional',targetId:professionalId},'submit-closed'); assert(closed.error);
 await pilot.updateControls({applicationsOpen:true,maxSubmittedApplications:5,maxApprovedApplications:2});
 let missing=await pilot.submitApplication(account,{targetKind:'professional',targetId:professionalId},'submit-missing'); assert(missing.error);
 let submitted=await pilot.submitApplication(account,{targetKind:'professional',targetId:professionalId,acceptMembershipTerms:true,acceptPrivacy:true,acceptRecurringBilling:true,acceptNoGuarantees:true,acceptIndependentProfessional:true,acceptConflicts:true},'submit-1'); assert.strictEqual(submitted.application.status,'submitted');
 let owner=pilot.ownerView(); assert.strictEqual(owner.applications.length,1); assert.strictEqual(owner.queue.applicationQueue.length,1);
 let reviewed=await pilot.ownerReviewApplication(submitted.application.id,{status:'approved-for-payment'},'review-1'); assert.strictEqual(reviewed.application.status,'approved-for-payment'); assert.strictEqual(reviewed.application.paymentStatus,'blocked');
 let badGate=await pilot.updateControls({paymentGateEnabled:true}); assert(badGate.error);
 for(const item of pilot.ownerView().evidence) await pilot.updateEvidence(item.key,{status:'evidence-complete',summary:'Test evidence',verifiedBy:'automated test'});
 let controls=await pilot.updateControls({applicationsOpen:true,paymentGateEnabled:true,maxApprovedApplications:2}); assert.strictEqual(controls.paymentGate.available,true);
 let checkout=await pilot.markCheckoutStarted(account,'cs_test'); assert.strictEqual(checkout.application.paymentStatus,'checkout-started');
 let paid=await pilot.recordPayment(account.id,{status:'paid',reference:'cs_test'}); assert.strictEqual(paid.application.status,'active-member');
 let ticket=await pilot.createSupportTicket(account,{category:'Account and sign-in',subject:'Need account help',message:'Please help with the professional account workflow.'},'ticket-1'); assert(ticket.ticket); let ticketReplay=await pilot.createSupportTicket(account,{category:'x',subject:'x',message:'xxxxxxxxxx'},'ticket-1'); assert.strictEqual(ticketReplay.idempotentReplay,true);
 console.log('Paid founding-professional pilot tests passed.');
})().catch(err=>{console.error(err);process.exit(1);});
