'use strict';
const assert=require('assert');const fs=require('fs');const path=require('path');const portfolio=require('../lib/portfolioTruth');
const truth=require('../PORTFOLIO_TRUTH_V1.7.32.json');const contracts=require('../DASHBOARD_CONTRACTS_V1.7.32.json');const conformance=require('../DASHBOARD_CONFORMANCE_V1.7.32.json');
const validation=portfolio.validate();assert.deepEqual(validation,{ok:true,errors:[]});const summary=portfolio.summary();assert.equal(summary.portalCount,26);assert.equal(summary.exactVerified,0);assert.equal(summary.candidatePendingExactAcceptance,0);assert.equal(summary.finalPackageAcceptedDetachedIdentity,1);assert.equal(summary.ownerRecorded,25);assert.equal(summary.missing,0);assert.equal(summary.highestDashboardClaim,'D3_INTEGRATION_TESTED_LOCAL_ONLY');
assert.equal(truth.dataPrinciple,'CENTRALIZE_PORTFOLIO_METADATA_DECENTRALIZE_USER_MATTER_DATA');assert.equal(new Set(truth.portals.map(x=>x.portalId)).size,truth.portals.length);assert(truth.portals.every(x=>x.portalId&&x.releaseId&&x.artifactId&&x.sourceOfTruth&&x.nextAction));assert(truth.portals.filter(x=>x.evidenceState==='EXACT_VERIFIED').every(x=>/^[a-f0-9]{64}$/.test(x.sha256)&&x.sizeBytes>0));assert(truth.portals.filter(x=>x.evidenceState==='OWNER_RECORDED').every(x=>x.sourceOfTruth!=='Uploaded exact Smarter Justice artifact'));
assert(contracts.contracts.every(x=>Array.isArray(x.writeAuthority)&&Array.isArray(x.forbiddenDataClasses)));assert(contracts.contracts[0].writeAuthority.includes('none through this read-only contract'));assert(contracts.contracts.some(x=>x.forbiddenDataClasses.some(v=>/public-user matter contents/i.test(v))));assert.equal(conformance.highestClaim,'D2_CONTRACT_TESTED');assert(conformance.runs.some(x=>x.state==='D0_CONCEPT_ONLY'));assert(!conformance.runs.some(x=>['D3_INTEGRATION_TESTED','D4_STAGING_VERIFIED','D5_PRODUCTION_VERIFIED'].includes(x.state)));
const server=fs.readFileSync(path.join(__dirname,'..','server.js'),'utf8');const html=fs.readFileSync(path.join(__dirname,'..','public','control-center.html'),'utf8');const app=fs.readFileSync(path.join(__dirname,'..','public','app.js'),'utf8');
for(const route of ['/api/owner/portfolio-truth','/api/owner/dashboard-conformance'])assert(server.includes(route),route);assert(server.includes('if (!requireOwner(req))'), 'owner gate');for(const id of ['portfolioAttentionSection','portfolioTruthSummary','portfolioAttentionList','portfolioDecisionList'])assert(html.includes(id),id);assert(app.includes('renderPortfolioTruth'));assert(app.includes('downloadPortfolioTruth'));
console.log('portfolio-truth-dashboard-v1732.test.js passed');
