'use strict';
const assert=require('assert');
const fs=require('fs');
const os=require('os');
const path=require('path');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'sj-truth-'));
process.env.SMARTER_JUSTICE_STORAGE_DIR=temp;
const portfolio=require('../lib/portfolioTruth');
const controlCenter=require('../lib/controlCenter');
const truth=require('../PORTFOLIO_TRUTH_V1.7.50.json');
const contracts=require('../DASHBOARD_CONTRACTS_V1.7.50.json');
const conformance=require('../DASHBOARD_CONFORMANCE_V1.7.50.json');

const validation=portfolio.validate();
assert.deepEqual(validation,{ok:true,errors:[]});
const view=portfolio.ownerView();
assert.equal(view.releaseVersion,'1.7.75');
assert.equal(view.summary.portalCount,26);
assert.equal(view.summary.exactVerified,0);
assert.equal(view.summary.candidatePendingExactAcceptance,0);
assert.equal(view.summary.finalPackageAcceptedDetachedIdentity,1);
assert.equal(view.summary.productionVerified,0);
assert.equal(view.summary.ownerRecorded,25);
assert.equal(view.summary.missing,0);
assert.equal(view.summary.detachedSelfIdentities,1);
assert.equal(new Set(view.portals.map(row=>row.portalId)).size,26);
const self=view.portals.find(row=>row.portalId==='general-smarter-justice-start');
assert(self);
assert.equal(self.evidenceState,'FINAL_PACKAGE_ACCEPTED_DETACHED_IDENTITY');
assert.equal(self.artifactIdentityMode,'DETACHED_AFTER_PACKAGING');
assert.equal(self.detachedSelfIdentity,true);
assert.equal(self.exactIdentityPresent,false);
assert.equal(self.exactEvidenceSupported,true);
assert.equal(self.identityCompleteness.state,'DETACHED_SELF_IDENTITY');
assert.equal(portfolio.validExactIdentity(self),true);
assert(view.portals.filter(row=>row.evidenceState==='OWNER_RECORDED'&&row.identityCompleteness.state==='COMPLETE').every(row=>/^[a-f0-9]{64}$/.test(row.sha256)&&row.sizeBytes>0));
assert.equal(view.summary.completeIdentities,18);
assert(!view.portals.some(row=>['smarter-health','smarter-property','smarter-money'].includes(row.portalId)));
assert.equal(truth.currentRelease.status,'CANDIDATE_PENDING_FINAL_EXACT_ACCEPTANCE');
assert.equal(truth.currentRelease.identityLocation,'EXTERNAL_DELIVERY_REPORT');
assert.equal(conformance.highestClaim,'D3_INTEGRATION_TESTED_LOCAL_ONLY');
assert(contracts.contracts.some(row=>row.contractId.includes('legal-network-action-center')));
assert(contracts.contracts.every(row=>Array.isArray(row.writeAuthority)&&Array.isArray(row.forbiddenDataClasses)));

const control=controlCenter.getControlCenterData();
assert.equal(control.portals.length,26);
assert.equal(new Set(control.portals.map(row=>row.currentTruthPortalId)).size,26);
const truthById=new Map(view.portals.map(row=>[row.portalId,row]));
for(const row of control.portals){
  const current=truthById.get(row.currentTruthPortalId);
  assert(current,row.slug);
  assert.equal(row.latestDevelopmentVersion,current.version,row.slug);
  assert.equal(row.latestZipName,current.artifact,row.slug);
  assert.equal(row.artifactEvidenceState,current.evidenceState,row.slug);
}
assert(control.legalNetworkActionCenter);
assert.equal(control.neutralBoardroomHandoff.liveConnection,false);
assert.equal(control.neutralBoardroomHandoff.automaticWrites,false);
fs.rmSync(temp,{recursive:true,force:true});
console.log('portfolio-truth-reconciliation-v1734.test.js passed');
