'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const os=require('os');
const http=require('http');
const root=path.join(__dirname,'..');
process.env.NODE_ENV='test';
process.env.SMARTER_JUSTICE_STORAGE_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'sj-prof-network-'));
process.env.OWNER_CONTROL_CENTER_TOKEN='owner-professional-network-test-token-123456789';
const server=require('../server');
const store=require('../lib/store');
const professionalNetwork=require('../lib/professionalNetwork');
const standard=require('../data/professionalNetworkStandard');
function ownerHeaders(extra={}){return {'x-owner-control-token':process.env.OWNER_CONTROL_CENTER_TOKEN,...extra};}
function request(base,pathname,options={}){return new Promise((resolve,reject)=>{const url=new URL(pathname,base);const req=http.request(url,{method:options.method||'GET',headers:options.headers||{}},res=>{let body='';res.on('data',chunk=>body+=chunk);res.on('end',()=>{let data;try{data=JSON.parse(body||'{}');}catch{data={raw:body};}resolve({status:res.statusCode,data,headers:res.headers});});});req.on('error',reject);if(options.body)req.write(options.body);req.end();});}
(async()=>{
  await store.init();
  const first=professionalNetwork.ownerView();
  assert.equal(first.standardVersion,'1.4.0');
  assert.equal(first.contractVersion,'1.4.0');
  assert.equal(first.summary.organizations,48,'the current seeded directory resolves to 48 firm organizations; independent professionals would receive separate individual-practice organizations');
  assert.equal(first.summary.firmOrganizations,48);
  assert.equal(first.summary.seats,233);
  assert.equal(first.summary.portalContracts,26);
  assert.equal(first.summary.livePortalConnections,0);
  assert.equal(first.summary.automaticPortalWrites,0);
  assert.equal(first.gates.liveBilling,false);
  assert.equal(first.gates.publicCheckout,false);
  assert.equal(first.gates.publicInquiries,false);
  assert.equal(first.gates.appointmentBooking,false);
  assert.equal(first.gates.automaticPortalWrites,false);
  assert(Object.values(first.rules).some(value=>/one Smarter Justice account/i.test(value)));
  assert(Object.values(first.rules).some(value=>/firm.*organization account/i.test(value)));
  assert(Object.values(first.rules).some(value=>/firm practice page alone/i.test(value)));
  assert(first.portalContracts.every(row=>row.contractState==='D3_ADAPTER_TESTS_PASS'));
  assert(first.portalContracts.every(row=>row.liveConnection===false&&row.automaticWrites===false));
  assert(first.portalContracts.every(row=>row.rules.paymentDoesNotBuyVerification===true&&row.rules.individualEvidenceRequired===true));
  assert(standard.PORTAL_CONTRACT_PROHIBITED_FIELDS.some(value=>/user legal matters/i.test(value)));
  const immigration=professionalNetwork.portalHandoff('immigration-oasis');
  assert(immigration);
  assert.equal(immigration.containsUserMatterData,false);
  assert.equal(immigration.containsCredentials,false);
  assert.equal(immigration.containsPaymentData,false);
  assert.equal(immigration.automaticWrites,false);
  const sync=await professionalNetwork.synchronize('test-owner');
  assert(sync.run.id.startsWith('pro-network-sync'));
  assert.equal(sync.run.automaticPortalWrites,false);
  const after=professionalNetwork.ownerView();
  assert(after.synchronizationRuns.length>=1);
  const practice=after.practiceAssignments[0];
  assert(practice);
  const updatedPractice=await professionalNetwork.updatePracticeAssignment(practice.id,{status:'approved',ownerApproved:true,ownerNotes:'Test-only evidence review.'});
  assert.equal(updatedPractice.record.status,'approved');
  assert.equal(updatedPractice.record.ownerApproved,true);
  const portalAssignment=after.portalAssignments[0];
  if(portalAssignment){const updated=await professionalNetwork.updatePortalAssignment(portalAssignment.id,{status:'approved',ownerApproved:true});assert.equal(updated.record.status,'approved');assert.equal(updated.record.paymentAffectsAssignment,false);}
  const professionalView=professionalNetwork.professionalView({professionalIds:[after.seats[0].professionalId],firmIds:[]});
  assert(professionalView.summary.seats>=1);
  assert.equal(professionalView.gates.liveBilling,false);
  const listen=await new Promise(resolve=>{server.listen(0,'127.0.0.1',()=>resolve(server.address()));});
  const base=`http://127.0.0.1:${listen.port}`;
  try{
    const denied=await request(base,'/api/owner/professional-network');assert.equal(denied.status,403);
    const owner=await request(base,'/api/owner/professional-network',{headers:ownerHeaders()});assert.equal(owner.status,200);assert.equal(owner.data.network.summary.portalContracts,26);
    const exportResult=await request(base,'/api/owner/professional-network/export',{headers:ownerHeaders()});assert.equal(exportResult.status,200);assert.equal(exportResult.data.bundle.portalHandoffs.length,26);
    const portalExport=await request(base,'/api/owner/professional-network/portal-handoffs/immigration-oasis',{headers:ownerHeaders()});assert.equal(portalExport.status,200);assert.equal(portalExport.data.handoff.liveConnection,false);
    const professionalDenied=await request(base,'/api/professional/network');assert.equal(professionalDenied.status,401);
    const page=await request(base,'/professional-network.html',{headers:ownerHeaders()});assert([200,302].includes(page.status));
  } finally {await new Promise(resolve=>server.close(resolve));}
  const html=fs.readFileSync(path.join(root,'public','professional-network.html'),'utf8');
  const js=fs.readFileSync(path.join(root,'public','professional-network.js'),'utf8');
  const dashboard=fs.readFileSync(path.join(root,'public','professional-dashboard.html'),'utf8');
  assert(html.includes('One Smarter Justice professional identity'));
  assert(js.includes('Evidence before placement'));
  assert(js.includes('/api/owner/auth/logout'));
  assert(dashboard.includes('one Smarter Justice account'));
  const releaseEvidence=require('../RELEASE_EVIDENCE_V1.7.35.json');
  assert.equal(releaseEvidence.testing.suiteParts,91);
  assert.equal(releaseEvidence.deployment.rollbackArtifact,'smarter-justice-v1.7.34.zip');
  assert.equal(releaseEvidence.implementation.professionalPortalCoordinationContracts,25);
  const storageRecord=require('../STORAGE_CONSERVATION_V1.7.35.json');
  assert.equal(storageRecord.removedFileCount,0);
  const improvement=require('../CONTINUOUS_IMPROVEMENT_RECORD_V1.7.35.json');
  assert.equal(improvement.theme,'Central professional network and legal-portal coordination');
  const contracts=require('../DASHBOARD_CONTRACTS_V1.7.35.json');
  const professionalContract=contracts.contracts.find(row=>row.contractId==='contract:professional-network:portal-coordination:v1.0.0');
  assert(professionalContract);
  assert(Array.isArray(professionalContract.writeAuthority));
  assert(Array.isArray(professionalContract.forbiddenDataClasses));
  console.log('professional-network-v1735.test.js passed');
})().catch(error=>{console.error(error);try{server.close(()=>{});}catch{}process.exit(1);});
