'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const os=require('os');
const http=require('http');
const root=path.join(__dirname,'..');
process.env.NODE_ENV='test';
process.env.SMARTER_JUSTICE_STORAGE_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'sj-prof-adapter-v1736-'));
process.env.OWNER_CONTROL_CENTER_TOKEN='owner-professional-adapter-test-token-123456789';
const server=require('../server');
const store=require('../lib/store');
const professionalNetwork=require('../lib/professionalNetwork');
const adapterLab=require('../lib/professionalPortalAdapterLab');
const adapter=require('../lib/professionalPortalAdapter');
const aliases=require('../data/professionalPortalAliases');
function ownerHeaders(extra={}){return {'x-owner-control-token':process.env.OWNER_CONTROL_CENTER_TOKEN,...extra};}
function request(base,pathname,options={}){return new Promise((resolve,reject)=>{const url=new URL(pathname,base);const req=http.request(url,{method:options.method||'GET',headers:options.headers||{}},res=>{let body='';res.on('data',chunk=>body+=chunk);res.on('end',()=>{let data;try{data=JSON.parse(body||'{}');}catch{data={raw:body};}resolve({status:res.statusCode,data,headers:res.headers});});});req.on('error',reject);if(options.body)req.write(options.body);req.end();});}
(async()=>{
  await store.init();
  const network=professionalNetwork.ownerView();
  assert.equal(network.standardVersion,'1.4.0');
  assert.equal(network.contractVersion,'1.4.0');
  assert.equal(network.summary.portalContracts,26);
  assert.equal(network.summary.canonicalPortalAssignments,678);
  assert.equal(network.summary.unresolvedPortalAssignments,14);
  assert.equal(network.portalAssignments.length,678);
  assert.equal(network.unresolvedPortalAssignments.length,14);
  assert(network.portalContracts.every(row=>row.contractState==='D3_ADAPTER_TESTS_PASS'));
  assert(network.portalAssignments.every(row=>aliases.CANONICAL_PORTAL_IDS.includes(row.portalId)));
  assert(network.portalAssignments.every(row=>Array.isArray(row.sourcePortalIds)&&row.sourcePortalIds.length>=1));
  assert(network.unresolvedPortalAssignments.every(row=>!row.canonicalPortalId&&row.automaticWrites===false));
  assert.equal(aliases.resolveProfessionalPortalId('accident-injury-help').canonicalPortalId,'personal-injury-law-aid');
  assert.equal(aliases.resolveProfessionalPortalId('name-records-employment').canonicalPortalId,null);
  assert.equal(aliases.resolveProfessionalPortalId('domestic-violence-safety-support').state,'UNRESOLVED_LEGACY_ALIAS');
  const employment=professionalNetwork.portalHandoff('employment-law-aid');
  assert.equal(employment.assignments.length,56);
  assert(employment.assignments.every(row=>row.portalId==='employment-law-aid'));
  assert(employment.assignments.every(row=>row.sourcePortalIds.includes('employment-labor-law-help-center')));
  assert(employment.assignments.every(row=>row.assignmentId&&row.seatId&&row.sourceFreshness));
  const personalInjury=professionalNetwork.portalHandoff('personal-injury-law-aid');
  assert.equal(personalInjury.assignments.length,60);
  assert(personalInjury.assignments.every(row=>!row.sourcePortalIds.includes('domestic-violence-safety-support')));
  const carAccident=professionalNetwork.portalHandoff('car-accident-law-aid');
  assert.equal(carAccident.assignments.length,0,'broad accident eligibility must not be inferred as Car Accident Law Aid eligibility');
  const firstLab=adapterLab.ownerView();
  const secondLab=adapterLab.ownerView();
  assert.equal(firstLab.readiness,'D3_ADAPTER_TESTS_PASS');
  assert.equal(firstLab.summary.portalContracts,26);
  assert.equal(firstLab.summary.d3AdapterTestsPassed,26);
  assert.equal(firstLab.summary.adapterTestsFailed,0);
  assert.equal(firstLab.summary.populatedFixtures,13);
  assert.equal(firstLab.summary.validEmptyFixtures,13);
  assert.equal(firstLab.summary.resolvedCanonicalAssignments,445);
  assert.equal(firstLab.summary.unresolvedLegacyAssignments,14);
  assert.equal(firstLab.summary.prohibitedDataFindings,0);
  assert.equal(firstLab.summary.liveConnections,0);
  assert.equal(firstLab.summary.automaticWrites,0);
  assert(firstLab.fixtures.every(row=>row.validation.valid&&row.consumerPreview.writeAttempted===false&&row.consumerPreview.writeAuthorized===false));
  const firstFingerprints=Object.fromEntries(firstLab.fixtures.map(row=>[row.portalId,row.sourceFingerprint]));
  const secondFingerprints=Object.fromEntries(secondLab.fixtures.map(row=>[row.portalId,row.sourceFingerprint]));
  assert.deepEqual(firstFingerprints,secondFingerprints,'fixture fingerprints should ignore generated timestamps and remain deterministic');
  const invalid=JSON.parse(JSON.stringify(employment));
  invalid.assignments[0].passwordHash='forbidden-test-value';
  const validation=adapter.validateHandoff(invalid,'employment-law-aid');
  assert.equal(validation.valid,false);
  assert(validation.prohibitedKeyPaths.some(value=>/passwordHash/.test(value)));
  const listen=await new Promise(resolve=>server.listen(0,'127.0.0.1',()=>resolve(server.address())));
  const base=`http://127.0.0.1:${listen.port}`;
  try{
    const denied=await request(base,'/api/owner/professional-network/adapter-lab');assert.equal(denied.status,403);
    const owner=await request(base,'/api/owner/professional-network/adapter-lab',{headers:ownerHeaders()});assert.equal(owner.status,200);assert.equal(owner.data.adapterLab.summary.d3AdapterTestsPassed,26);
    const fixture=await request(base,'/api/owner/professional-network/adapter-fixtures/employment-law-aid',{headers:ownerHeaders()});assert.equal(fixture.status,200);assert.equal(fixture.data.fixture.consumerPreview.assignmentCount,56);assert.equal(fixture.data.fixture.consumerPreview.writeAuthorized,false);
    const missing=await request(base,'/api/owner/professional-network/adapter-fixtures/not-a-portal',{headers:ownerHeaders()});assert.equal(missing.status,404);
    const health=await request(base,'/health');assert.equal(health.status,200);assert.equal(health.data.version,'1.7.83');
  } finally {await new Promise(resolve=>server.close(resolve));}
  const html=fs.readFileSync(path.join(root,'public','professional-network.html'),'utf8');
  const js=fs.readFileSync(path.join(root,'public','professional-network.js'),'utf8');
  assert(html.includes('local D3 adapter fixtures'));
  assert(js.includes('Professional Portal Adapter Lab'));
  assert(js.includes('Legacy assignments requiring owner review'));
  assert(js.includes('SMARTER_JUSTICE_PROFESSIONAL_NETWORK_V1.7.41.json'));
  const evidence=require('../RELEASE_EVIDENCE_V1.7.41.json');
  assert.equal(evidence.testing.suiteParts,97);
  assert.equal(evidence.implementation.professionalPortalContractsAtD3,true);
  assert.equal(evidence.implementation.canonicalProfessionalPortalAssignments,678);
  assert.equal(evidence.implementation.unresolvedLegacyProfessionalAssignments,14);
  assert.equal(evidence.deployment.rollbackArtifact,'smarter-justice-v1.7.40.zip');
  console.log('professional-portal-adapter-lab-v1736.test.js passed');
})().catch(error=>{console.error(error);try{server.close(()=>{});}catch{}process.exit(1);});
