const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'public','professionals.html'),'utf8');
const js=fs.readFileSync(path.join(root,'public','professional.js'),'utf8');
const css=fs.readFileSync(path.join(root,'public','styles.css'),'utf8');
assert(html.includes('id="compareProfiles"')&&html.includes('id="profileComparisonResults"'),'directory must provide a public comparison workspace');
assert(html.includes('Download Comparison')&&html.includes('Clear Shortlist'),'comparison must provide local download and clearing controls');
assert(/up to three profiles/.test(js)||/length>=3/.test(js),'comparison must cap the shortlist at three');
assert(/parseCompareTokens/.test(js)&&/professional\|firm/.test(js),'comparison tokens must be restricted to professional and firm records');
assert(/directoryCompareTokens\.join\(','\)/.test(js),'shortlist must be represented in the page URL');
assert(/profile-comparison-table/.test(js)&&/Side-by-side public profile facts/.test(js),'comparison must render documented facts side by side');
for(const field of ['Business location','Documented practices or services','Jurisdictions','Documented languages','Documented service methods','Profile label','Public-source review','Smarter Justice inquiries'])assert(js.includes(field),`comparison missing ${field}`);
assert(/not a ranking, recommendation, credential check/i.test(html),'comparison must state its neutral limits');
assert(/safeDirectoryReturn/.test(js)&&/validatedDirectoryReturn/.test(js)&&/data-directory-profile-link/.test(js),'profile navigation must preserve a validated directory return path');
assert(/new Blob/.test(js)&&/smarter-justice-profile-comparison\.txt/.test(js),'comparison download must be local and plain text');
assert(!/localStorage|indexedDB|sendBeacon|XMLHttpRequest/.test(js.slice(0,js.indexOf('async function loadDirectory')+1)),'comparison helpers must not add hidden persistence or alternate network channels');
assert(css.includes('.profile-comparison-table-wrap')&&css.includes('@media print'),'comparison must have responsive overflow and print treatment');
console.log('v1.7.15 device-only neutral profile comparison, URL shortlist, local export, and search-return tests passed.');
