const assert=require('assert');
const fs=require('fs');
const os=require('os');
const path=require('path');
process.env.NODE_ENV='test';
process.env.APP_BASE_URL='http://localhost:3000';
process.env.SMARTER_JUSTICE_STORAGE_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'sj-professional-verify-'));
process.env.SMTP_HOST='';process.env.SMTP_USER='';process.env.SMTP_PASS='';process.env.SMTP_FROM='';
const store=require('../lib/store');
const accounts=require('../lib/professionalAccounts');
const marketplace=require('../lib/professionalMarketplace');
(async()=>{
  await store.init();
  const created=await accounts.createAccount({accountType:'individual',displayName:'Verification Test',email:'verify@example.test',password:'Professional!123',professionalType:'attorney',acceptTerms:true,acceptPrivacy:true,startMembership:true,billingCadence:'annual'});
  assert(!created.error,created.error);
  assert.equal(created.account.status,'pending-email-verification');
  assert.equal(created.account.emailVerified,false);
  assert(created.verification.testToken);
  assert(!marketplace.getOwnerData().professionals.some(item=>item.email==='verify@example.test'),'unverified signup must not create a marketplace record');
  let login=accounts.login({email:'verify@example.test',password:'Professional!123'});
  assert.equal(login.emailVerificationRequired,true);
  const verified=await accounts.verifyEmail(created.verification.testToken);
  assert(!verified.error,verified.error);
  assert.equal(verified.account.status,'active');
  assert.equal(verified.account.emailVerified,true);
  assert(marketplace.getOwnerData().professionals.some(item=>item.email==='verify@example.test'),'verification should create the deferred marketplace record');
  assert(verified.session.cookie.includes('sj_professional_session='));
  const replay=await accounts.verifyEmail(created.verification.testToken);
  assert(replay.error);
  login=accounts.login({email:'verify@example.test',password:'Professional!123'});
  assert(login.session);
  const state=store.readJson('professionalAccounts.json',{});
  const persisted=JSON.stringify(state);
  assert(!persisted.includes(created.verification.testToken),'raw verification token must not be stored');
  assert(state.emailVerificationRequests.every(item=>item.tokenHash&&item.tokenHash!==created.verification.testToken));
  assert.equal(typeof store.flush,'function','transactional writes must expose an awaited flush barrier');
  console.log('professional-email-verification.test.js passed');
})().catch(error=>{console.error(error);process.exit(1);}).finally(()=>fs.rmSync(process.env.SMARTER_JUSTICE_STORAGE_DIR,{recursive:true,force:true}));
