const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const home=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
const js=fs.readFileSync(path.join(root,'public','home.js'),'utf8');
const env=fs.readFileSync(path.join(root,'.env.example'),'utf8');
const field=require('../data/nycFieldLaunchSeed');
const story=fs.readFileSync(path.join(root,'public','our-story.html'),'utf8');
assert(home.includes('stopDomesticViolenceInitiative'));
assert(home.includes('About the Stop Sign Project'));
assert(!home.includes('href="https://stopsignproject.org/"'),'unverified destination must not be linked in static public HTML');
assert(home.includes('800-799-SAFE (7233)'));
assert(home.includes('text <strong>START</strong> to 88788'));
assert(story.includes('/images/stop-sign-project-manufactured-sign.jpg'));
assert(story.includes('StopSignProject.org'));
assert(js.includes('loadPublicServiceInitiatives'));
assert(js.includes('initiative?.configured'));
assert(js.includes("link.textContent='Visit StopSignProject.org'"));
assert(env.includes('STOP_DOMESTIC_VIOLENCE_URL='));
assert(env.includes('STOP_SIGN_PROJECT_DESTINATION_VERIFIED=false'));
assert(!env.includes('STOP_DOMESTIC_VIOLENCE_URL=https://stopsignproject.org/'),'unverified destination must not be enabled by the example environment');
assert(env.includes('STOP_DOMESTIC_VIOLENCE_ARTWORK_PATH=/images/stop-sign-project.png'));
assert(fs.existsSync(path.join(root,'public','images','stop-sign-project.png')));
assert(fs.existsSync(path.join(root,'public','images','stop-sign-project-manufactured-sign.jpg')));
const asset=field.NYC_FIELD_LAUNCH_ASSETS.find(x=>x.id==='FIELD-ASSET-STOP-DV-SIDE-001');
assert(asset);
assert.strictEqual(asset.status,'design pending');
assert(/website URL and two owner-supplied artwork files recorded/i.test(asset.complianceStatus));
assert(/destination availability/i.test(asset.complianceStatus));
console.log('public-service-initiatives.test.js passed');
