const assert=require('assert');
const fs=require('fs');
const os=require('os');
const path=require('path');
process.env.NODE_ENV='test';
process.env.SMARTER_JUSTICE_STORAGE_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'sj-public-paid-services-'));
const store=require('../lib/store');
const revenue=require('../lib/revenueAccessModel');
const services=require('../lib/publicPaidServices');
const standard=fs.readFileSync(path.join(__dirname,'..','PUBLIC_PAID_HUMAN_REVIEW_STANDARD.md'),'utf8');
assert(standard.includes('Fail-closed activation gate'));
assert(standard.includes('Paying for Human Review Specialist work does not create'));
(async()=>{
  await store.init();
  store.writeJson('revenueAccessModel.json',null);
  store.writeJson('publicPaidServices.json',null);
  const initially=services.availability('starter_review',{});
  assert.strictEqual(initially.available,false);
  assert(initially.reasons.some(x=>/not pilot-ready/i.test(x)));
  const configuredService=await revenue.updateHumanReviewService('starting-file-completeness-review',{status:'pilot-ready',activeForBilling:true,priceCents:4900,turnaround:'Two business days after assignment.',revisionPolicy:'One missing-information follow-up is included.'});
  assert(configuredService.service.activeForBilling);
  await services.updateControls({status:'pilot-ready',ownerApproved:true,liveChargesAllowed:true,refundPolicyStatus:'approved',supportOperationsStatus:'approved',termsVersion:'public-paid-services-1.0.0'});
  const env={publicPaidServicesEnabled:true,sensitiveTrafficApproved:true,stripeConfigured:true,webhookConfigured:true,smtpConfigured:true,ownerEmailConfigured:true,priceConfigured:true};
  const ready=services.availability('starter_review',env);
  assert.strictEqual(ready.available,true);
  const missing=await services.createOrder({caseId:'case-internal-1',publicToken:'public-token-1',email:'user@example.com',serviceType:'starter_review',acknowledgments:{}},env);
  assert(missing.error && missing.missingAcknowledgments.length===5);
  const acknowledgments=Object.fromEntries(services.REQUIRED_ACKNOWLEDGMENTS.map(key=>[key,true]));
  const created=await services.createOrder({caseId:'case-internal-1',publicToken:'public-token-1',email:'user@example.com',serviceType:'starter_review',acknowledgments},env);
  assert(created.order && !created.duplicate);
  assert.strictEqual(created.order.publicToken,undefined);
  assert.strictEqual(created.order.priceCents,4900);
  const duplicate=await services.createOrder({caseId:'case-internal-1',publicToken:'public-token-1',email:'user@example.com',serviceType:'starter_review',acknowledgments},env);
  assert.strictEqual(duplicate.duplicate,true);
  const checkout=await services.markCheckoutCreated(created.order.id,{id:'cs_test_public_1'});
  assert.strictEqual(checkout.order.status,'checkout created');
  const paid=await services.applyCheckoutSession({id:'cs_test_public_1',status:'complete',payment_status:'paid',payment_intent:'pi_test_1',metadata:{orderId:created.order.id}},'checkout.session.completed');
  assert.strictEqual(paid.paid,true);
  assert.strictEqual(paid.order.status,'paid — queued');
  const assigned=await services.updateOrder(created.order.id,{status:'assigned',assignedTo:'Human Review Specialist 1',dueAt:'2026-08-01',userFacingStatus:'Assigned for review',historyNote:'Test assignment.'});
  assert.strictEqual(assigned.order.status,'assigned');
  const publicRows=services.publicOrdersForCase('case-internal-1');
  assert.strictEqual(publicRows.length,1);
  assert.strictEqual(publicRows[0].assignedTo,undefined);
  const refunded=await services.updateOrder(created.order.id,{status:'refunded',refundReference:'re_test_1',userFacingStatus:'Refund completed',historyNote:'Test refund.'});
  assert.strictEqual(refunded.order.paymentStatus,'refunded');
  const owner=services.ownerView();
  assert.strictEqual(owner.summary.refunded,1);
  assert(services.exportMarkdown().includes('Public Paid-Service Operations'));
  console.log('public-paid-services.test.js passed');
})().catch(err=>{console.error(err);process.exit(1);});
