const assert=require('assert');
const fs=require('fs');
const path=require('path');
const pkg=require('../package.json');
assert.equal(pkg.version,'1.7.83');
assert.equal(pkg.scripts.test.split(' && ').length,145);
assert.equal(require('../server-version-helper').version,'1.7.83');
for(const f of ['AUDIT_REPORT_V1.7.27.md','CHANGE_MAP_V1.7.27.md','NO_CHANGE_LEDGER_V1.7.27.md','CONTINUATION_PROMPT_V1.7.27.md','RELEASE_EVIDENCE_V1.7.27.json','PREDEPLOYMENT_AUDIT_V1.7.27.md','PREDEPLOYMENT_AUDIT_V1.7.27.json','PROFILE_GROWTH_REPORT_V1.7.27.json']) assert(fs.existsSync(path.join(__dirname,'..',f)),f);
const evidence=require('../RELEASE_EVIDENCE_V1.7.27.json');
assert.equal(evidence.deployed,false);
assert.equal(evidence.activationGatesChanged,false);
assert.equal(evidence.predeploymentAudit.serverEnforcedSensitivePublicFormGating,true);
assert.equal(evidence.predeploymentAudit.truthfulSensitivePublicFormAvailability,true);
assert.equal(evidence.predeploymentAudit.directorySourceFreshnessFilter,true);
assert.equal(evidence.security.sensitiveTrafficApproved,false);
assert.equal(evidence.security.sensitivePublicFormStorageWhenClosed,false);
assert.equal(evidence.profileGrowth.publicDirectory.total,159);
assert.equal(evidence.profileGrowth.strictQualifying.total,156);
assert.equal(evidence.revenue.professionalPricesChanged,false);
assert.equal(evidence.revenue.monthlyProfessionalPrice,15);
assert.equal(evidence.revenue.annualProfessionalPrice,150);
assert.equal(evidence.revenue.paidOrganicRanking,false);
const manifest=require('../portal-manifest.json');
assert.equal(manifest.currentDevelopmentVersion,'1.7.83');
assert.equal(manifest.testSuiteParts,146);
assert.equal(manifest.releaseEvidence,'RELEASE_EVIDENCE_V1.7.83.json');
assert.equal(manifest.profileGrowthReport,'PROFILE_GROWTH_REPORT_V1.7.50.json');
assert.equal(manifest.predeploymentAudit,'PREDEPLOYMENT_AUDIT_V1.7.27.json');
assert.equal(manifest.capabilities.completePredeploymentAuditV1727,true);
assert.equal(manifest.capabilities.serverEnforcedSensitivePublicFormGatingV1727,true);
assert.equal(manifest.capabilities.truthfulSensitivePublicFormAvailabilityV1727,true);
assert.equal(manifest.capabilities.directorySourceFreshnessFilterV1727,true);
assert.equal(manifest.capabilities.manhattanLedProfessionalProfileGrowthV1727,true);
assert.equal(manifest.capabilities.sensitivePublicFormCollectionWhenClosed,false);
assert.equal(manifest.capabilities.paidOrganicRanking,false);
const next=require('../NEXT_VERSION_IMPROVEMENT_LIST.json');
assert.equal(next.releaseVersion,'1.7.83');
assert(next.baselineArtifact.includes('v1.7.82.zip'));
assert(Array.isArray(next.currentReleasePriorities)&&next.currentReleasePriorities.length===8);
const profileSeeds=require('../data/threeMarketProfileSeedsV1727');
assert.equal(profileSeeds.THREE_MARKET_PROFESSIONAL_SEEDS_V1727.length,12);
const mark=profileSeeds.THREE_MARKET_PROFESSIONAL_SEEDS_V1727.find(x=>x.id==='professional-mark-a-tabakin');
const jessica=profileSeeds.THREE_MARKET_PROFESSIONAL_SEEDS_V1727.find(x=>x.id==='professional-jessica-cunha');
assert.equal(mark.phone,'201-896-7703');assert.equal(jessica.phone,'201-896-7244');
assert(mark.officeLocations[0].includes('150 Clove Road'));
const scarinci=profileSeeds.THREE_MARKET_FIRM_SEEDS_V1727.find(x=>x.id==='firm-scarinci-hollenbeck');
assert(scarinci.sourceRecords.some(x=>x.sourceUrl.includes('/location/little-falls')));
const sbom=require('../SBOM.spdx.json');
assert(sbom.name.includes('1.7.83'));
assert(sbom.documentNamespace.includes('/1.7.83/'));
assert.equal(sbom.packages.length,15);
const nextMd=fs.readFileSync(path.join(__dirname,'..','NEXT_VERSION_IMPROVEMENT_LIST.md'),'utf8');
assert(nextMd.includes('v1.7.77'));
assert(!nextMd.includes('after v1.7.25'));
console.log('release-governance-v1727.test.js passed');
