'use strict';
const assert=require('assert');const fs=require('fs');const path=require('path');const root=path.join(__dirname,'..');const pkg=require('../package.json');
assert.equal(pkg.version,'1.7.83');assert.equal(pkg.scripts.test.split(' && ').length,145);assert.equal(require('../server-version-helper').version,'1.7.83');
for(const f of ['AUDIT_REPORT_V1.7.32.md','CHANGE_MAP_V1.7.32.md','NO_CHANGE_LEDGER_V1.7.32.md','CONTINUATION_PROMPT_V1.7.32.md','RELEASE_EVIDENCE_V1.7.32.json','PROFILE_GROWTH_REPORT_V1.7.32.json','CURRENT_ENVIRONMENT_REVIEW_V1.7.32.json','CONTINUOUS_IMPROVEMENT_RECORD_V1.7.32.json','CURRENT_WATCHLIST_V1.7.32.json','PORTAL_RELEASE_SNAPSHOT_V1.7.32.json','PORTFOLIO_TRUTH_V1.7.32.json','DASHBOARD_CONTRACTS_V1.7.32.json','DASHBOARD_CONFORMANCE_V1.7.32.json','STORAGE_CONSERVATION_V1.7.32.json'])assert(fs.existsSync(path.join(root,f)),f);
const evidence=require('../RELEASE_EVIDENCE_V1.7.32.json');assert.equal(evidence.version,'1.7.32');assert.equal(evidence.deployment.deployed,false);assert.equal(evidence.activationGatesChanged,false);assert.equal(evidence.implementation.preparationQualityCheck,true);assert.equal(evidence.implementation.preparationQualityDeterminesTruth,false);assert.equal(evidence.implementation.preparationQualityCalculatesLegalDeadlines,false);assert.equal(evidence.implementation.portfolioTruthRegistry,true);assert.equal(evidence.implementation.dashboardConformanceHighestClaim,'D2_CONTRACT_TESTED');assert.equal(evidence.implementation.liveCrossPortalDashboardIntegration,false);assert.equal(evidence.profileGrowth.newProfessionals,0);assert.equal(evidence.profileGrowth.newFirms,0);assert.equal(evidence.profileGrowth.newLinks,0);assert.equal(evidence.profileGrowth.publicDirectory.total,281);assert.equal(evidence.profileGrowth.strictQualifying.total,278);assert.equal(evidence.testing.suiteParts,82);
const manifest=require('../portal-manifest.json');assert.equal(manifest.currentDevelopmentVersion,'1.7.83');assert.equal(manifest.lastExactArtifactTestVersion,'1.7.82');assert.equal(manifest.testSuiteParts,146);assert.equal(manifest.releaseEvidence,'RELEASE_EVIDENCE_V1.7.83.json');for(const k of ['preparationQualityCheckV1732','portfolioTruthRegistryV1732','stablePortfolioIdentifiersV1732','evidenceStateSeparationV1732','attentionFirstOwnerControlCenterV1732','dashboardContractsV1732','dashboardConformanceD2V1732','storageConservationV1732','noWeakProfilePaddingV1732'])assert.equal(manifest.capabilities[k],true,k);for(const k of ['preparationQualityTruthDeterminationV1732','preparationQualityDeadlineCalculationV1732','preparationQualityServerTransmissionV1732','preparationQualityExternalAiV1732','preparationQualityProfessionalRoutingV1732','dashboardLiveIntegrationV1732','centralizedPublicUserMatterDataV1732','automaticCrossPortalDashboardWritesV1732','profileGrowthBatchV1732'])assert.equal(manifest.capabilities[k],false,k);
const sbom=require('../SBOM.spdx.json');assert(sbom.name.includes('1.7.83'));assert(sbom.documentNamespace.includes('/1.7.83/'));assert.equal(sbom.packages.length,15);const next=require('../NEXT_VERSION_IMPROVEMENT_LIST.json');assert.equal(next.releaseVersion,'1.7.83');assert(next.baselineArtifact.includes('v1.7.82.zip'));assert.equal(next.leadRegion,'The Bronx');assert.equal(next.currentReleasePriorities.length,8);
const readme=fs.readFileSync(path.join(root,'README.md'),'utf8');const notes=fs.readFileSync(path.join(root,'RELEASE_NOTES.md'),'utf8');assert(readme.startsWith('# Smarter Justice v1.7.83'));assert(readme.includes('0 new professionals'));assert(notes.includes('v1.7.32 — Preparation Quality, Portfolio Truth'));
console.log('release-governance-v1732.test.js passed');
