'use strict';
const assert=require('assert');
const fs=require('fs');
const os=require('os');
const path=require('path');
process.env.NODE_ENV='test';
process.env.SMARTER_JUSTICE_STORAGE_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'sj-v1742-'));
(async()=>{
  const store=require('../lib/store'); await store.init();
  const operating=require('../lib/legalPortfolioOperatingSystem');
  const adapter=require('../lib/professionalPortalAdapter');
  const network=require('../lib/professionalNetwork');
  const aliases=require('../data/professionalPortalAliases');
  const pkg=require('../package.json');
  const manifest=require('../portal-manifest.json');
  const rollout=require('../MICRO_PORTAL_INTEGRATION_ROLLOUT_V1.7.66.json');
  const truth=require('../PORTFOLIO_TRUTH_V1.7.66.json');
  const view=operating.ownerView();
  assert.equal(pkg.version,'1.7.83');
  assert.equal(pkg.scripts.test.split(' && ').length,145);
  assert(!pkg.scripts.test.includes('storage-readiness.test.js')); // PostgreSQL-dependent test is separate
  assert.equal(manifest.currentDevelopmentVersion,'1.7.83');
  assert.equal(manifest.testSuiteParts,146);
  assert.equal(manifest.dependencyIndependentTestParts,145);
  assert.equal(view.authority.finalOwner,'Roger');
  assert.equal(view.authority.neutralBoardroom.launchCritical,false);
  assert.equal(view.authority.neutralBoardroom.runtimeDependency,false);
  assert.equal(view.authority.neutralBoardroom.managementDependency,false);
  assert.equal(view.authority.neutralBoardroom.sourceOfTruth,false);
  assert.deepEqual(view.summary.pilotOrder,['divorce-law-aid','estate-law-aid','personal-injury-law-aid','domestic-violence-aid']);
  assert.equal(view.summary.openGates,0);
  assert.equal(view.summary.launchState,'NO_GO');
  const pi=view.pilots.find(x=>x.portalId==='personal-injury-law-aid');
  assert(pi.simpleLaunchScope.includes('Vehicle accidents'));
  assert(/separate portal/i.test(pi.workersCompensationBoundary));
  assert(pi.compatibilityAssets.some(x=>x.portalId==='car-accident-law-aid'&&x.state==='PRESERVED_NOT_SEPARATELY_LAUNCHED'));
  assert.equal(aliases.PILOT_COMPATIBILITY_POLICY.personalInjuryIncludesVehicleAccidents,true);
  assert.equal(aliases.PILOT_COMPATIBILITY_POLICY.workersCompensationSeparate,true);
  assert.equal(aliases.PILOT_COMPATIBILITY_POLICY.automaticRecordReassignment,false);
  assert.deepEqual(rollout.pilotOrder,['divorce-law-aid','estate-law-aid','personal-injury-law-aid','domestic-violence-aid']);
  assert.deepEqual(rollout.portalInstructions.filter(x=>['divorce-law-aid','estate-law-aid','personal-injury-law-aid','domestic-violence-aid'].includes(x.portalId)).map(x=>x.portalId),['divorce-law-aid','estate-law-aid','personal-injury-law-aid','domestic-violence-aid']);
  assert(truth.ownerDecisions.some(x=>/Personal Injury includes vehicle accidents/i.test(x.decision)));
  assert(!truth.ownerDecisions.some(x=>/Neutral Boardroom is the separate top-level/i.test(x.decision)));
  for(const id of ['divorce-law-aid','estate-law-aid','personal-injury-law-aid']){
    const handoff=network.portalHandoff(id); assert(handoff,id);
    const validation=adapter.validateHandoff(handoff,id); assert.equal(validation.valid,true,validation.errors.join('; '));
    assert.equal(handoff.automaticWrites,false); assert.equal(handoff.liveConnection,false);
    assert.equal(handoff.containsUserMatterData,false); assert.equal(handoff.containsPaymentData,false);
    assert(fs.existsSync(path.join(__dirname,'..','examples',`${id}-professional-handoff-v1.4.0.json`)));
    assert(fs.existsSync(path.join(__dirname,'..','examples',`${id}-import-receipt-v1.4.0.json`)));
  }
  const dvHandoff=network.portalHandoff('domestic-violence-aid');
  assert(dvHandoff); assert.equal(adapter.validateHandoff(dvHandoff,'domestic-violence-aid').valid,true);
  assert.equal(dvHandoff.liveConnection,false); assert.equal(dvHandoff.automaticWrites,false); assert.equal(dvHandoff.assignments.length,0);
  const decision=await operating.recordDecision({decision:'Keep all v1.7.53 commercial and live portal gates closed during external acceptance.',scope:'v1.7.53 tests',status:'ACTIVE'},'test-owner');
  assert(decision.decision);
  const blocked=await operating.updateGate('checkout',{state:'OPEN',reason:'test opening attempt',evidence:['test']},'test-owner');
  assert(blocked.error); assert(/disabled/i.test(blocked.error));
  const pending=await operating.updateGate('checkout',{state:'READY_FOR_OWNER_DECISION',reason:'Await production Stripe lifecycle evidence.',evidence:['No production evidence yet.']},'test-owner');
  assert.equal(pending.gate.state,'READY_FOR_OWNER_DECISION');
  const receipt=await operating.recordIntegrationReceipt({portalId:'personal-injury-law-aid',batchId:'local-test-batch',result:'LOCAL_VALIDATION_PASS_NOT_IMPORTED',lastKnownGood:true,rollbackAvailable:true},'test-owner');
  assert.equal(receipt.receipt.liveConnection,false); assert.equal(receipt.receipt.automaticWrites,false);
  const server=fs.readFileSync(path.join(__dirname,'..','server.js'),'utf8');
  const html=fs.readFileSync(path.join(__dirname,'..','public','control-center.html'),'utf8');
  const app=fs.readFileSync(path.join(__dirname,'..','public','app.js'),'utf8');
  assert(server.includes('/api/owner/legal-portfolio-operating-system'));
  assert(html.includes('Legal Portfolio Operating System'));
  assert(html.includes('Smarter Justice is the self-contained legal-portfolio operating system'));
  assert(!html.includes('Neutral Boardroom owns top-level'));
  assert(app.includes('renderLegalPortfolioOperatingSystem'));
  for(const f of ['OWNER_DECISION_REGISTER_V1.7.50.json','ARTIFACT_REGISTRY_V1.7.50.json','LAUNCH_GATE_REGISTER_V1.7.50.json','SELF_CONTAINED_LAUNCH_DEPENDENCY_REGISTER_V1.7.50.json','PILOT_LINK_SPECIFICATION_V1.7.50.json','PERSONAL_INJURY_PILOT_SCOPE_V1.7.50.md','DIVORCE_LAW_AID_INTEGRATION_BUILD_PROMPT_V1.7.50.txt','ESTATE_LAW_AID_INTEGRATION_BUILD_PROMPT_V1.7.50.txt','PERSONAL_INJURY_LAW_AID_INTEGRATION_BUILD_PROMPT_V1.7.50.txt']) assert(fs.existsSync(path.join(__dirname,'..',f)),f);
  console.log('self-contained-pilot-expansion-v1742.test.js passed');
})().catch(err=>{console.error(err);process.exit(1)});
