'use strict';
const { portForTest } = require('./test-port');
const assert=require('assert');const {spawn}=require('child_process');const fs=require('fs');const os=require('os');const path=require('path');
const root=path.join(__dirname,'..');const storage=fs.mkdtempSync(path.join(os.tmpdir(),'sj-sensitive-v1727-'));const port=portForTest(3997);let log='';const wait=ms=>new Promise(r=>setTimeout(r,ms));
const child=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,NODE_ENV:'test',PORT:String(port),APP_BASE_URL:`http://127.0.0.1:${port}`,SMARTER_JUSTICE_STORAGE_DIR:storage,ENFORCE_SENSITIVE_TRAFFIC_GATE:'true',SENSITIVE_TRAFFIC_APPROVED:'false',OWNER_NOTIFICATION_EMAIL:'',SMTP_HOST:''}});child.stdout.on('data',d=>log+=d);child.stderr.on('data',d=>log+=d);
async function body(response){const text=await response.text();try{return JSON.parse(text)}catch{return{text}}}
(async()=>{try{for(let i=0;i<80&&!log.includes('listening');i++){if(child.exitCode!==null)throw new Error(log);await wait(100);}const base=`http://127.0.0.1:${port}`;const config=await body(await fetch(base+'/api/public-config'));for(const key of ['contactRequestsAvailable','profileCorrectionRequestsAvailable','communityPartnerRegistrationAvailable','professionalMembershipInterestAvailable'])assert.equal(config[key],false,key);assert(/temporarily unavailable/i.test(config.sensitivePublicFormMessage));
for(const [endpoint,payload] of [['/api/contact',{name:'Test',email:'test@example.test',message:'Help'}],['/api/help',{name:'Test',message:'Help'}],['/api/public/profile-requests',{profileId:'professional-test',requestType:'correction',requesterName:'Test',requesterEmail:'test@example.test',details:'Correction'}],['/api/community-partners/register',{name:'Test Partner',email:'partner@example.test'}],['/api/professional-membership-interest',{campaignCode:'TEST',contactName:'Test',email:'test@example.test',consentToContact:true}]]){const response=await fetch(base+endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await body(response);assert.equal(response.status,503,endpoint);assert.equal(data.ok,false);assert(/No information was saved/i.test(data.error));assert.equal(data.safeAlternative,'/free-tools.html');}
const serverSource=fs.readFileSync(path.join(root,'server.js'),'utf8');for(const endpoint of ['/api/contact','/api/help','/api/public/profile-requests','/api/community-partners/register','/api/professional-membership-interest'])assert(serverSource.includes(endpoint));
const app=fs.readFileSync(path.join(root,'public/app.js'),'utf8');assert(app.includes('initSensitivePublicForms'));assert(app.includes("control.disabled=true"));const contact=fs.readFileSync(path.join(root,'public/contact.html'),'utf8');const referral=fs.readFileSync(path.join(root,'public/referral-program.html'),'utf8');assert(contact.includes('data-sensitive-public-form="contactRequestsAvailable"'));assert(referral.includes('data-sensitive-public-form="communityPartnerRegistrationAvailable"'));assert(contact.includes('Checking protected request availability'));assert(referral.includes('Checking registration availability'));console.log('sensitive-public-forms-v1727.test.js passed');}catch(e){console.error(e);process.exitCode=1;}finally{child.kill('SIGTERM');fs.rmSync(storage,{recursive:true,force:true});}})();
