'use strict';
const assert=require('assert');const fs=require('fs');const os=require('os');const path=require('path');
process.env.NODE_ENV='test';process.env.SMARTER_JUSTICE_STORAGE_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'sj-profile-v1730-'));
const seeds=require('../data/sixRegionProfileSeedsV1730');const marketplace=require('../lib/professionalMarketplace');
assert.equal(seeds.SIX_REGION_PROFILE_BATCH_V1730.version,'1.7.30');assert.equal(seeds.SIX_REGION_PROFESSIONAL_SEEDS_V1730.length,36);assert.equal(seeds.SIX_REGION_FIRM_SEEDS_V1730.length,7);assert.equal(new Set(seeds.SIX_REGION_PROFESSIONAL_SEEDS_V1730.map(x=>x.id)).size,36);assert.equal(new Set(seeds.SIX_REGION_FIRM_SEEDS_V1730.map(x=>x.id)).size,7);
for(const [county,count] of Object.entries({'New York County':6,'Kings County':6,'Queens County':6,'Bronx County':6,'Passaic County':6,'Fairfield County':6}))assert.equal(seeds.SIX_REGION_PROFESSIONAL_SEEDS_V1730.filter(x=>x.publicFacts.county===county).length,count,county);
for(const row of seeds.SIX_REGION_PROFESSIONAL_SEEDS_V1730){assert.equal(row.claimStatus,'not claimed');assert.equal(row.verificationStatus,'not started');assert.equal(row.availabilityStatus,'not configured');assert(row.sourceRecords.length>=1);assert(row.sourceRecords.every(x=>x.authorityLevel==='self-reported'&&x.lastVerifiedAt.startsWith('2026-07-24')));assert(row.officeLocations.length&&row.practiceAreas.length&&row.portalEligibility.length);const live=marketplace.getPublicProfessional(row.id);assert(live,row.id);assert.equal(live.claimed,false);assert.equal(live.participating,false);}
for(const firm of seeds.SIX_REGION_FIRM_SEEDS_V1730){const live=marketplace.getPublicFirm(firm.id);assert(live,firm.id);assert.equal(live.claimed,false);assert.equal(live.participating,false);assert(live.professionalCount>=1,firm.id);}
const metrics=marketplace.directoryMetrics();assert.deepEqual({professionals:metrics.publicProfessionals,firms:metrics.publicFirms,total:metrics.publicTotal,qualifyingProfessionals:metrics.qualifyingProfessionals,qualifyingFirms:metrics.qualifyingFirms,qualifyingTotal:metrics.qualifyingTotal},{professionals:233,firms:48,total:281,qualifyingProfessionals:232,qualifyingFirms:46,qualifyingTotal:278});
assert.equal(marketplace.publicFeatureStatus().sixRegionProfileBatch.actual.individualProfessionals,36);assert.equal(marketplace.publicFeatureStatus().sixRegionProfileBatch.actual.firms,6);assert.equal(marketplace.publicFeatureStatus().sixRegionProfileBatch.nextLeadRegion,'The Bronx');
console.log('six-region-profile-growth-v1730.test.js passed');
