const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { PRACTICE_AREAS } = require('../data/practiceAreas');
const { PORTALS } = require('../data/portals');
const pub = path.join(__dirname, '..', 'public');
const focusedPracticePages = ['taxes.html','business-formation-compliance.html','business-law.html','real-estate.html','divorce-family-law.html','landlord-tenant-housing.html','bankruptcy-debt.html','disability-benefits.html','estate-planning.html','vehicle-accidents.html','personal-injury.html','medical-malpractice.html','public-benefits.html','employment-wage-claims.html','nonprofit-formation-compliance.html'];
assert(fs.existsSync(path.join(__dirname, '..', 'render.yaml')), 'missing render.yaml');
assert(fs.existsSync(path.join(__dirname, '..', 'DEPLOY_RENDER.md')), 'missing DEPLOY_RENDER.md');

const renderYaml = fs.readFileSync(path.join(__dirname,'..','render.yaml'),'utf8');
assert(/name:\s*smarter-justice-app\b/.test(renderYaml), 'render.yaml should reference the existing live service');
assert(/runtime:\s*node\b/.test(renderYaml), 'render.yaml should use the current Render runtime field');
assert(!/^\s*plan:\s*free\s*$/m.test(renderYaml), 'render.yaml must not force the existing service back to free');
assert(/autoDeployTrigger:\s*off/.test(renderYaml),'controlled releases must not auto-deploy on commit');
assert(/preDeployCommand:\s*npm run migrate/.test(renderYaml),'Render must run versioned migrations before deployment');
assert(/numInstances:\s*1/.test(renderYaml),'current broad state model must remain single-instance until multi-instance acceptance');
for(const key of ['SENSITIVE_TRAFFIC_APPROVED','PROFESSIONAL_PILOT_ACTIVATION_APPROVED','PUBLIC_PAID_SERVICES_ENABLED','STOP_SIGN_PROJECT_DESTINATION_VERIFIED']) assert(new RegExp(`key: ${key}\\n\\s+value: \"false\"`).test(renderYaml),`${key} must be explicitly closed in Render configuration`);
for (const f of ['SMARTER_JUSTICE_SHARED_PLATFORM_STANDARD.md','SMARTER_JUSTICE_MASTER_COORDINATION_STANDARD.md','PORTAL_CONTINUATION_PROMPT_STANDARD.md','CONTROL_CENTER_ROADMAP.md','SMARTER_JUSTICE_MASTER_RULES_AND_SUGGESTIONS_PACK.md','SMARTER_JUSTICE_MASTER_RULES_AND_SUGGESTIONS_PACK.json','PROFESSIONAL_MARKETPLACE_STANDARD.md','PUBLIC_PROFILE_SOURCE_STANDARD.md','MARKETPLACE_REVENUE_ROADMAP.md','portal-manifest.json','portal-manifest.schema.json']) assert(fs.existsSync(path.join(__dirname,'..',f)), `missing ${f}`);
const required = [...focusedPracticePages, 'portals.html','portal-router.html','form-drafts.html','index.html','how-it-works.html','practice-areas.html','upload-notice.html','document-tools.html','portal-preparation.html','pricing.html','referral-program.html','community-partner-tools.html','attorney-review.html','contact.html','faq.html','privacy.html','terms.html','disclaimer.html','security.html','dashboard.html','staff.html','forms-roadmap.html','production-readiness.html','launch-readiness.html','review-delivery.html','checkout-success.html','checkout-cancel.html','next-path.html','ai-summary.html','llms.txt','robots.txt','sitemap.xml','logo.svg','favicon.svg','app.js','home.js','notice-route.js','live-chat.js','styles.css','control-center.html','owner-login.html','internal-access.html','professional-membership.html','professional-membership-terms.html','professionals.html','professional-profile.html','professional-signup.html','professional-login.html','professional-dashboard.html','professional.js','attorney-launch.html','attorney-partner-tour.html','attorney-partner-tour.js'];
for (const f of required) assert(fs.existsSync(path.join(pub,f)), `missing ${f}`);
for (const f of required.filter(f => f.endsWith('.html') && !['control-center.html'].includes(f))) {
  const html = fs.readFileSync(path.join(pub,f),'utf8');
  assert(/<title>/.test(html), `${f} missing title`);
  assert(/Smarter Justice/.test(html), `${f} missing Smarter Justice branding`);
  assert(/not a law firm|Not a law firm|private support service/i.test(html), `${f} missing trust/disclaimer language`);
  assert(!/external lead integration/i.test(html), `${f} should not expose unavailable lead-integration roadmap`);
  const professionalFacing=/^professionals?[-.]|^attorney-(?:launch|partner-tour)/.test(f);
  if(!professionalFacing) assert(!/\bintake\b|risk flags|handoff|route check|product support|payment\/release|release status/i.test(html), `${f} contains customer-facing internal wording`);
}
const index = fs.readFileSync(path.join(pub,'index.html'),'utf8');
assert(/Start with the problem—not the legal category/.test(index) && /Attorney Partner Tour/.test(index) && /professional-membership\.html/.test(index), 'homepage missing clear public and professional positioning');
assert(/Tell us what happened/.test(index) && /storyRouteForm/.test(index), 'homepage missing non-saved public story routing');
assert(/free basic profile control/i.test(index) && /Paid membership remains separate and paused/i.test(index), 'homepage must state truthful free profile control and closed paid growth');
assert(/program-status\.js/.test(index), 'homepage should use the shared professional program status');
assert(!/type="file"/.test(index), 'homepage must not invite confidential uploads before readiness');
assert(/<strong>Not saved:<\/strong>/.test(index), 'homepage should explain that the public starting-point description is not saved');
assert(/expanded-footer/.test(index), 'homepage missing complete footer');
const portalsPage = fs.readFileSync(path.join(pub,'portals.html'),'utf8');
assert(/portalDirectory/.test(portalsPage) && /focused micro-portals/i.test(portalsPage), 'portals page missing directory panel');
const portalRouter = fs.readFileSync(path.join(pub,'portal-router.html'),'utf8');
assert(/portalDetail/.test(portalRouter), 'portal router page missing detail panel');
const portalsData = fs.readFileSync(path.join(__dirname,'..','data','portals.js'),'utf8');
assert(/Immigration Oasis/.test(portalsData) && /Live — Separate Platform/.test(portalsData), 'portal data missing separate Immigration Oasis card');
assert(PORTALS.length >= 10, 'expected broad focused portal coverage');
const practiceHtml = fs.readFileSync(path.join(pub,'practice-areas.html'),'utf8');
assert.equal((practiceHtml.match(/class="practice-card"/g) || []).length, PRACTICE_AREAS.length, 'practice page must include every practice area');
for (const p of PRACTICE_AREAS) assert(practiceHtml.includes(`id="${p.slug}"`), `practice page missing ${p.slug}`);
assert(!practiceHtml.includes('#start#start'), 'practice page contains duplicated start anchors');
const appJs = fs.readFileSync(path.join(pub,'app.js'),'utf8');
assert(/practices\.map\(p => `<option/.test(appJs), 'home practice select should be populated from the full practice-area API');
assert(/initPortalDirectory/.test(appJs), 'app should render portal directory');
assert(/Recommended focused website/.test(appJs), 'dashboard should show the recommended focused website');
assert(/portalBox/.test(appJs), 'case display missing portal box');
assert(!/\?token=/.test(appJs), 'administrator credentials must not be placed in ordinary URLs');
assert(/X-Admin-Token/.test(appJs), 'administrator requests should use a private header');
assert(/X-Owner-Control-Token/.test(appJs), 'owner Control Center requests should use a separate private header');
assert(!/api\/admin\/control-center/.test(appJs), 'owner Control Center must not share the staff administrator namespace');
assert(/sj_csrf/.test(appJs) && /X-CSRF-Token/.test(appJs),'browser mutations should send explicit CSRF tokens');
assert(/X-Partner-Access/.test(appJs), 'Community Partner requests should use a private access header');
assert(!/searchParams\.get\(['"]access['"]\)/.test(appJs), 'private partner link keys should not be read from query strings');
assert(/location\.hash/.test(appJs), 'private partner links should use a URL fragment for the access key');
const liveChatJs = fs.readFileSync(path.join(pub,'live-chat.js'),'utf8');
assert(/\/api\/public-config/.test(liveChatJs), 'live chat should load non-secret public configuration from the server');
assert(/addFallback/.test(liveChatJs), 'live chat should retain a contact fallback');
const serverJs = fs.readFileSync(path.join(__dirname,'..','server.js'),'utf8');
assert(/function internalPageRole/.test(serverJs) && /owner-login\.html/.test(serverJs),'private page shells must be authenticated before delivery');
assert(/sensitiveCasePath/.test(serverJs) && /sensitiveTrafficGateEnforced/.test(serverJs),'sensitive shutdown must cover all saved-case routes');
assert(/function findUserCase/.test(serverJs), 'user case routes should require continuation-token lookup');
assert(/id: privateAccessToken/.test(serverJs), 'public case responses must not expose internal storage IDs');
assert(/function publicAttachment/.test(serverJs), 'public attachment responses should be explicitly sanitized');
const healthSource=serverJs.slice(serverJs.indexOf("pathName === '/health'"),serverJs.indexOf("pathName === '/api/system/master-rules-pack'",serverJs.indexOf("pathName === '/health'")));
assert(/practiceAreas:PRACTICE_AREAS\.length/.test(healthSource) && /portalCount:PORTALS\.length/.test(healthSource), 'public health should retain useful aggregate truth');
assert(!/features:|operationalReadiness|providerOrder|configuredProviders|storageDir/.test(healthSource), 'public health must not expose internal capability, provider, readiness, or storage details');

const controlCenterPage = fs.readFileSync(path.join(pub,'control-center.html'),'utf8');
assert(/Private Owner Control Center/.test(controlCenterPage), 'control center missing private owner identity');
assert(/noindex,nofollow/.test(controlCenterPage), 'control center must be excluded from search indexing');
assert(/controlCenterTokenForm/.test(controlCenterPage) && /controlCenterPortalList/.test(controlCenterPage), 'control center missing protected portfolio workspace');
assert(/separate owner credential/i.test(controlCenterPage), 'Control Center must explain owner/staff credential separation');
assert(/generateMasterCoordinationPrompt/.test(controlCenterPage) && /exportControlCenterPortfolio/.test(controlCenterPage), 'Control Center missing master-prompt or portfolio-export tools');
assert(/Add a private planned portal record/.test(controlCenterPage) && /controlCenterAddPortalForm/.test(controlCenterPage), 'Control Center missing private planned-portal registration');
assert(/controlCenterSystemReadiness/.test(controlCenterPage), 'Control Center missing system launch-readiness snapshot');
assert(/Master Rules and Suggestions Pack/.test(controlCenterPage) && /Professional Network, Membership, and Revenue Center/.test(controlCenterPage), 'Control Center missing rules or marketplace sections');
assert(/Official New York attorney source/.test(controlCenterPage) && /nysAttorneySourceSearchForm/.test(controlCenterPage), 'Control Center missing official New York source connector');
assert(/professionalMembershipPlans/.test(controlCenterPage) && /professionalRevenuePrograms/.test(controlCenterPage) && /professionalRecordList/.test(controlCenterPage), 'Control Center missing marketplace management panels');
assert(/Public paid-service operations/.test(controlCenterPage), 'Control Center missing public paid-service operations section');
assert(/Human Review Specialist checkout, fulfillment, support, and refunds/.test(controlCenterPage), 'Control Center missing public service lifecycle controls');
assert(/publicPaidServicesControlsForm/.test(controlCenterPage) && /publicPaidServicesOrders/.test(controlCenterPage), 'Control Center missing public paid-service controls or order queue');
assert(/NYC founding-member outreach/.test(controlCenterPage) && /createOutreachCampaignForm/.test(controlCenterPage) && /firmDiscountQuoteForm/.test(controlCenterPage) && /createOutreachProspectForm/.test(controlCenterPage), 'Control Center missing NYC outreach and firm discount controls');
const membershipPage=fs.readFileSync(path.join(pub,'professional-membership.html'),'utf8');
assert(/Basic profile control is free/.test(membershipPage) && /\$15<span>\/month<\/span>/.test(membershipPage) && /payment remains closed/i.test(membershipPage), 'professional membership page missing free-basic control, exact monthly terms, or closed payment gate');
assert(/firm-seat planning/i.test(membershipPage) && /Prepare Firm Account/.test(membershipPage), 'professional membership page missing truthful firm seat planning offer');
assert(/does not create endorsement|never buys|Payment does not improve/i.test(membershipPage), 'professional membership page missing non-influence disclosure');
const professionalJs=fs.readFileSync(path.join(pub,'professional.js'),'utf8');
assert(/officialRegistration/.test(professionalJs) && /pendingClaimProfiles/.test(professionalJs), 'professional UI missing official-record signup or pending-claim state');
assert(/firmProfessionalAdd/.test(professionalJs), 'professional dashboard missing central firm roster management');
assert(!fs.readFileSync(path.join(pub,'index.html'),'utf8').includes('/control-center.html'), 'customer homepage must not link to private Control Center');
const robots = fs.readFileSync(path.join(pub,'robots.txt'),'utf8');
assert(/Disallow: \/owner-login\.html/.test(robots) && /Disallow: \/internal-access\.html/.test(robots),'private sign-in surfaces should be discouraged from indexing');
assert(/Disallow: \/control-center\.html/.test(robots) && /Disallow: \/professional-login\.html/.test(robots) && /Disallow: \/professional-dashboard\.html/.test(robots) && /Disallow: \/api\/owner\//.test(robots), 'robots file should discourage indexing private owner and professional account surfaces');
const sitemap = fs.readFileSync(path.join(pub,'sitemap.xml'),'utf8');
assert(!/smarter-justice-app\.onrender\.com/.test(sitemap), 'sitemap should not mix the temporary Render host with the canonical domain');
assert(!/control-center\.html/.test(sitemap), 'private Control Center must not appear in the public sitemap');
assert(/professional-membership\.html/.test(sitemap), 'public professional membership page must appear in the sitemap');
assert(!/professionals\.html/.test(sitemap) && !/professional-profile\.html/.test(sitemap), 'noindexed compatibility profile lookup surfaces must not appear in the public sitemap');
const sharedStandard = fs.readFileSync(path.join(__dirname,'..','SMARTER_JUSTICE_SHARED_PLATFORM_STANDARD.md'),'utf8');
assert(/strong defaults, not inflexible rules/i.test(sharedStandard), 'shared standard missing deliberate portal-deviation policy');
assert(/dedicated development chat for each portal/i.test(sharedStandard), 'shared standard missing hybrid chat model');
const masterStandard = fs.readFileSync(path.join(__dirname,'..','SMARTER_JUSTICE_MASTER_COORDINATION_STANDARD.md'),'utf8');
assert(/Master Coordination chat/.test(masterStandard) && /dedicated development chat/.test(masterStandard), 'master coordination standard missing hybrid workflow');
const continuationStandard = fs.readFileSync(path.join(__dirname,'..','PORTAL_CONTINUATION_PROMPT_STANDARD.md'),'utf8');
assert(/both/i.test(continuationStandard) && /portal-specific/i.test(continuationStandard) && /shared standards/i.test(continuationStandard), 'continuation standard must preserve shared and portal-specific requirements');
const manifest = JSON.parse(fs.readFileSync(path.join(__dirname,'..','portal-manifest.json'),'utf8'));
assert.equal(manifest.currentDevelopmentVersion,'1.7.83');
assert.equal(manifest.testSuiteParts,146);
assert.equal(manifest.sbom,'SBOM.spdx.json');
assert(fs.existsSync(path.join(__dirname,'..','SBOM.spdx.json')),'release must include a dependency SBOM');
assert(fs.existsSync(path.join(__dirname,'..','scripts','run-migrations.js'))&&fs.existsSync(path.join(__dirname,'..','scripts','postgres-acceptance.js')),'migration and PostgreSQL acceptance tools must be packaged');
assert.equal(manifest.productionVersion,'1.6.1');
assert.equal(manifest.productionUrl,'https://smarterjustice.com');
assert.equal(manifest.deploymentService,'smarter-justice-app');
assert.equal(manifest.capabilities.releasePortabilityValidation,true);
assert.equal(manifest.capabilities.publicRegistryLockfile,true);
assert.equal(manifest.capabilities.node22Reproducibility,true);
assert.equal(manifest.capabilities.customDomainVerified,true);
assert.equal(manifest.privateControlCenter,true);
assert.equal(manifest.sharedStandardVersion,require('../data/sharedPlatformStandards').SHARED_STANDARD_VERSION,'manifest shared standard version must match the actual shared platform standard');
assert.equal(manifest.masterRulesPackVersion,'1.7.0');
assert(/^[a-f0-9]{64}$/.test(manifest.masterRulesPackChecksum), 'root manifest missing rules-pack checksum');
assert.equal(manifest.masterRulesPackChecksum, require('../data/masterRulesPack').checksum(), 'root manifest rules-pack checksum must match the exported governing pack');
assert.equal(manifest.capabilities.professionalMarketplacePrivateFoundation,true);
assert.equal(manifest.capabilities.nysAttorneyOfficialDatasetConnector,true);
assert.equal(manifest.capabilities.nycFoundingMemberPilotFoundation,true);
assert.equal(manifest.capabilities.firmVolumeDiscountFoundation,true);
assert.equal(manifest.capabilities.professionalOutreachPipelineFoundation,true);
assert.equal(manifest.capabilities.publicProfessionalDirectory,false);
assert.equal(manifest.capabilities.temporaryClaimMigrationLookup,true);
assert.equal(manifest.capabilities.focusedPortalProfessionalProfiles,true);
assert.equal(manifest.capabilities.professionalAccounts,true);
assert.equal(manifest.capabilities.centralProfessionalAccountAcrossPortals,true);
assert.equal(manifest.capabilities.stripeProfessionalSubscriptionCheckout,true);
assert.equal(manifest.capabilities.publicFirmProfiles,false);
assert.equal(manifest.capabilities.focusedPortalFirmProfiles,true);
assert.equal(manifest.capabilities.publicDirectoryPagination,true);
assert.equal(manifest.capabilities.publicDirectoryUsefulDefaultPageSize,true);
assert.equal(manifest.capabilities.firmProfileClaimWorkflow,true);
assert.equal(manifest.capabilities.ownerApprovedFirmClaimControl,true);
assert.equal(manifest.capabilities.professionalCampaignAttribution,true);
assert.equal(manifest.capabilities.officialNysAttorneyPagination,true);
assert.equal(manifest.capabilities.shareablePublicDirectoryFilters,true);
assert.equal(manifest.capabilities.sourceGroundedProfileMetadata,true);
assert.equal(manifest.capabilities.professionalSetupChecklist,true);
assert.equal(manifest.capabilities.transparentFirmMembershipEstimator,true);
assert.equal(manifest.capabilities.mobileEnrollmentAutocomplete,true);
assert.equal(manifest.capabilities.freeFirstPricingClarity,true);
assert.equal(manifest.capabilities.customerFacingPlainLanguageAuditV2,true);
assert.equal(manifest.capabilities.customerFacingTechnicalLanguageRegression,true);
assert.equal(manifest.capabilities.publicFunnelClarityPolish,true);
assert.equal(manifest.capabilities.responsiveCustomerJourneyAudit,true);
assert.equal(manifest.capabilities.mobileTouchTargetAndInputZoomSafeguards,true);
assert.equal(manifest.capabilities.plainLanguageAvailabilityLabels,true);
assert.equal(manifest.capabilities.customerFacingProfessionalDashboardCopy,true);
assert.equal(manifest.capabilities.activeJusticeTruckSmarterJusticeBrandRelationship,true);
assert.equal(manifest.professionalMarketplaceStandardVersion,'1.3.5');
const controlCenterLib = fs.readFileSync(path.join(__dirname,'..','lib','controlCenter.js'),'utf8');
assert(/promptForPortal/.test(controlCenterLib), 'missing governed portal prompt generator');
assert(/documentedDeviations/.test(controlCenterLib), 'portal portfolio must track documented specialty adaptations');
assert(/ownerDecisions/.test(controlCenterLib) && /portalSpecificRequirements/.test(controlCenterLib) && /nextBuildInstructions/.test(controlCenterLib), 'portal portfolio missing portal-specific source-of-truth fields');
assert(/masterCoordinationPrompt/.test(controlCenterLib) && /manifestForPortal/.test(controlCenterLib), 'Control Center missing master prompt or manifest generator');
assert(/function createPortal/.test(controlCenterLib) && /customPrivateRecord/.test(controlCenterLib), 'Control Center missing private custom-portal records');
const generatedPortalPrompt = require('../lib/controlCenter').promptForPortal('justice-tax-solutions');
assert(/shared standards are strong defaults, not inflexible rules/i.test(generatedPortalPrompt), 'generated prompts must preserve deviation authority');
assert(/General Smarter Justice system requirements/.test(generatedPortalPrompt) && /Portal-specific identity/.test(generatedPortalPrompt), 'generated prompt must contain shared and portal-specific sections');
assert(/function requireOwner/.test(serverJs), 'server missing separate owner authorization');
assert(!/credentials:\s*\{[\s\S]*storageStatus:\s*store\.storageStatus\(\)/.test(serverJs), 'public health response must not expose detailed storage or credential configuration');
assert(/function requireRulesPackAccess/.test(serverJs) && /x-portal-rules-token/.test(serverJs), 'server missing protected portal rules-pack access');
assert(/professional-marketplace\/public-sources\/nys-attorneys\/import/.test(serverJs), 'server missing official New York attorney import route');
assert(/api\/public\/professionals/.test(serverJs) && /api\/professional\/auth\/signup/.test(serverJs), 'server missing public professional finder or central account signup');
assert(/approve-profile-claim/.test(serverJs), 'owner claim approval route missing');
const professionalAccountsLib=fs.readFileSync(path.join(__dirname,'..','lib','professionalAccounts.js'),'utf8'); assert(/firm_professional_profile_added/.test(professionalAccountsLib) && /addProfessionalToFirm/.test(professionalAccountsLib), 'central firm roster management missing');
assert(/professional-login\.html#reset_token=/.test(professionalAccountsLib), 'password-reset links should use a URL fragment so reset tokens are not sent in HTTP requests');
assert(/maxRequests:10/.test(serverJs) && /professional-password-reset-request/.test(serverJs), 'authentication-specific rate limits are missing');
const capabilityRegistryLib=fs.readFileSync(path.join(__dirname,'..','data','crossPortalCapabilities.js'),'utf8');
assert(/sourceFiles/.test(capabilityRegistryLib) && /testStatus/.test(capabilityRegistryLib) && /requiredAdaptations/.test(capabilityRegistryLib) && /nextAction/.test(capabilityRegistryLib), 'Capability Registry must include evidence, tests, adaptations, and next actions');
assert(/OWNER_CONTROL_CENTER_TOKEN/.test(serverJs) && /x-owner-control-token/.test(serverJs), 'server missing separate owner credential configuration');
assert(!/pathName === '\/api\/admin\/control-center'/.test(serverJs), 'owner Control Center must not use staff administrator route');

const referral = fs.readFileSync(path.join(pub,'referral-program.html'),'utf8');
assert(/Community Partner/.test(referral), 'Community Partner wording missing');
assert(!/Helper/.test(referral), 'public page should not use Helper wording');
const partnerTools = fs.readFileSync(path.join(pub,'community-partner-tools.html'),'utf8');
assert(/private (?:dashboard )?access key/i.test(partnerTools), 'Community Partner dashboard should explain its separate private access key');
assert(/never shows (?:user )?names, email addresses, uploaded documents, or issue topics/i.test(partnerTools), 'Community Partner dashboard should explain anonymized reporting');
const admin = fs.readFileSync(path.join(pub,'staff.html'),'utf8');
assert(/Human Review Specialist/.test(admin), 'staff page missing Human Review Specialist workflow');
assert(/Why this path was chosen/.test(appJs), 'staff workbench should show why path was chosen');
const contact = fs.readFileSync(path.join(pub,'contact.html'),'utf8');
assert(!/reachrgnow|OWNER_NOTIFICATION_EMAIL|owner\/admin/i.test(contact), 'contact page must not expose internal notification details');
const flyer = fs.readFileSync(path.join(pub,'partner-flyer.html'),'utf8');
assert(!/https?:\/\//.test(flyer), 'flyer should avoid plain website address');
for (const name of ['cases.json','communityPartners.json','notifications.json','auditLog.json','portalPortfolio.json']) assert.equal(fs.readFileSync(path.join(__dirname, '..', 'storage', name), 'utf8').trim(), '[]', `release ZIP should not include ${name} data`);
const accountsStorage=JSON.parse(fs.readFileSync(path.join(__dirname,'..','storage','professionalAccounts.json'),'utf8'));
assert.deepEqual(accountsStorage.accounts||[],[], 'release ZIP should not include professional account data');
assert.deepEqual(accountsStorage.sessions||[],[], 'release ZIP should not include professional sessions');
assert.deepEqual(accountsStorage.passwordResetRequests||[],[], 'release ZIP should not include professional password reset requests');
assert.equal(accountsStorage.schemaVersion,'1.4.0','professional account seed schema must match the email-verification release');
assert.deepEqual(accountsStorage.emailVerificationRequests||[],[], 'release ZIP should not include professional email verification requests');
const ownerAccountsStorage=JSON.parse(fs.readFileSync(path.join(__dirname,'..','storage','ownerAccounts.json'),'utf8'));
assert.deepEqual(ownerAccountsStorage.accounts||[],[], 'release ZIP should not include owner account data');
assert.deepEqual(ownerAccountsStorage.sessions||[],[], 'release ZIP should not include owner sessions');
const marketplaceStorage=JSON.parse(fs.readFileSync(path.join(__dirname,'..','storage','professionalMarketplace.json'),'utf8'));
assert.equal(marketplaceStorage.pilotControls?.status,'paused', 'release ZIP must keep founding-member enrollment paused by default');
for(const key of ['firms','professionals','profileRequests','appointments','reviews','complaints','consentRecords','professionalOpportunities','outreachCampaigns','outreachProspects']) assert.deepEqual(marketplaceStorage[key],[], `release ZIP should not include marketplace ${key} data`);
const rules=require('../data/masterRulesPack');
const rulesJson=JSON.parse(fs.readFileSync(path.join(__dirname,'..','SMARTER_JUSTICE_MASTER_RULES_AND_SUGGESTIONS_PACK.json'),'utf8'));
assert.equal(rulesJson.version,rules.MASTER_RULES_PACK_VERSION);
assert.equal(rulesJson.checksum,rules.checksum());
assert.equal(fs.readFileSync(path.join(__dirname,'..','SMARTER_JUSTICE_MASTER_RULES_AND_SUGGESTIONS_PACK.md'),'utf8'),rules.markdown(),'exported Markdown rules pack is stale');
const marketplaceStandards=fs.readFileSync(path.join(__dirname,'..','data','professionalMarketplaceStandards.js'),'utf8');
assert(/professional-memberships/.test(marketplaceStandards), 'revenue architecture missing professional memberships');
assert(/founding-member-pilot/.test(marketplaceStandards) && /firm-volume-discounts/.test(marketplaceStandards) && /mobile-qr-enrollment/.test(marketplaceStandards), 'marketplace standards missing founding member, firm discount, or QR enrollment revenue architecture');
assert(/NYC founding-member/.test(rules.markdown()) && /volume discounts/.test(rules.markdown()), 'Master Rules Pack missing NYC founding-member or firm-discount strategy');
assert(/eqw2-r5nb/.test(fs.readFileSync(path.join(__dirname,'..','data','publicProfessionalDataSources.js'),'utf8')), 'official New York attorney dataset connector missing');
const formDraftsPage = fs.readFileSync(path.join(pub,'form-drafts.html'),'utf8');
assert(/Carefully Prepared Form Drafts/.test(formDraftsPage) && /IRS Form 9465/.test(formDraftsPage) && /IRS Form 1040-X/.test(formDraftsPage) && /Form 433-A/.test(formDraftsPage), 'form drafts page missing expanded draft paths');
const pricing = fs.readFileSync(path.join(pub,'pricing.html'),'utf8');
assert(/Professional membership plans/.test(pricing) && /Professional Membership/.test(pricing) && /Firm Membership/.test(pricing) && /Meaningful guided starting help stays free/.test(pricing) && /Optional human help/.test(pricing) && /Published only when ready/.test(pricing), 'pricing page missing professional-first and free-public-access structure');
assert(!/Notice or Document Starter Review|Human Review Specialist Starter File|Completed Forms After Review/.test(pricing), 'pricing page must not sell unapproved public services');
for (const f of focusedPracticePages) { const page = fs.readFileSync(path.join(pub,f),'utf8'); assert(/Start Free/.test(page) && /Describe Notice/.test(page), `${f} missing focused conversion links`); }

const professionalSignupPage=fs.readFileSync(path.join(pub,'professional-signup.html'),'utf8');
assert(/data-nav-toggle/.test(professionalSignupPage) && /Create your account now\. Complete your profile at your pace\./i.test(professionalSignupPage), 'professional signup should have mobile navigation and a clear account-creation heading');
assert(/professional-membership-terms\.html/.test(professionalSignupPage), 'professional signup must link to membership terms');
const professionalTerms=fs.readFileSync(path.join(pub,'professional-membership-terms.html'),'utf8');
assert(/recurring/i.test(professionalTerms) && /cancel/i.test(professionalTerms) && /does not guarantee/i.test(professionalTerms), 'professional membership terms must explain recurring billing, cancellation, and non-guarantee');
for(const f of ['control-center.html','staff.html','admin.html','dashboard.html','next-path.html','checkout-success.html','checkout-cancel.html','launch-readiness.html','production-readiness.html','ai-summary.html','professional-dashboard.html','professional-login.html','professional-signup.html']){
  const page=fs.readFileSync(path.join(pub,f),'utf8');
  assert(/noindex/.test(page), `${f} should be excluded from public indexing`);
}
assert(!/launch-readiness\.html|production-readiness\.html|ai-summary\.html|dashboard\.html|checkout-success\.html|checkout-cancel\.html|next-path\.html/.test(sitemap), 'private, result, and internal readiness pages must not appear in the public sitemap');
assert(/professional-membership-terms\.html/.test(sitemap), 'professional membership terms should appear in the public sitemap');
assert(/publicLanguageReadiness/.test(controlCenterLib) && /conversionReadiness/.test(controlCenterLib) && /promptHandoffReadiness/.test(controlCenterLib) && /accessibilityReadiness/.test(controlCenterLib), 'Control Center must track public language, conversion, handoff, and accessibility readiness');
assert(/publicLanguageReadiness/.test(appJs) && /Signup and conversion/.test(appJs), 'Control Center UI missing expanded readiness fields');
assert.equal(manifest.sharedStandardVersion,require('../data/sharedPlatformStandards').SHARED_STANDARD_VERSION);
assert.equal(manifest.capabilities.publicLanguageReleaseAudit,true);
assert.equal(manifest.capabilities.mobileProfessionalConversionPolish,true);
assert.equal(manifest.capabilities.sharedMicroPortalOriginStoryStandard,true);
const originStandard=fs.readFileSync(path.join(__dirname,'..','PORTAL_PROFESSIONAL_INTEGRATION_STANDARD.md'),'utf8');
assert(/street-level outreach through Justice Truck/.test(originStandard) && /specialty portal remains the primary portal brand/i.test(originStandard), 'micro-portal origin-story standard missing or incomplete');

console.log('static-checks.test.js passed');
