const assert=require('assert');
const fs=require('fs');
const path=require('path');
const portals=require('../data/portals');
const schemas=require('../data/intakeSchemas');
const router=require('../lib/router');
const portal=portals.getPortalBySlug('domestic-violence-safety-support');
assert(portal,'Stop Sign Project portal registry entry is required');
assert.equal(portal.officialDomain,'stopsignproject.org');
assert.equal(portal.status,'In Development');
assert.equal(portal.defaultUrl,'');
assert.equal(portal.publicUrl,'','an unverified in-development destination must not be published automatically');
assert(portal.practices.includes('domestic-violence-protection-orders'));
assert(schemas.SCHEMAS['domestic-violence-protection-orders'],'domestic-violence-specific safe intake schema is required');
const source=fs.readFileSync(path.join(__dirname,'..','data','intakeSchemas.js'),'utf8');
assert(/no-save|not save|does not save/i.test(source),'bridge intake must disclose no-save behavior');
const inferred=router.inferPractice('My former partner is stalking me and violated the order of protection.');
assert.equal(inferred.slug,'domestic-violence-protection-orders');
assert(!fs.existsSync(path.join(__dirname,'..','data','domesticViolenceSupport.js')),'unverified resource content must not remain embedded in the shared release');
console.log('stop-sign-project-bridge.test.js passed');
