'use strict';
const assert=require('assert');const fs=require('fs');const os=require('os');const path=require('path');process.env.NODE_ENV='test';process.env.SMARTER_JUSTICE_STORAGE_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'sj-profile-growth-v1725-'));
const seeds=require('../data/threeMarketProfileSeedsV1725');const marketplace=require('../lib/professionalMarketplace');const batch=seeds.THREE_MARKET_PROFILE_BATCH_V1725;
assert.equal(batch.leadMarket,'Northern Metro New Jersey');assert.equal(batch.nextLeadMarket,'Brooklyn');assert.deepEqual(batch.actual,{individualProfessionals:12,firms:2,professionalFirmLinks:12,markets:{'Northern Metro New Jersey':8,Manhattan:2,Brooklyn:2}});assert.equal(seeds.THREE_MARKET_PROFESSIONAL_SEEDS_V1725.length,12);assert.equal(seeds.THREE_MARKET_FIRM_SEEDS_V1725.length,2);assert.equal(new Set(seeds.THREE_MARKET_PROFESSIONAL_SEEDS_V1725.map(x=>x.id)).size,12);
for(const p of seeds.THREE_MARKET_PROFESSIONAL_SEEDS_V1725){assert(p.firmId&&p.officeLocations.length&&p.practiceAreas.length&&p.portalEligibility.length&&p.sourceRecords.length);assert.equal(p.claimStatus,'not claimed');assert.equal(p.verificationStatus,'not started');assert(p.sourceRecords.every(x=>x.authorityLevel==='self-reported'&&x.reviewStatus==='approved source'));}
const metrics=marketplace.directoryMetrics();assert.equal(metrics.publicProfessionals,233);assert.equal(metrics.publicFirms,48);assert.equal(metrics.publicTotal,281);assert.equal(metrics.qualifyingProfessionals,232);assert.equal(metrics.qualifyingFirms,46);assert.equal(metrics.qualifyingTotal,278);assert.equal(marketplace.searchPublicProfessionals({city:'Jersey City',limit:200}).total,15);assert.equal(marketplace.searchPublicProfessionals({city:'Newark',limit:200}).total,12);
const owner=marketplace.getOwnerData();for(const id of seeds.THREE_MARKET_PROFESSIONAL_SEEDS_V1725.map(x=>x.id)){const p=owner.professionals.find(x=>x.id===id);assert(p&&p.sourceSeeded&&p.publicProfileEnabled);assert.equal(p.claimStatus,'not claimed');assert.equal(p.verificationStatus,'not started');assert.equal(p.eligibility.consultationEligible,false);assert.equal(p.membership.status,'none');assert(p.firmId);}
assert.equal(owner.profileGrowthBatch.version,'1.7.31');assert.equal(marketplace.publicFeatureStatus().threeMarketProfileBatch.version,'1.7.29');const report=JSON.parse(fs.readFileSync(path.join(__dirname,'..','PROFILE_GROWTH_REPORT_V1.7.25.json'),'utf8'));assert.equal(report.actual.newIndividualProfessionals,12);assert.equal(report.actual.newFirms,2);assert.equal(report.actual.newProfessionalFirmLinks,12);assert.equal(report.finalDirectory.publicTotal,131);assert.equal(report.finalDirectory.qualifyingTotal,128);
console.log('three-market-profile-growth-v1725.test.js passed');
