'use strict';
const assert=require('assert');const fs=require('fs');const os=require('os');const path=require('path');
process.env.NODE_ENV='test';process.env.SMARTER_JUSTICE_STORAGE_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'sj-profile-growth-v1722-'));
const seeds=require('../data/threeMarketProfileSeedsV1722');const marketplace=require('../lib/professionalMarketplace');const batch=seeds.THREE_MARKET_PROFILE_BATCH_V1722;
assert.equal(batch.leadMarket,'Northern Metro New Jersey');assert.equal(batch.nextLeadMarket,'Brooklyn');assert.deepEqual(batch.actual,{individualProfessionals:12,firms:2,professionalFirmLinks:12,markets:{'Northern Metro New Jersey':8,Manhattan:2,Brooklyn:2}});assert.equal(seeds.THREE_MARKET_PROFESSIONAL_SEEDS_V1722.length,12);assert.equal(seeds.THREE_MARKET_FIRM_SEEDS_V1722.length,2);assert.equal(new Set(seeds.THREE_MARKET_PROFESSIONAL_SEEDS_V1722.map(x=>x.id)).size,12);
for(const p of seeds.THREE_MARKET_PROFESSIONAL_SEEDS_V1722){assert(p.firmId&&p.officeLocations.length&&p.practiceAreas.length&&p.portalEligibility.length&&p.sourceRecords.length);assert.equal(p.claimStatus,'not claimed');assert.equal(p.verificationStatus,'not started');assert(p.sourceRecords.every(x=>x.authorityLevel==='self-reported'&&x.reviewStatus==='approved source'));}
assert.deepEqual(marketplace.directoryMetrics(),{publicProfessionals:233,publicFirms:48,publicTotal:281,qualifyingProfessionals:232,qualifyingFirms:46,qualifyingTotal:278,qualificationRule:marketplace.directoryMetrics().qualificationRule});assert.equal(marketplace.searchPublicProfessionals({county:'Hudson County',limit:100}).total,21);assert.equal(marketplace.searchPublicProfessionals({county:'Essex County',limit:100}).total,13);assert.equal(marketplace.searchPublicProfessionals({city:'New York',limit:100}).total,51);assert.equal(marketplace.searchPublicProfessionals({city:'Brooklyn',limit:100}).total,75);
for(const id of seeds.THREE_MARKET_PROFESSIONAL_SEEDS_V1722.map(x=>x.id)){const p=marketplace.getOwnerData().professionals.find(x=>x.id===id);assert(p&&p.sourceSeeded&&p.publicProfileEnabled);assert.equal(p.claimStatus,'not claimed');assert.equal(p.verificationStatus,'not started');assert.equal(p.eligibility.consultationEligible,false);assert.equal(p.membership.status,'none');assert(p.firmId);}
const owner=marketplace.getOwnerData();assert.equal(owner.profileGrowthBatch.version,'1.7.31');assert.equal(owner.profileGrowthBatch.nextLeadMarket,'The Bronx');const report=JSON.parse(fs.readFileSync(path.join(__dirname,'..','PROFILE_GROWTH_REPORT_V1.7.22.json'),'utf8'));assert.equal(report.actual.newIndividualProfessionals,12);assert.equal(report.actual.newFirms,2);assert.equal(report.actual.newProfessionalFirmLinks,12);assert.equal(report.finalDirectory.publicTotal,89);assert.equal(report.finalDirectory.qualifyingTotal,86);console.log('three-market-profile-growth-v1722.test.js passed');
