'use strict';
const assert=require('assert');const http=require('http');const connector=require('../lib/v14LiveEvidenceConnector');const workspace=require('../lib/v14EvidenceBatchWorkspace');const planner=require('../lib/v14EvidenceReadinessPlanner');const app=require('../server');
const TEST_NOW=new Date();const TEST_NOW_ISO=TEST_NOW.toISOString();const OBSERVED_AT=new Date(TEST_NOW.getTime()-60*1000).toISOString();const EXPIRES_AT=new Date(TEST_NOW.getTime()+60*60*1000).toISOString();
function request(base,path,{method='GET',headers={},body=null}={}){return new Promise((resolve,reject)=>{const req=http.request(base+path,{method,headers:{...headers,...(body?{'content-type':'application/json'}:{})}},res=>{let text='';res.on('data',d=>text+=d);res.on('end',()=>resolve({status:res.statusCode,data:JSON.parse(text)}));});req.on('error',reject);if(body)req.write(JSON.stringify(body));req.end();});}
function receipt(component,id){const now=OBSERVED_AT;const rule=require('../V14_LIVE_EVIDENCE_CONNECTOR_CONTRACT_V1.7.83.json').component_rules.find(x=>x.component_id===component);const value={schema_id:'SJP-V14-LIVE-EVIDENCE-RECEIPT-2026-08-03-V1',receipt_id:id,component_id:component,environment:'production',evidence_type:rule.evidence_type,observed_at:now,expires_at:EXPIRES_AT,identities:{source_artifact_sha256:'61fea278a69055915e9b4b916e4b64ec514614f1746cacf659a6931ccd0228b1',release_version:'1.7.83',repository:'owner/repository',commit_sha256:'a'.repeat(40),service:'render-central'},checks:rule.required_checks.map(x=>({id:x,status:'PASS',evidence_ref:`masked:${x}`,observed_at:now})),contains_secrets:false,write_performed:false,production_activation_performed:false,owner_go_inferred:false};value.receipt_digest=connector.digest(value);return value;}
function batch(){const value={schema_id:'SJP-V14-LIVE-EVIDENCE-BATCH-2026-08-03-V1',batch_id:'LIVE-EVIDENCE-READINESS-BATCH-0001',receipts:[receipt('github-canonical-repository','LIVE-EVIDENCE-GITHUB-READINESS-0001'),receipt('render-central-service','LIVE-EVIDENCE-RENDER-READINESS-0001')]};value.batch_digest=workspace.digest(value);return value;}
(async()=>{const good=batch();const result=planner.plan(good,{now:TEST_NOW_ISO});assert.equal(result.ok,true,result.validation.errors.join(','));assert.equal(result.plan.component_count,8);assert.equal(result.plan.valid_receipt_count,2);assert.equal(result.plan.evidence_coverage_percent,25);assert.equal(result.plan.components.find(x=>x.component_id==='render-central-service').missing_dependencies.length,0);assert.equal(result.plan.components.find(x=>x.component_id==='openai-central-gateway').missing_dependencies.length,0);assert.equal(result.plan.components.find(x=>x.component_id==='production-deployment').missing_dependencies.length,5);assert.equal(result.plan.apply_supported,false);assert.equal(result.plan.deployment_authorized,false);assert.equal(result.plan.launch_state,'NO_GO');assert.match(result.plan.one_exact_owner_action,/PostgreSQL/);const repeat=planner.plan(good,{now:TEST_NOW_ISO});assert.equal(result.plan.plan_digest,repeat.plan.plan_digest);const bad=batch();bad.receipts[0].contains_secrets=true;bad.receipts[0].receipt_digest=connector.digest(bad.receipts[0]);bad.batch_digest=workspace.digest(bad);const rejected=planner.plan(bad,{now:TEST_NOW_ISO});assert.equal(rejected.ok,false);assert(rejected.plan.components.find(x=>x.component_id==='github-canonical-repository').validation_errors.includes('secret-bearing'));
 const old=process.env.OWNER_CONTROL_CENTER_TOKEN;process.env.OWNER_CONTROL_CENTER_TOKEN='test-owner-v1782';const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base=`http://127.0.0.1:${server.address().port}`;try{assert.equal((await request(base,'/api/owner/live-evidence/readiness-plan')).status,403);const headers={'x-owner-control-token':'test-owner-v1782'};const owner=await request(base,'/api/owner/live-evidence/readiness-plan',{headers});assert.equal(owner.status,200);assert.equal(owner.data.appVersion,'1.7.83');const api=await request(base,'/api/owner/live-evidence/readiness-plan',{method:'POST',headers,body:good});assert.equal(api.status,200);assert.equal(api.data.plan.plan.apply_supported,false);}finally{await new Promise(r=>server.close(r));if(old===undefined)delete process.env.OWNER_CONTROL_CENTER_TOKEN;else process.env.OWNER_CONTROL_CENTER_TOKEN=old;}
 console.log('v14-evidence-readiness-planner-v1782.test.js passed');})().catch(e=>{console.error(e);process.exit(1);});
