'use strict';
const assert=require('assert');const http=require('http');const connector=require('../lib/v14LiveEvidenceConnector');const workspace=require('../lib/v14EvidenceBatchWorkspace');const app=require('../server');
const TEST_NOW=new Date();const TEST_NOW_ISO=TEST_NOW.toISOString();const OBSERVED_AT=new Date(TEST_NOW.getTime()-60*1000).toISOString();const EXPIRES_AT=new Date(TEST_NOW.getTime()+60*60*1000).toISOString();
function request(base,path,{method='GET',headers={},body=null}={}){return new Promise((resolve,reject)=>{const req=http.request(base+path,{method,headers:{...headers,...(body?{'content-type':'application/json'}:{})}},res=>{let text='';res.on('data',d=>text+=d);res.on('end',()=>resolve({status:res.statusCode,data:JSON.parse(text)}));});req.on('error',reject);if(body)req.write(JSON.stringify(body));req.end();});}
function receipt(component='github-canonical-repository',id='LIVE-EVIDENCE-GITHUB-BATCH-0001'){
 const now=OBSERVED_AT;const checks={
  'github-canonical-repository':['repository-resolved','commit-resolved','protected-branch-confirmed','secret-scan-pass'],
  'render-central-service':['service-resolved','deployment-resolved','artifact-bound','dark-state-confirmed','rollback-identified']
 }[component];
 const value={schema_id:'SJP-V14-LIVE-EVIDENCE-RECEIPT-2026-08-03-V1',receipt_id:id,component_id:component,environment:'production',evidence_type:component==='github-canonical-repository'?'REPOSITORY_OBSERVATION':'DEPLOYMENT_OBSERVATION',observed_at:now,expires_at:EXPIRES_AT,identities:{source_artifact_sha256:'61fea278a69055915e9b4b916e4b64ec514614f1746cacf659a6931ccd0228b1',release_version:'1.7.83',repository:'owner/repository',commit_sha256:'a'.repeat(40),service:'render-central'},checks:checks.map(x=>({id:x,status:'PASS',evidence_ref:`masked:${x}`,observed_at:now})),contains_secrets:false,write_performed:false,production_activation_performed:false,owner_go_inferred:false};value.receipt_digest=connector.digest(value);return value;
}
function batch(receipts=[receipt(),receipt('render-central-service','LIVE-EVIDENCE-RENDER-BATCH-0001')]){const value={schema_id:'SJP-V14-LIVE-EVIDENCE-BATCH-2026-08-03-V1',batch_id:'LIVE-EVIDENCE-BATCH-0001',receipts};value.batch_digest=workspace.digest(value);return value;}
(async()=>{const good=batch();const result=workspace.validateBatch(good,{now:TEST_NOW_ISO});assert.equal(result.ok,true,result.errors.join(','));const preview=workspace.previewTransaction(good,{now:TEST_NOW_ISO});assert.equal(preview.transaction.promotions.length,2);assert.equal(preview.transaction.applied,false);assert.equal(preview.transaction.register_mutated,false);const conflict=batch([receipt(),receipt('github-canonical-repository','LIVE-EVIDENCE-GITHUB-BATCH-0002')]);assert(workspace.validateBatch(conflict,{now:TEST_NOW_ISO}).errors.includes('component-conflict:github-canonical-repository'));const replay=batch([receipt(),receipt()]);const replayErrors=workspace.validateBatch(replay,{now:TEST_NOW_ISO}).errors;assert(replayErrors.some(x=>x.startsWith('duplicate-receipt-id:')));assert(replayErrors.some(x=>x.startsWith('replayed-receipt-digest:')));const mixed=batch();mixed.receipts[1].environment='staging';mixed.receipts[1].receipt_digest=connector.digest(mixed.receipts[1]);mixed.batch_digest=workspace.digest(mixed);assert(workspace.validateBatch(mixed,{now:TEST_NOW_ISO}).errors.includes('mixed-environment'));const tampered=batch();tampered.receipts[0].identities.repository='other/repository';tampered.batch_digest=workspace.digest(tampered);assert(workspace.validateBatch(tampered,{now:TEST_NOW_ISO}).errors.some(x=>x.endsWith(':digest')));
 const old=process.env.OWNER_CONTROL_CENTER_TOKEN;process.env.OWNER_CONTROL_CENTER_TOKEN='test-owner-v1781';const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base=`http://127.0.0.1:${server.address().port}`;try{assert.equal((await request(base,'/api/owner/live-evidence/workspace')).status,403);const headers={'x-owner-control-token':'test-owner-v1781'};const owner=await request(base,'/api/owner/live-evidence/workspace',{headers});assert.equal(owner.status,200);assert.equal(owner.data.appVersion,'1.7.83');const api=await request(base,'/api/owner/live-evidence/batch-preview',{method:'POST',headers,body:good});assert.equal(api.status,200);assert.equal(api.data.preview.transaction.apply_supported,false);assert.equal(api.data.preview.transaction.deployment_authorized,false);}finally{await new Promise(r=>server.close(r));if(old===undefined)delete process.env.OWNER_CONTROL_CENTER_TOKEN;else process.env.OWNER_CONTROL_CENTER_TOKEN=old;}
 console.log('v14-evidence-batch-workspace-v1781.test.js passed');})().catch(e=>{console.error(e);process.exit(1);});
