'use strict';
const manifest=require('../data/commercialTermsV1775');
function clone(v){return JSON.parse(JSON.stringify(v));}
function quoteIndividual(){return{monthlyTotalCents:manifest.plans.coveredAttorneyProfile.monthlyPriceCents,billingInterval:'monthly'};}
function quoteFirm(coveredAttorneySeats){const seats=Math.max(0,Math.min(10000,Math.trunc(Number(coveredAttorneySeats)||0)));return{firmProfileMonthlyCents:manifest.plans.claimedFirmProfile.monthlyPriceCents,coveredAttorneySeats:seats,seatMonthlyCents:manifest.plans.firmCoveredAttorneySeat.monthlyPriceCents,monthlyTotalCents:manifest.plans.claimedFirmProfile.monthlyPriceCents+seats*manifest.plans.firmCoveredAttorneySeat.monthlyPriceCents,billingInterval:'monthly',discountPercent:0};}
function validatePayers(records=[]){const errors=[];const seen=new Map();for(const r of records){if(!r||!r.attorneyProfileId||!r.payerId||r.active!==true)continue;if(seen.has(r.attorneyProfileId)&&seen.get(r.attorneyProfileId)!==r.payerId)errors.push(`${r.attorneyProfileId}:multiple-active-payers`);seen.set(r.attorneyProfileId,r.payerId);}return{ok:errors.length===0,errors,activeCoveredSeats:seen.size};}
function validate(){const errors=[];if(manifest.releaseVersion!=='1.7.75')errors.push('release-version');if(manifest.billingInterval!=='MONTHLY_ONLY')errors.push('monthly-only');for(const key of ['coveredAttorneyProfile','claimedFirmProfile','firmCoveredAttorneySeat'])if(manifest.plans?.[key]?.monthlyPriceCents!==1500)errors.push(`${key}:price`);if(quoteFirm(1).monthlyTotalCents!==3000||quoteFirm(3).monthlyTotalCents!==6000)errors.push('firm-examples');if(manifest.publicActivation!==false||manifest.liveBilling!==false)errors.push('billing-gate');if(manifest.claimMemberSeparation!==true)errors.push('claim-member-separation');return{ok:errors.length===0,errors,releaseVersion:manifest.releaseVersion};}
function ownerView(){return{manifest:clone(manifest),validation:validate(),examples:{individual:quoteIndividual(),firmOneSeat:quoteFirm(1),firmThreeSeats:quoteFirm(3)}};}
module.exports={quoteIndividual,quoteFirm,validatePayers,validate,ownerView};
