'use strict';
const plan=require('../CONTINUOUS_SELF_IMPROVEMENT_AND_INNOVATION_PLAN_V1.7.83.json');
const report=require('../PRODUCT_AND_PROMPT_DUAL_IMPROVEMENT_REPORT_V1.7.83.json');
const learning=require('../CROSS_VERSION_LEARNING_LEDGER_V1.7.83.json');
function clone(v){return JSON.parse(JSON.stringify(v));}
function text(v){return String(v??'').trim();}
function validateImprovement(row,kind){const errors=[];for(const field of kind==='product'?['category','problem','implementation','before_state','after_state','benefit']:['category','problem','implementation','before_state','after_state','future_build_benefit'])if(!text(row?.[field]))errors.push(`${kind}:${field}`);const files=kind==='product'?row?.affected_files_records_or_systems:row?.affected_files_or_artifacts;if(!Array.isArray(files)||files.length<2)errors.push(`${kind}:affected-files`);if(!Array.isArray(row?.tests_and_acceptance_evidence)||row.tests_and_acceptance_evidence.length<1)errors.push(`${kind}:tests`);if(!Array.isArray(row?.limitations)||row.limitations.length<1)errors.push(`${kind}:limitations`);if(text(row?.before_state)===text(row?.after_state))errors.push(`${kind}:no-material-delta`);return errors;}
function validate(value=report,learn=learning,innovationPlan=plan){const errors=[];if(value.schema_id!=='SJP-LMP-PRODUCT-AND-PROMPT-DUAL-IMPROVEMENT-REPORT-2026-08-03-V1')errors.push('schema');if(value.product?.version!=='1.7.83')errors.push('version');if(value.release_classification!=='ORDINARY_MATERIAL_DUAL_TRACK_RELEASE')errors.push('classification');if(innovationPlan.product?.starting_artifact_sha256!=='61fea278a69055915e9b4b916e4b64ec514614f1746cacf659a6931ccd0228b1')errors.push('source-artifact');if(innovationPlan.governing_packet?.sha256!=='fce42ce0927748f94189692ef5b3bf8e0fe9f8d12273287f03a68eb7bccdad6f')errors.push('packet');if(innovationPlan.strongest_justified_set_selected!==true||innovationPlan.hard_constraints_preserved!==true)errors.push('plan-boundary');const products=value.product_platform_improvements||[],builders=value.builder_prompt_system_improvements||[];if(!products.length)errors.push('product-track-empty');if(!builders.length)errors.push('builder-track-empty');products.forEach(row=>errors.push(...validateImprovement(row,'product')));builders.forEach(row=>errors.push(...validateImprovement(row,'builder')));if(!Array.isArray(learn.lessons)||learn.lessons.length<2)errors.push('learning-lessons');for(const lesson of learn.lessons||[]){for(const field of ['observation','product_change_made','builder_prompt_system_change_made','future_candidate_selection_effect','future_testing_or_recovery_effect'])if(!text(lesson[field]))errors.push(`lesson:${field}`);}if(!Array.isArray(value.prior_limitations_reviewed)||value.prior_limitations_reviewed.length<2)errors.push('prior-limitations');const productPassed=products.length>0&&!errors.some(e=>e.startsWith('product:'));const builderPassed=builders.length>0&&!errors.some(e=>e.startsWith('builder:'))&&!errors.some(e=>e.startsWith('lesson:'))&&!errors.includes('learning-lessons')&&!errors.includes('prior-limitations');if(value.dual_track_gate?.product_platform_track_passed!==productPassed)errors.push('product-gate-claim');if(value.dual_track_gate?.builder_prompt_system_track_passed!==builderPassed)errors.push('builder-gate-claim');const authorized=productPassed&&builderPassed&&value.hard_constraints_preserved===true&&innovationPlan.hard_constraints_preserved===true;if(value.dual_track_gate?.ordinary_material_release_authorized!==authorized)errors.push('release-authority-claim');return{ok:errors.length===0,errors,productPlatformTrackPassed:productPassed,builderPromptSystemTrackPassed:builderPassed,ordinaryMaterialReleaseAuthorized:errors.length===0&&authorized,deploymentAuthorized:false,productionRequestSent:false};}
function ownerView(){return{innovationPlan:clone(plan),dualImprovementReport:clone(report),crossVersionLearning:clone(learning),validation:validate(),deploymentAuthorized:false,productionRequestSent:false};}
module.exports={validateImprovement,validate,ownerView};
