'use strict';
const {PORTALS}=require('../data/portals');
const CURRENT_RELEASE='1.7.41';
const CURRENT_SMARTER_JUSTICE_ARTIFACT=Object.freeze({portalId:'general-smarter-justice-start',portalName:'Smarter Justice',version:'1.7.34',artifactName:'smarter-justice-v1.7.34.zip',sha256:'b363bf4a41422646f7561d67b387039b39dcbc55343c950e16d8493dd72ffcb1',sizeBytes:1744744,zipEntries:556,files:545,explicitDirectories:11,evidenceLevel:'exact artifact independently verified as the source for the v1.7.37 build audit and immediate rollback',deploymentStatus:'not deployed; last verified production remains v1.6.1',recordedAt:'2026-07-27'});
const ALLOWED_PORTAL_IDS=new Set(PORTALS.map(x=>x.slug));
const OUT_OF_SCOPE_IDS=new Set(['smarter-money','smarter-health','smarter-property','smarter-ecosystem-control-center']);
const CONFIDENTIAL_KEY_PATTERN=/(^|_)(case|matter|client|patient|document|upload|credential|password|secret|token|social.?security|bank.?account|medical.?record|privileged.?communication)(_|$)/i;
function clone(v){return JSON.parse(JSON.stringify(v));}
function validateArtifact(row={}){const errors=[];if(!ALLOWED_PORTAL_IDS.has(row.portalId))errors.push('portalId is outside the legal-portal registry scope');if(!String(row.version||'').trim())errors.push('version is required');if(!String(row.artifactName||'').toLowerCase().endsWith('.zip'))errors.push('artifactName must identify a ZIP');if(!/^[a-f0-9]{64}$/.test(String(row.sha256||'')))errors.push('sha256 must be 64 lowercase hexadecimal characters');if(!Number.isInteger(row.sizeBytes)||row.sizeBytes<1)errors.push('sizeBytes must be a positive integer');return{valid:errors.length===0,errors};}
function scanConfidentialKeys(value,path='root',findings=[]){if(!value||typeof value!=='object')return findings;for(const [key,child] of Object.entries(value)){const next=`${path}.${key}`;if(CONFIDENTIAL_KEY_PATTERN.test(key))findings.push(next);if(child&&typeof child==='object')scanConfidentialKeys(child,next,findings);}return findings;}
function buildControls(registry={}){const source=clone(registry.sourceArtifacts||registry.learningSystem?.sourceArtifacts||[]);const legalSource=source.filter(x=>ALLOWED_PORTAL_IDS.has(x.portalId));const rejected=source.filter(x=>OUT_OF_SCOPE_IDS.has(x.portalId)||!ALLOWED_PORTAL_IDS.has(x.portalId));const historical=[...legalSource];const sjOld=historical.find(x=>x.portalId==='general-smarter-justice-start');if(sjOld)sjOld.supersededBy={version:CURRENT_SMARTER_JUSTICE_ARTIFACT.version,sha256:CURRENT_SMARTER_JUSTICE_ARTIFACT.sha256,recordedAt:'2026-07-26'};historical.push(clone(CURRENT_SMARTER_JUSTICE_ARTIFACT));const identityChecks=historical.map(row=>({portalId:row.portalId,version:row.version,artifactName:row.artifactName,sha256:row.sha256,sizeBytes:row.sizeBytes,validation:validateArtifact(row)}));const stale=legalSource.filter(x=>x.portalId!=='general-smarter-justice-start').map(x=>({portalId:x.portalId,recordedVersion:x.version,recordedArtifact:x.artifactName,status:'verify-before-update',reason:'This coordination snapshot may be older than the newest dedicated portal artifact. The registry must not be updated until that dedicated ZIP is uploaded and independently verified.'}));const conflictRecords=rejected.map(x=>({portalId:x.portalId,artifactName:x.artifactName||'',classification:'out-of-scope-or-archival',resolution:x.portalId==='smarter-ecosystem-control-center'?'Keep as archival compatibility evidence only; do not continue a multi-sector platform.':'Reject from the Smarter Justice legal-portal registry.'}));return{version:'1.0.0',generatedForRelease:CURRENT_RELEASE,scope:'Smarter Justice and its separate legal micro-portals only',automaticCrossRepositorySynchronization:false,currentSmarterJusticeArtifact:clone(CURRENT_SMARTER_JUSTICE_ARTIFACT),artifactHistory:historical,identityChecks,staleRecords:stale,conflictRecords,decisionQueue:[...stale.map(x=>({portalId:x.portalId,decision:'verify newest dedicated artifact before changing registry truth'})),...conflictRecords.map(x=>({portalId:x.portalId,decision:x.resolution}))],appendOnlyRules:['Never delete or rewrite a previously verified artifact identity.','Add a supersession link only after the newer dedicated ZIP is independently verified.','Keep deployment truth separate from artifact existence.','Reject out-of-scope sector records.','Reject confidential matter data and secrets.'],summary:{allowedPortalIds:ALLOWED_PORTAL_IDS.size,artifactHistoryRecords:historical.length,validIdentityRecords:identityChecks.filter(x=>x.validation.valid).length,invalidIdentityRecords:identityChecks.filter(x=>!x.validation.valid).length,staleRecords:stale.length,conflicts:conflictRecords.length}};}
function validateImport(payload={}){const confidentialPaths=scanConfidentialKeys(payload);const artifacts=Array.isArray(payload.artifactHistory)?payload.artifactHistory:Array.isArray(payload.sourceArtifacts)?payload.sourceArtifacts:[];const artifactErrors=artifacts.map((row,index)=>({index,...validateArtifact(row)})).filter(x=>!x.valid);return{accepted:confidentialPaths.length===0&&artifactErrors.length===0,confidentialPaths,artifactErrors,automaticSynchronization:false};}
module.exports={CURRENT_RELEASE,CURRENT_SMARTER_JUSTICE_ARTIFACT,ALLOWED_PORTAL_IDS,OUT_OF_SCOPE_IDS,validateArtifact,scanConfidentialKeys,buildControls,validateImport};
