const crypto = require('crypto');
const store = require('./store');
const { NYC_FIELD_LAUNCH_STANDARD_VERSION, NYC_FIELD_LAUNCH_LOCATIONS, NYC_FIELD_LAUNCH_ASSETS, FIELD_ASSET_TYPES, FIELD_ASSET_STATUSES, FIELD_EVENT_TYPES, FIELD_CHANNELS, FIELD_LANES } = require('../data/nycFieldLaunchSeed');

const STORE_KEY='fieldLaunchProgram.json';
const CAMPAIGN_STATUSES=['draft','planning','permission review','ready for controlled use','active','paused','closed','cancelled'];
const LOCATION_STATUSES=['planning','permission review','approved for controlled use','active','paused','closed'];
const CONTROL_STATUSES=['planning','paused','controlled field pilot','active','closed'];

function clean(value,max=4000){return String(value==null?'':value).trim().slice(0,max);}
function oneOf(value,allowed,fallback){return allowed.includes(value)?value:fallback;}
function list(value,max=100,maxLength=500){const src=Array.isArray(value)?value:String(value||'').split(/\r?\n|,/);return [...new Set(src.map(x=>clean(x,maxLength)).filter(Boolean))].slice(0,max);}
function clone(value){return JSON.parse(JSON.stringify(value));}
function hash(value){return value?crypto.createHash('sha256').update(String(value)).digest('hex').slice(0,24):'';}
function initialCampaigns(){return NYC_FIELD_LAUNCH_LOCATIONS.flatMap(location=>[
  {id:`FIELD-${location.id}-PUBLIC`,name:`${location.area} public starting-help campaign`,campaignCode:location.publicCampaignCode,locationId:location.id,lane:'public',channel:'kiosk',status:'planning',publicEntryPath:'/kiosk.html',professionalEntryPath:'/professional-membership.html',portalSlugs:[],staffCodes:[],notes:'Public acquisition campaign. Do not collect confidential oral facts in public.',createdAt:'2026-07-20T00:00:00.000Z',updatedAt:''},
  {id:`FIELD-${location.id}-PRO`,name:`${location.area} professional founding-member campaign`,campaignCode:location.professionalCampaignCode,locationId:location.id,lane:'professional',channel:'kiosk',status:'planning',publicEntryPath:'/kiosk.html',professionalEntryPath:'/professional-membership.html',portalSlugs:[],staffCodes:[],notes:'Professional enrollment campaign. No guaranteed leads, clients, revenue, or ranking.',createdAt:'2026-07-20T00:00:00.000Z',updatedAt:''}
]);}
function initialState(){return {schemaVersion:'1.0.0',standardVersion:NYC_FIELD_LAUNCH_STANDARD_VERSION,controls:{status:'planning',publicLaneEnabled:false,professionalLaneEnabled:false,confidentialOralIntakeAllowed:false,staffLegalAdviceAllowed:false,courtAffiliationClaimAllowed:false,requireLocationPermissionEvidence:true,requireOwnerActivation:true,notes:'Do not activate a location until permits, property permission, courthouse restrictions, insurance, staffing, scripts, and owner approval are verified.',updatedAt:''},locations:clone(NYC_FIELD_LAUNCH_LOCATIONS),campaigns:initialCampaigns(),assets:clone(NYC_FIELD_LAUNCH_ASSETS),staff:[],events:[],dailyReports:[],updatedAt:'',stateRevision:0};}
function normalize(raw){const base=raw&&typeof raw==='object'&&!Array.isArray(raw)?raw:{};const defaults=initialState();const baseLocations=Array.isArray(base.locations)?base.locations:[];const baseCampaigns=Array.isArray(base.campaigns)?base.campaigns:[];const baseAssets=Array.isArray(base.assets)?base.assets:[];const locById=new Map(baseLocations.map(x=>[x.id,x]));const campById=new Map(baseCampaigns.map(x=>[x.id,x]));const assetById=new Map(baseAssets.map(x=>[x.id,x]));return {...defaults,...base,standardVersion:NYC_FIELD_LAUNCH_STANDARD_VERSION,controls:{...defaults.controls,...(base.controls||{})},locations:defaults.locations.map(x=>({...x,...(locById.get(x.id)||{})})).concat(baseLocations.filter(x=>!defaults.locations.some(d=>d.id===x.id))),campaigns:defaults.campaigns.map(x=>({...x,...(campById.get(x.id)||{})})).concat(baseCampaigns.filter(x=>!defaults.campaigns.some(d=>d.id===x.id))),assets:defaults.assets.map(x=>({...x,...(assetById.get(x.id)||{})})).concat(baseAssets.filter(x=>!defaults.assets.some(d=>d.id===x.id))),staff:Array.isArray(base.staff)?base.staff:[],events:Array.isArray(base.events)?base.events:[],dailyReports:Array.isArray(base.dailyReports)?base.dailyReports:[],stateRevision:Number.isFinite(Number(base.stateRevision))?Number(base.stateRevision):0};}
function readState(){return normalize(store.readJson(STORE_KEY,initialState()));}
function stamp(state){state.schemaVersion='1.0.0';state.standardVersion=NYC_FIELD_LAUNCH_STANDARD_VERSION;state.updatedAt=store.now();state.stateRevision=(Number(state.stateRevision)||0)+1;return state;}
async function mutate(mutator,eventFactory){const tx=await store.mutateJson(STORE_KEY,initialState(),async raw=>{const state=normalize(raw);const result=await mutator(state);return {value:stamp(state),result};},{event:(result,next)=>eventFactory?eventFactory(result,next):null});return tx.result;}
function summarize(state){const counts={};for(const type of FIELD_EVENT_TYPES)counts[type]=state.events.filter(x=>x.eventType===type).length;return {locations:state.locations.length,approvedLocations:state.locations.filter(x=>['approved for controlled use','active'].includes(x.status)).length,campaigns:state.campaigns.length,activeCampaigns:state.campaigns.filter(x=>x.status==='active').length,assets:state.assets.length,printReadyAssets:state.assets.filter(x=>['approved for print','printed','deployed'].includes(x.status)).length,staff:state.staff.filter(x=>x.status!=='inactive').length,events:state.events.length,publicEvents:state.events.filter(x=>x.lane==='public').length,professionalEvents:state.events.filter(x=>x.lane==='professional').length,counts};}
function safeCampaign(c,state){const location=state.locations.find(x=>x.id===c.locationId);return {id:c.id,name:c.name,campaignCode:c.campaignCode,locationId:c.locationId,locationName:location?.name||'',lane:c.lane,channel:c.channel,status:c.status,publicEntryPath:c.publicEntryPath,professionalEntryPath:c.professionalEntryPath,portalSlugs:c.portalSlugs||[],disclosures:['Smarter Justice is not a law firm or government agency.','No court or government affiliation.','No legal advice by outreach staff.','No guaranteed clients, matters, outcomes, or professional availability.']};}
function publicConfig(code=''){const state=readState();const campaign=state.campaigns.find(x=>x.campaignCode===clean(code,120))||state.campaigns[0];if(!campaign)return {available:false};const location=state.locations.find(x=>x.id===campaign.locationId);const active=state.controls.status==='active'||state.controls.status==='controlled field pilot';const laneEnabled=campaign.lane==='public'?state.controls.publicLaneEnabled:campaign.lane==='professional'?state.controls.professionalLaneEnabled:(state.controls.publicLaneEnabled||state.controls.professionalLaneEnabled);return {available:true,standardVersion:state.standardVersion,campaign:safeCampaign(campaign,state),location:{id:location?.id||'',name:location?.name||'',area:location?.area||'',borough:location?.borough||'',status:location?.status||'planning'},fieldProgramStatus:state.controls.status,laneEnabled:Boolean(active&&laneEnabled&&['ready for controlled use','active'].includes(campaign.status)),boundaries:['Use your own phone for private details whenever possible.','Do not say confidential facts aloud where others can hear.','Kiosk and outreach staff provide navigation, not legal or tax advice.','Smarter Justice is not affiliated with a court or government agency.']};}
async function recordEvent(input={}){const eventType=oneOf(input.eventType,FIELD_EVENT_TYPES,'');if(!eventType)return {error:'Unsupported field event type.'};const campaignCode=clean(input.campaignCode,120);return mutate(state=>{const campaign=state.campaigns.find(x=>x.campaignCode===campaignCode);if(!campaign)return {error:'Field campaign not found.'};const idempotencyHash=hash(input.idempotencyKey);if(idempotencyHash){const existing=state.events.find(x=>x.idempotencyHash===idempotencyHash);if(existing)return {event:clone(existing),idempotentReplay:true};}const event={id:store.uid('field',8),eventType,campaignCode,campaignId:campaign.id,locationId:campaign.locationId,lane:oneOf(input.lane,FIELD_LANES,campaign.lane),channel:oneOf(input.channel,FIELD_CHANNELS,campaign.channel),portalSlug:clean(input.portalSlug,180),staffCode:clean(input.staffCode,100),assetCode:clean(input.assetCode,120),idempotencyHash,occurredAt:clean(input.occurredAt,100)||store.now(),notes:clean(input.notes,1000)};state.events.unshift(event);state.events=state.events.slice(0,20000);return {event:clone(event),idempotentReplay:false};},result=>result?.event?{eventType:'field_launch_event_recorded',action:'field_launch_event_recorded',fieldEventId:result.event.id,fieldEventType:result.event.eventType,campaignCode:result.event.campaignCode}:null);}
async function updateControls(input={}){return mutate(state=>{const next={...state.controls};next.status=oneOf(input.status,CONTROL_STATUSES,next.status);for(const key of ['publicLaneEnabled','professionalLaneEnabled','confidentialOralIntakeAllowed','staffLegalAdviceAllowed','courtAffiliationClaimAllowed','requireLocationPermissionEvidence','requireOwnerActivation'])if(Object.prototype.hasOwnProperty.call(input,key))next[key]=Boolean(input[key]);if(Object.prototype.hasOwnProperty.call(input,'notes'))next.notes=clean(input.notes,5000);if(next.confidentialOralIntakeAllowed||next.staffLegalAdviceAllowed||next.courtAffiliationClaimAllowed)return {error:'Public field operations may not enable confidential oral intake, staff legal advice, or court/government affiliation claims.'};if(['controlled field pilot','active'].includes(next.status)&&next.requireOwnerActivation){const paidOps=store.readJson('paidPilotOperations.json',{})||{};const approvals=Array.isArray(paidOps.ownerApprovals)?paidOps.ownerApprovals:[];const approved=approvals.some(x=>x.approvalType==='nyc-field-launch'&&x.status==='approved');if(!approved)return {error:'Record an approved NYC field-launch owner decision before opening field operations.'};}next.updatedAt=store.now();state.controls=next;return {controls:clone(next)};},result=>result?.controls?{eventType:'field_launch_controls_updated',action:'field_launch_controls_updated',status:result.controls.status}:null);}
async function upsertLocation(input={}){return mutate(state=>{const id=clean(input.id,160)||`FIELD-LOCATION-${String(state.locations.length+1).padStart(3,'0')}`;let row=state.locations.find(x=>x.id===id);if(!row){row={id,name:'',borough:'',area:'',status:'planning',propertyPermissionStatus:'not verified',permitStatus:'not verified',courthouseRestrictionStatus:'not verified',insuranceStatus:'not verified',publicCampaignCode:'',professionalCampaignCode:'',publicSummary:'',boundaries:[],ownerNotes:'',updatedAt:''};state.locations.push(row);}for(const key of ['name','borough','area','propertyPermissionStatus','permitStatus','courthouseRestrictionStatus','insuranceStatus','publicCampaignCode','professionalCampaignCode','publicSummary','ownerNotes'])if(Object.prototype.hasOwnProperty.call(input,key))row[key]=clean(input[key],key==='publicSummary'||key==='ownerNotes'?5000:300);row.status=oneOf(input.status,LOCATION_STATUSES,row.status);if(Object.prototype.hasOwnProperty.call(input,'boundaries'))row.boundaries=list(input.boundaries,50,500);row.updatedAt=store.now();if(!row.name)return {error:'Location name is required.'};return {location:clone(row)};},result=>result?.location?{eventType:'field_launch_location_updated',action:'field_launch_location_updated',locationId:result.location.id,status:result.location.status}:null);}
async function upsertCampaign(input={}){return mutate(state=>{const id=clean(input.id,200)||`FIELD-CAMPAIGN-${String(state.campaigns.length+1).padStart(3,'0')}`;let row=state.campaigns.find(x=>x.id===id);if(!row){row={id,name:'',campaignCode:'',locationId:'',lane:'mixed',channel:'other',status:'draft',publicEntryPath:'/kiosk.html',professionalEntryPath:'/professional-membership.html',portalSlugs:[],staffCodes:[],notes:'',createdAt:store.now(),updatedAt:''};state.campaigns.push(row);}for(const key of ['name','campaignCode','locationId','publicEntryPath','professionalEntryPath','notes'])if(Object.prototype.hasOwnProperty.call(input,key))row[key]=clean(input[key],key==='notes'?5000:400);row.lane=oneOf(input.lane,FIELD_LANES,row.lane);row.channel=oneOf(input.channel,FIELD_CHANNELS,row.channel);row.status=oneOf(input.status,CAMPAIGN_STATUSES,row.status);if(Object.prototype.hasOwnProperty.call(input,'portalSlugs'))row.portalSlugs=list(input.portalSlugs,100,180);if(Object.prototype.hasOwnProperty.call(input,'staffCodes'))row.staffCodes=list(input.staffCodes,100,100);row.updatedAt=store.now();if(!row.name||!row.campaignCode||!row.locationId)return {error:'Campaign name, code, and location are required.'};const duplicate=state.campaigns.find(x=>x.id!==row.id&&x.campaignCode===row.campaignCode);if(duplicate)return {error:'Campaign code already exists.'};return {campaign:clone(row)};},result=>result?.campaign?{eventType:'field_launch_campaign_updated',action:'field_launch_campaign_updated',campaignId:result.campaign.id,status:result.campaign.status}:null);}

async function upsertAsset(input={}){return mutate(state=>{const id=clean(input.id,200)||`FIELD-ASSET-${String(state.assets.length+1).padStart(3,'0')}`;let row=state.assets.find(x=>x.id===id);if(!row){row={id,assetCode:'',name:'',assetType:'other',status:'idea',language:'',dimensions:'',primaryBrand:'Smarter Justice',legacyLine:'Connected with Justice Truck',publicCampaignCode:'',professionalCampaignCode:'',publicCopy:'',professionalCopy:'',complianceStatus:'',ownerNotes:'',updatedAt:''};state.assets.push(row);}for(const key of ['assetCode','name','language','dimensions','primaryBrand','legacyLine','publicCampaignCode','professionalCampaignCode','publicCopy','professionalCopy','complianceStatus','ownerNotes'])if(Object.prototype.hasOwnProperty.call(input,key))row[key]=clean(input[key],['publicCopy','professionalCopy','complianceStatus','ownerNotes'].includes(key)?5000:500);row.assetType=oneOf(input.assetType,FIELD_ASSET_TYPES,row.assetType);row.status=oneOf(input.status,FIELD_ASSET_STATUSES,row.status);row.updatedAt=store.now();if(!row.name||!row.assetCode)return {error:'Asset name and asset code are required.'};const duplicate=state.assets.find(x=>x.id!==row.id&&x.assetCode===row.assetCode);if(duplicate)return {error:'Asset code already exists.'};return {asset:clone(row)};},result=>result?.asset?{eventType:'field_launch_asset_updated',action:'field_launch_asset_updated',assetId:result.asset.id,assetCode:result.asset.assetCode,status:result.asset.status}:null);}

async function upsertStaff(input={}){return mutate(state=>{const code=clean(input.staffCode,100).toUpperCase().replace(/[^A-Z0-9-]/g,'');if(!code)return {error:'Staff code is required.'};let row=state.staff.find(x=>x.staffCode===code);if(!row){row={id:store.uid('fieldstaff',6),staffCode:code,displayName:'',role:'field navigator',status:'training',allowedLanes:['public','professional'],trainingCompletedAt:'',acknowledgments:[],notes:'',updatedAt:''};state.staff.push(row);}for(const key of ['displayName','role','status','trainingCompletedAt','notes'])if(Object.prototype.hasOwnProperty.call(input,key))row[key]=clean(input[key],key==='notes'?5000:300);if(Object.prototype.hasOwnProperty.call(input,'allowedLanes'))row.allowedLanes=list(input.allowedLanes,3,50).filter(x=>FIELD_LANES.includes(x));if(Object.prototype.hasOwnProperty.call(input,'acknowledgments'))row.acknowledgments=list(input.acknowledgments,50,500);row.updatedAt=store.now();return {staff:clone(row)};},result=>result?.staff?{eventType:'field_launch_staff_updated',action:'field_launch_staff_updated',staffCode:result.staff.staffCode,status:result.staff.status}:null);}
async function recordDailyReport(input={}){return mutate(state=>{const report={id:store.uid('fieldreport',7),date:clean(input.date,20)||new Date().toISOString().slice(0,10),locationId:clean(input.locationId,160),campaignCodes:list(input.campaignCodes,50,120),staffCodes:list(input.staffCodes,50,100),flyersDistributed:Math.max(0,Number(input.flyersDistributed)||0),publicConversations:Math.max(0,Number(input.publicConversations)||0),professionalConversations:Math.max(0,Number(input.professionalConversations)||0),officeVisits:Math.max(0,Number(input.officeVisits)||0),followUpsDue:Math.max(0,Number(input.followUpsDue)||0),notes:clean(input.notes,5000),createdAt:store.now()};state.dailyReports.unshift(report);state.dailyReports=state.dailyReports.slice(0,2000);return {report:clone(report)};},result=>result?.report?{eventType:'field_launch_daily_report_recorded',action:'field_launch_daily_report_recorded',reportId:result.report.id,date:result.report.date}:null);}
function ownerView(){const state=readState();return {...state,summary:summarize(state),enums:{campaignStatuses:CAMPAIGN_STATUSES,locationStatuses:LOCATION_STATUSES,controlStatuses:CONTROL_STATUSES,assetTypes:FIELD_ASSET_TYPES,assetStatuses:FIELD_ASSET_STATUSES,eventTypes:FIELD_EVENT_TYPES,channels:FIELD_CHANNELS,lanes:FIELD_LANES}};}
function exportMarkdown(){const data=ownerView();const lines=[`# Smarter Justice NYC Field Launch Program`,``,`Standard version: ${data.standardVersion}`,`Program status: ${data.controls.status}`,``,`## Non-negotiable boundaries`,`- No legal or tax advice by kiosk or outreach staff.`,`- No confidential oral intake in public.`,`- No claim of court or government affiliation.`,`- No guaranteed leads, clients, professional availability, or outcomes.`,``,`## Locations`,...data.locations.map(x=>`- **${x.name}** — ${x.status}; permission: ${x.propertyPermissionStatus}; permit: ${x.permitStatus}; courthouse restrictions: ${x.courthouseRestrictionStatus}; insurance: ${x.insuranceStatus}`),``,`## Campaigns`,...data.campaigns.map(x=>`- **${x.name}** (${x.campaignCode}) — ${x.status}; ${x.lane}; ${x.channel}`),``,`## Physical and outreach assets`,...data.assets.map(x=>`- **${x.name}** (${x.assetCode}) — ${x.assetType}; ${x.status}; dimensions: ${x.dimensions||'pending'}`),``,`## Totals`,`- Events: ${data.summary.events}`,`- Public events: ${data.summary.publicEvents}`,`- Professional events: ${data.summary.professionalEvents}`,`- Daily reports: ${data.dailyReports.length}`];return lines.join('\n');}
module.exports={STORE_KEY,NYC_FIELD_LAUNCH_STANDARD_VERSION,CAMPAIGN_STATUSES,LOCATION_STATUSES,CONTROL_STATUSES,readState,publicConfig,recordEvent,updateControls,upsertLocation,upsertCampaign,upsertAsset,upsertStaff,recordDailyReport,ownerView,exportMarkdown};
