'use strict';
const canonical=require('../data/initialPortalAuthorityV1775');
const receipt=require('../INITIAL_PORTAL_CURRENTNESS_RECEIPT_V1.7.75.json');
const previous=require('../INITIAL_PORTAL_CURRENTNESS_RECEIPT_V1.7.66.json');
function clone(v){return JSON.parse(JSON.stringify(v));}
function parts(v){return String(v||'').split('.').map(x=>Number(x)||0);}
function compare(a,b){const aa=parts(a),bb=parts(b);for(let i=0;i<Math.max(aa.length,bb.length);i++){const d=(aa[i]||0)-(bb[i]||0);if(d)return d;}return 0;}
function index(rows){return new Map((rows||[]).map(x=>[x.portalId,x]));}
function validate(){const errors=[];const current=index(canonical.portals),emitted=index(receipt.portals),prior=index(previous.portals);if(current.size!==4)errors.push(`canonical-count:${current.size}`);if(emitted.size!==4)errors.push(`receipt-count:${emitted.size}`);const orders=new Set();for(const [id,row] of current){const out=emitted.get(id),old=prior.get(id);if(orders.has(row.order))errors.push(`${id}:duplicate-order:${row.order}`);orders.add(row.order);if(!out){errors.push(`${id}:receipt-missing`);continue;}for(const field of ['version','artifactFilename','ownerRecordedSha256','ownerRecordedSizeBytes','identityCompleteness','evidenceState','independentlyVerifiedInThisBuild','supersededOwnerRecordedVersion'])if(out[field]!==row[field])errors.push(`${id}:receipt:${field}`);if(row.artifactFilename!==`${id}-v${row.version}.zip`)errors.push(`${id}:filename-version`);if(row.identityCompleteness==='VERSION_FILENAME_SHA_SIZE'){if(!/^[a-f0-9]{64}$/.test(row.ownerRecordedSha256||''))errors.push(`${id}:sha256`);if(!(row.ownerRecordedSizeBytes>0))errors.push(`${id}:size`);if(row.evidenceState!=='OWNER_RECORDED')errors.push(`${id}:full-identity-state`);}else if(row.identityCompleteness==='VERSION_AND_FILENAME_ONLY'){if(row.ownerRecordedSha256!==null||row.ownerRecordedSizeBytes!==null)errors.push(`${id}:partial-identity-values`);if(row.evidenceState!=='OWNER_RECORDED_VERSION_ONLY')errors.push(`${id}:partial-identity-state`);}else errors.push(`${id}:identity-completeness`);if(row.independentlyVerifiedInThisBuild!==false)errors.push(`${id}:inspection-boundary`);if(old&&compare(row.version,old.version)<0)errors.push(`${id}:version-regressed:${row.version}<${old.version}`);if(old&&compare(row.version,old.version)>0&&row.supersededOwnerRecordedVersion!==old.version)errors.push(`${id}:supersession-receipt`);if(old&&compare(row.version,old.version)===0&&row.supersededOwnerRecordedVersion!==row.version)errors.push(`${id}:unchanged-version-receipt`);}return{ok:errors.length===0,status:errors.length?'CONFLICT':'CURRENT_RUNTIME_AUTHORITY',errors,portalCount:current.size,releaseVersion:canonical.releaseVersion,advancedCount:[...current].filter(([id,row])=>prior.get(id)&&compare(row.version,prior.get(id).version)>0).length,unchangedCount:[...current].filter(([id,row])=>prior.get(id)&&compare(row.version,prior.get(id).version)===0).length,completeIdentityCount:[...current.values()].filter(x=>x.identityCompleteness==='VERSION_FILENAME_SHA_SIZE').length,versionOnlyCount:[...current.values()].filter(x=>x.identityCompleteness==='VERSION_AND_FILENAME_ONLY').length};}
function ownerView(){const prior=index(previous.portals);return{...clone(canonical),changes:canonical.portals.map(row=>({portalId:row.portalId,priorVersion:prior.get(row.portalId)?.version||null,currentVersion:row.version,change:prior.has(row.portalId)?(compare(row.version,prior.get(row.portalId).version)>0?'ADVANCED':compare(row.version,prior.get(row.portalId).version)===0?'UNCHANGED':'REGRESSED'):'NEW'})),validation:validate()};}
function artifactFor(portalId){const row=canonical.portals.find(x=>x.portalId===portalId);if(!row)throw new Error(`Unknown initial portal: ${portalId}`);return Object.freeze({version:row.version,filename:row.artifactFilename,sha256:row.ownerRecordedSha256,sizeBytes:row.ownerRecordedSizeBytes,evidenceState:row.evidenceState,identityCompleteness:row.identityCompleteness});}
module.exports={compare,validate,ownerView,artifactFor};
