'use strict';
const store = require('./store');
const professionalMarketplace = require('./professionalMarketplace');
const { TARGET_RELEASE_VERSION, listFourPortalLaunch } = require('../data/fourPortalLaunchV1751');

const STORE_KEY = 'launchCohortOperations.json';
const STANDARD_VERSION = '1.0.0';
const PORTALS = Object.freeze(listFourPortalLaunch().map(item=>Object.freeze({id:item.portalId,name:item.name,safetyCritical:item.safetyCritical===true})));
const CONTACT_STATUSES = Object.freeze(['identified','invite-ready','invited','interest-received','account-started','claim-started','claim-submitted','profile-draft','verification-pending','portal-review','staging-ready','support-needed','follow-up','declined','do-not-contact']);
const COHORT_STATUSES = Object.freeze(['draft','rehearsal','ready','active','paused','completed','archived']);
const SOURCE_AUTHORITY_LEVELS = Object.freeze(['primary','government','bar-or-court','professional-supplied','secondary','other']);
const SOURCE_REVIEW_STATUSES = Object.freeze(['pending-review','approved-source','limited-use','rejected','terms-review-needed']);
const MAX_CONTACTS = 5000;
const MAX_BATCH_ROWS = 500;

function clean(value,max=500){return String(value??'').trim().slice(0,max);}
function list(value,maxItems=50,maxLength=300){const src=Array.isArray(value)?value:String(value||'').split(/\r?\n|,/);return [...new Set(src.map(x=>clean(x,maxLength)).filter(Boolean))].slice(0,maxItems);}
function oneOf(value,allowed,fallback){const v=clean(value,100);return allowed.includes(v)?v:fallback;}
function bool(value){return value===true||/^(1|true|yes|on)$/i.test(String(value||''));}
function int(value,fallback=0,min=0,max=10000){const n=Number(value);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.round(n))):fallback;}
function email(value){const v=clean(value,220);return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)?v:'';}
function safeUrl(value){const v=clean(value,1500);if(!v)return'';try{const u=new URL(v);return ['https:','http:'].includes(u.protocol)?u.toString():'';}catch{return'';}}
function iso(value){const v=clean(value,100);if(!v)return'';const t=Date.parse(v);return Number.isNaN(t)?'':new Date(t).toISOString();}
function code(value){return clean(value,80).toUpperCase().replace(/[^A-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,80);}
function portalIds(value){return list(value,4,80).filter(v=>PORTALS.some(p=>p.id===v));}
function normalized(value){return clean(value,1000).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');}
function maskEmail(value){const v=email(value);if(!v)return'';const [a,d]=v.split('@');return `${a.slice(0,2)}${a.length>2?'***':''}@${d}`;}
function clone(value){return JSON.parse(JSON.stringify(value));}

function defaultState(){return{
  schemaVersion:'1.0.0',standardVersion:STANDARD_VERSION,releaseVersion:TARGET_RELEASE_VERSION,
  cohort:{id:'initial-nyc-attorney-cohort',name:'Initial NYC Attorney Profile Cohort',campaignCode:'ATTORNEY-LAUNCH-NYC',status:'draft',capacity:25,owner:'Roger',supportOwner:'',portalIds:PORTALS.map(x=>x.id),channels:['in-person building outreach','QR code','email follow-up'],freeBasicProfileOnly:true,paidGrowthOpen:false,publicUserMatterDataAllowed:false,notes:'Launch attorneys through free basic profile control first. Domestic Violence Aid participation requires specialty and survivor-safety review. Paid growth remains separately gated.',updatedAt:''},
  contacts:[],batches:[],updatedAt:''
};}
function normalizeState(raw){const base={...defaultState(),...(raw||{})};base.cohort={...defaultState().cohort,...(raw?.cohort||{})};base.cohort.portalIds=portalIds(base.cohort.portalIds);if(!base.cohort.portalIds.length)base.cohort.portalIds=PORTALS.map(x=>x.id);base.contacts=Array.isArray(raw?.contacts)?raw.contacts.slice(0,MAX_CONTACTS):[];base.batches=Array.isArray(raw?.batches)?raw.batches:[];return base;}
function readState(){return normalizeState(store.readJson(STORE_KEY,defaultState()));}
function writeState(state){state.updatedAt=store.now();store.writeJson(STORE_KEY,state);return state;}

function parseCsv(text){
  const rows=[];let row=[];let field='';let quoted=false;const input=String(text||'').replace(/^\uFEFF/,'');
  for(let i=0;i<input.length;i++){const c=input[i];if(quoted){if(c==='"'&&input[i+1]==='"'){field+='"';i++;}else if(c==='"')quoted=false;else field+=c;}else if(c==='"')quoted=true;else if(c===','){row.push(field);field='';}else if(c==='\n'){row.push(field);rows.push(row);row=[];field='';}else if(c!=='\r')field+=c;}
  if(field||row.length){row.push(field);rows.push(row);}if(rows.length<2)return[];
  const headers=rows.shift().map(h=>normalized(h).replace(/ /g,''));
  return rows.filter(r=>r.some(x=>clean(x))).slice(0,MAX_BATCH_ROWS).map(r=>Object.fromEntries(headers.map((h,i)=>[h,clean(r[i]||'',2000)])));
}
function normalizeRowKeys(row){const out={};for(const [key,value] of Object.entries(row&&typeof row==='object'?row:{}))out[normalized(key).replace(/ /g,'')]=value;return out;}
function pick(row,...keys){for(const key of keys){if(row&&row[key]!=null&&clean(row[key]))return clean(row[key],2000);}return'';}
function inferPortals(practiceAreas){
  const text=normalized((practiceAreas||[]).join(' '));const out=[];
  if(/\b(divorce|family law|custody|matrimonial|child support|parenting|separation|spousal support)\b/.test(text))out.push('divorce-law-aid');
  if(/\b(estate|probate|trust|will|guardianship|surrogate|elder law|estate administration)\b/.test(text))out.push('estate-law-aid');
  if(!/\b(workers compensation|worker compensation|medical malpractice)\b/.test(text)&&/\b(personal injury|accident|negligence|premises|slip and fall|wrongful death|product liability|motor vehicle|car accident|truck accident|pedestrian|bicycle|rideshare)\b/.test(text))out.push('personal-injury-law-aid');
  if(/\b(domestic violence|family offense|order of protection|restraining order|intimate partner violence|victim rights|survivor representation|stalking|coercive control)\b/.test(text))out.push('domestic-violence-aid');
  return [...new Set(out)];
}
function existingIndex(){const data=professionalMarketplace.getOwnerData();const byRegistration=new Map();const byNameOffice=new Map();for(const p of data.professionals||[]){const reg=normalized(p.publicFacts?.registrationNumber||p.credentials?.[0]?.identifier||'');if(reg)byRegistration.set(reg,p.id);const key=`${normalized(p.displayName)}|${normalized((p.officeLocations||[])[0]||'')}`;if(key!=='|')byNameOffice.set(key,p.id);}return{byRegistration,byNameOffice};}
function sourceRecord(source,row,index){return{id:`launch-source-${store.uid('row',6)}`,sourceType:clean(source.sourceType||'public professional directory',180),sourceName:clean(source.sourceName,240),sourceUrl:safeUrl(source.sourceUrl),authorityLevel:oneOf(source.authorityLevel,SOURCE_AUTHORITY_LEVELS,'other')==='government'?'primary':oneOf(source.authorityLevel,SOURCE_AUTHORITY_LEVELS,'other')==='bar-or-court'?'primary':oneOf(source.authorityLevel,SOURCE_AUTHORITY_LEVELS,'other'),reviewStatus:source.reviewStatus==='approved-source'?'approved source':source.reviewStatus==='limited-use'?'limited-use source':source.reviewStatus==='terms-review-needed'?'terms review needed':'pending review',retrievedAt:iso(source.retrievedAt)||store.now(),factsSupported:list(source.factsSupported,30,180),externalSourceId:pick(row,'externalsourceid','sourceid','registrationnumber','registration','barnumber')||`batch-row-${index+1}`,publisher:clean(source.publisher||source.sourceName,240),termsOrUseNotes:clean(source.termsOrUseNotes,2000),notes:'Imported through the v1.7.53 owner-only profile-growth intake. No publication, verification, specialty approval, payment entitlement, or endorsement was created.'};}
function normalizeCandidate(row,source,index,idx){
  const displayName=pick(row,'displayname','name','attorneyname','professionalname','fullname');
  const registrationNumber=pick(row,'registrationnumber','registration','barnumber','attorneyregistrationnumber');
  const office=pick(row,'officeaddress','address','businessaddress','location');
  const practiceAreas=list(pick(row,'practiceareas','practicearea','practices'),30,180);
  const requested=portalIds(list(pick(row,'portalids','portals'),3,80));const suggested=requested.length?requested:inferPortals(practiceAreas);
  const errors=[];const warnings=[];
  if(displayName.length<2)errors.push('Professional name is required.');
  if(!registrationNumber)warnings.push('Registration or license identifier is missing.');
  if(!office)warnings.push('Public business office is missing.');
  if(!practiceAreas.length)warnings.push('Practice area needs review before portal assignment.');
  if(!safeUrl(source.sourceUrl))errors.push('A valid source URL is required for the batch.');
  if(!clean(source.sourceName))errors.push('A source name is required for the batch.');
  if(!list(source.factsSupported,30,180).length)errors.push('Facts supported by the source must be listed.');
  const regKey=normalized(registrationNumber);const key=`${normalized(displayName)}|${normalized(office)}`;let duplicateProfessionalId='';if(regKey&&idx.byRegistration.has(regKey))duplicateProfessionalId=idx.byRegistration.get(regKey);else if(key!=='|'&&idx.byNameOffice.has(key))duplicateProfessionalId=idx.byNameOffice.get(key);
  const status=errors.length?'invalid':duplicateProfessionalId?'duplicate':warnings.length?'needs-review':'ready';
  return{id:store.uid('candidate',9),rowNumber:index+2,status,displayName,registrationNumber,firmName:pick(row,'firmname','firm','company'),officeAddress:office,businessEmail:email(pick(row,'businessemail','email')),phone:pick(row,'phone','telephone'),website:safeUrl(pick(row,'website','url')),jurisdictions:list(pick(row,'jurisdictions','jurisdiction','state'),20,120),practiceAreas,languages:list(pick(row,'languages','language'),20,80),suggestedPortalIds:suggested,requestedPortalIds:requested,errors,warnings,duplicateProfessionalId,sourceRecord:sourceRecord(source,row,index)};
}
function previewBatch(input={},actor='owner'){
  const source={sourceName:clean(input.sourceName,240),sourceUrl:safeUrl(input.sourceUrl),sourceType:clean(input.sourceType||'public professional directory',180),authorityLevel:oneOf(input.authorityLevel,SOURCE_AUTHORITY_LEVELS,'other'),reviewStatus:oneOf(input.reviewStatus,SOURCE_REVIEW_STATUSES,'pending-review'),retrievedAt:iso(input.retrievedAt)||store.now(),publisher:clean(input.publisher,240),factsSupported:list(input.factsSupported,30,180),termsOrUseNotes:clean(input.termsOrUseNotes,2000)};
  let rows=Array.isArray(input.records)?input.records.slice(0,MAX_BATCH_ROWS).map(normalizeRowKeys):[];if(!rows.length&&clean(input.csvText,1000000))rows=parseCsv(input.csvText);
  if(!rows.length)return{error:'Add at least one structured record or CSV data row.'};
  const idx=existingIndex();const candidates=rows.map((row,i)=>normalizeCandidate(row,source,i,idx));
  const state=readState();const batch={id:store.uid('profile-batch',9),status:'previewed',source,rowCount:rows.length,readyCount:candidates.filter(x=>x.status==='ready').length,needsReviewCount:candidates.filter(x=>x.status==='needs-review').length,duplicateCount:candidates.filter(x=>x.status==='duplicate').length,invalidCount:candidates.filter(x=>x.status==='invalid').length,candidates,createdAt:store.now(),createdBy:clean(actor,100)||'owner',committedAt:'',createdProfessionalIds:[]};state.batches.unshift(batch);state.batches=state.batches.slice(0,50);writeState(state);store.addAudit({actor:'owner-control-center',action:'launch_profile_source_batch_previewed',details:{batchId:batch.id,rowCount:batch.rowCount,readyCount:batch.readyCount,needsReviewCount:batch.needsReviewCount,duplicateCount:batch.duplicateCount,invalidCount:batch.invalidCount}});return{batch:clone(batch)};
}
function commitBatch(batchId,actor='owner'){
  const state=readState();const batch=state.batches.find(x=>x.id===clean(batchId,180));if(!batch)return{error:'Profile intake batch was not found.'};if(batch.status==='committed')return{error:'This profile intake batch was already committed.'};
  const results={created:[],duplicates:[],errors:[]};for(const c of batch.candidates.filter(x=>x.status==='ready')){const source=c.sourceRecord;const input={displayName:c.displayName,professionalType:'attorney',seededFromPublicInfo:true,email:c.businessEmail,phone:c.phone,website:c.website,officeLocations:c.officeAddress?[c.officeAddress]:[],jurisdictions:c.jurisdictions.length?c.jurisdictions:['New York'],practiceAreas:c.practiceAreas,languages:c.languages,portalEligibility:[],membership:{planId:'basic-directory',status:'none',foundingRate:false,paymentState:'not configured'},credentials:c.registrationNumber?[{credentialType:'Attorney registration',jurisdiction:c.jurisdictions[0]||'New York',identifier:c.registrationNumber,status:'unverified',verificationSource:source.sourceUrl}]:[],publicFacts:{registrationNumber:c.registrationNumber,companyName:c.firmName,publicBusinessAddress:c.officeAddress,state:c.jurisdictions[0]||'New York'},sourceRecords:[source],sourceOrigin:'owner-approved-profile-source-batch',dataAuthority:'source-supported',ownerNotes:`Suggested portal review only: ${c.suggestedPortalIds.join(', ')||'none'}. Portal eligibility was not auto-approved.`};const created=professionalMarketplace.createProfessional(input,'launch-profile-growth-intake');if(created.error){(created.duplicateCredentialIdentifier||created.duplicateExternalSourceId?results.duplicates:results.errors).push({candidateId:c.id,displayName:c.displayName,error:created.error});}else results.created.push({candidateId:c.id,professionalId:created.professional.id,displayName:c.displayName,suggestedPortalIds:c.suggestedPortalIds});}
  batch.status='committed';batch.committedAt=store.now();batch.committedBy=clean(actor,100)||'owner';batch.createdProfessionalIds=results.created.map(x=>x.professionalId);batch.commitResults=results;writeState(state);store.addAudit({actor:'owner-control-center',action:'launch_profile_source_batch_committed',details:{batchId:batch.id,created:results.created.length,duplicates:results.duplicates.length,errors:results.errors.length,publicationActivated:false,portalEligibilityAutoApproved:false}});return{batch:clone(batch),results};
}
function publicInterest(input={},context={}){
  const state=readState();const name=clean(input.name||input.professionalName,180);const contactEmail=email(input.email);const phone=clean(input.phone,80);if(name.length<2)return{error:'Add your professional name.'};if(!contactEmail&&!phone)return{error:'Add an email address or phone number.'};if(!bool(input.consentToContact))return{error:'Consent to contact is required.'};
  const existingId=clean(context.existingContactId,180);let contact=existingId?state.contacts.find(x=>x.id===existingId):null;const reused=Boolean(contact);
  if(contact){contact.campaignCode=code(input.campaignCode||contact.campaignCode||state.cohort.campaignCode)||state.cohort.campaignCode;contact.status='interest-received';contact.professionalName=name;contact.firmName=clean(input.firmName||contact.firmName,240);contact.email=contactEmail||contact.email;contact.phone=phone||contact.phone;contact.registrationNumber=clean(input.registrationNumber||contact.registrationNumber,100);const selected=portalIds(input.portalIds||input.portals);if(selected.length)contact.portalIds=selected;contact.sourceChannel=clean(input.sourceChannel||contact.sourceChannel||'personalized invitation',120);contact.consentToContact=true;contact.nextAction='Send account or claim instructions and confirm the correct portal specialties.';contact.notes=clean(`${contact.notes||''} Personalized invitation response recorded. No legal matter information collected.`,4000);contact.updatedAt=store.now();contact.updatedBy='public-attorney-launch';}
  else{contact={id:store.uid('launch-contact',10),campaignCode:code(input.campaignCode||state.cohort.campaignCode)||state.cohort.campaignCode,status:'interest-received',professionalName:name,firmName:clean(input.firmName,240),email:contactEmail,phone,registrationNumber:clean(input.registrationNumber,100),portalIds:portalIds(input.portalIds||input.portals),sourceChannel:clean(input.sourceChannel||'website or QR signup',120),consentToContact:true,nextAction:'Send account or claim instructions and confirm the correct portal specialties.',nextFollowUpAt:'',supportNeed:'',notes:'Public attorney launch interest. No legal matter information collected.',createdAt:store.now(),updatedAt:store.now(),createdBy:'public-attorney-launch'};state.contacts.unshift(contact);state.contacts=state.contacts.slice(0,MAX_CONTACTS);}
  writeState(state);store.addAudit({actor:'attorney-launch-interest',action:'free_profile_launch_interest_recorded',details:{contactId:contact.id,campaignCode:contact.campaignCode,portalIds:contact.portalIds,existingInvitationContactReused:reused,paidGrowthActivated:false,profilePublished:false}});return{confirmationId:contact.id,reusedExistingContact:reused,contact:{id:contact.id,campaignCode:contact.campaignCode,status:contact.status,professionalName:contact.professionalName,email:maskEmail(contact.email),portalIds:contact.portalIds}};
}
function createContact(input={},actor='owner'){
  const result=publicInterest({...input,consentToContact:input.consentToContact!==false});if(result.error)return result;const state=readState();const contact=state.contacts.find(x=>x.id===result.confirmationId);contact.createdBy=clean(actor,100)||'owner';contact.status=oneOf(input.status,CONTACT_STATUSES,'identified');contact.nextAction=clean(input.nextAction,1200)||contact.nextAction;contact.nextFollowUpAt=iso(input.nextFollowUpAt);contact.supportNeed=clean(input.supportNeed,1000);contact.notes=clean(input.notes,4000)||contact.notes;writeState(state);return{contact:clone(contact)};
}
function updateContact(id,input={},actor='owner'){
  const state=readState();const contact=state.contacts.find(x=>x.id===clean(id,180));if(!contact)return null;for(const field of ['professionalName','firmName','phone','registrationNumber','nextAction','supportNeed','notes'])if(Object.prototype.hasOwnProperty.call(input,field))contact[field]=clean(input[field],field==='notes'?4000:1200);if(Object.prototype.hasOwnProperty.call(input,'email'))contact.email=email(input.email);if(Object.prototype.hasOwnProperty.call(input,'status'))contact.status=oneOf(input.status,CONTACT_STATUSES,contact.status);if(Object.prototype.hasOwnProperty.call(input,'portalIds'))contact.portalIds=portalIds(input.portalIds);if(Object.prototype.hasOwnProperty.call(input,'nextFollowUpAt'))contact.nextFollowUpAt=iso(input.nextFollowUpAt);contact.updatedAt=store.now();contact.updatedBy=clean(actor,100)||'owner';writeState(state);store.addAudit({actor:'owner-control-center',action:'launch_cohort_contact_updated',details:{contactId:contact.id,status:contact.status}});return{contact:clone(contact)};
}
function updateCohort(input={},actor='owner'){
  const state=readState();const c=state.cohort;for(const field of ['name','owner','supportOwner','notes'])if(Object.prototype.hasOwnProperty.call(input,field))c[field]=clean(input[field],field==='notes'?4000:240);if(Object.prototype.hasOwnProperty.call(input,'campaignCode'))c.campaignCode=code(input.campaignCode)||c.campaignCode;if(Object.prototype.hasOwnProperty.call(input,'status'))c.status=oneOf(input.status,COHORT_STATUSES,c.status);if(Object.prototype.hasOwnProperty.call(input,'capacity'))c.capacity=int(input.capacity,c.capacity,1,5000);if(Object.prototype.hasOwnProperty.call(input,'portalIds'))c.portalIds=portalIds(input.portalIds);c.freeBasicProfileOnly=true;c.paidGrowthOpen=false;c.publicUserMatterDataAllowed=false;c.updatedAt=store.now();writeState(state);store.addAudit({actor:'owner-control-center',action:'launch_cohort_plan_updated',details:{status:c.status,capacity:c.capacity,paidGrowthOpen:false}});return{cohort:clone(c)};
}
function summary(state=readState()){
  const now=Date.now();const active=state.contacts.filter(x=>!['declined','do-not-contact'].includes(x.status));const overdue=active.filter(x=>x.nextFollowUpAt&&Date.parse(x.nextFollowUpAt)<now);return{contacts:state.contacts.length,activeContacts:active.length,overdueFollowUps:overdue.length,supportNeeded:state.contacts.filter(x=>x.status==='support-needed'||x.supportNeed).length,interestReceived:state.contacts.filter(x=>x.status==='interest-received').length,stagingReady:state.contacts.filter(x=>x.status==='staging-ready').length,batches:state.batches.length,profileCandidates:state.batches.reduce((s,b)=>s+b.rowCount,0),profilesCreated:state.batches.reduce((s,b)=>s+(b.createdProfessionalIds||[]).length,0)};
}
function ownerView(){const state=readState();return{standardVersion:STANDARD_VERSION,releaseVersion:TARGET_RELEASE_VERSION,cohort:clone(state.cohort),contacts:clone(state.contacts),batches:clone(state.batches),summary:summary(state),portals:PORTALS,contactStatuses:CONTACT_STATUSES,cohortStatuses:COHORT_STATUSES,sourceAuthorityLevels:SOURCE_AUTHORITY_LEVELS,sourceReviewStatuses:SOURCE_REVIEW_STATUSES,boundaries:{freeBasicProfileFirst:true,paidGrowthOpen:false,autoPublication:false,autoVerification:false,autoPortalEligibility:false,publicUserMatterDataAllowed:false,statement:'This launch cohort records attorney outreach and source-supported profile candidates. It cannot verify credentials, approve specialties, publish profiles, activate payment, change organic ordering, or connect a portal.'}};}
function exportMarkdown(){const v=ownerView();const lines=['# Smarter Justice Initial Attorney Cohort Packet','',`Release: ${TARGET_RELEASE_VERSION}`,`Cohort: ${v.cohort.name}`,`Status: ${v.cohort.status}`,`Campaign: ${v.cohort.campaignCode}`,`Capacity: ${v.cohort.capacity}`,'','## Fail-closed boundary',v.boundaries.statement,'','## Cohort summary',...Object.entries(v.summary).map(([k,val])=>`- ${k}: ${val}`),'','## Contacts',...v.contacts.map(c=>`- ${c.professionalName} | ${c.firmName||'No firm recorded'} | ${c.status} | next: ${c.nextAction||'not set'} | follow-up: ${c.nextFollowUpAt||'not set'}`),'','## Profile source batches',...v.batches.map(b=>`- ${b.id} | ${b.status} | rows ${b.rowCount} | ready ${b.readyCount} | needs review ${b.needsReviewCount} | duplicates ${b.duplicateCount} | invalid ${b.invalidCount}`)];return lines.join('\n');}

module.exports={STANDARD_VERSION,TARGET_RELEASE_VERSION,PORTALS,CONTACT_STATUSES,COHORT_STATUSES,SOURCE_AUTHORITY_LEVELS,SOURCE_REVIEW_STATUSES,parseCsv,inferPortals,previewBatch,commitBatch,publicInterest,createContact,updateContact,updateCohort,ownerView,exportMarkdown};
