const store = require('./store');
const launchActivation = require('./launchActivation');
const serviceReadiness = require('./serviceReadiness');
const { TARGET_RELEASE_VERSION } = require('../data/fourPortalLaunchV1751');

const STORE_KEY='launchDayOperations.json';
const STANDARD_VERSION='1.0.0';
const SHIFT_STATUSES=Object.freeze(['planned','open','paused','closed']);
const JOURNEY_TYPES=Object.freeze(['public-start-to-portal','attorney-invitation-to-follow-up','profile-control-to-review','portal-projection-round-trip','support-request-to-resolution','incident-detection-to-communication','rollback-decision-to-restore','domestic-violence-safe-entry-to-resource-direction','domestic-violence-safety-suppression-to-restore','stop-sign-project-direct-doorway']);
const JOURNEY_STATUSES=Object.freeze(['planned','running','passed','failed','blocked']);
const SUPPORT_CATEGORIES=Object.freeze(['access','profile-control','portal-routing','technical','privacy','billing-closed','complaint','domestic-violence-safety','safe-contact','confidential-location','emergency-resource-currentness','stop-sign-project','other']);
const SUPPORT_PRIORITIES=Object.freeze(['routine','priority','urgent']);
const SUPPORT_STATUSES=Object.freeze(['new','acknowledged','working','waiting','resolved','closed']);
const PAUSE_TRIGGERS=Object.freeze(['readiness-red','critical-incident','privacy-concern','wrong-portal-routing','profile-trust-concern','support-overload','rollback-required','domestic-violence-safety-failure','confidential-location-exposure','unsafe-notification','stale-emergency-resource','stop-sign-project-breakage']);
function clean(v,max=500){return String(v??'').trim().slice(0,max)}
function list(v,maxItems=30,maxLength=500){const a=Array.isArray(v)?v:String(v||'').split(/\r?\n/);return a.map(x=>clean(x,maxLength)).filter(Boolean).slice(0,maxItems)}
function oneOf(v,a,f){const x=clean(v,80);return a.includes(x)?x:f}
function bool(v){return v===true||/^(1|true|yes|on)$/i.test(String(v||''))}
function defaultState(){return{schemaVersion:'1.0.0',standardVersion:STANDARD_VERSION,releaseVersion:TARGET_RELEASE_VERSION,shifts:[],journeys:[],support:[],updatedAt:''}}
function state(){const raw=store.readJson(STORE_KEY,defaultState());return{...defaultState(),...(raw||{}),shifts:Array.isArray(raw?.shifts)?raw.shifts:[],journeys:Array.isArray(raw?.journeys)?raw.journeys:[],support:Array.isArray(raw?.support)?raw.support:[]}}
function save(s){s.updatedAt=store.now();store.writeJson(STORE_KEY,s);return s}
function createShift(input,actor='owner-control-center'){
 const s=state(); const name=clean(input.name,240)||`Launch shift ${new Date().toISOString().slice(0,10)}`;
 const item={id:store.uid('launch_shift',8),name,status:oneOf(input.status,SHIFT_STATUSES,'planned'),owner:clean(input.owner,180),supportOwner:clean(input.supportOwner,180),incidentOwner:clean(input.incidentOwner,180),startsAt:clean(input.startsAt,80),endsAt:clean(input.endsAt,80),supportTargetMinutes:Math.max(5,Math.min(1440,Number(input.supportTargetMinutes)||60)),capacityCap:Math.max(1,Math.min(5000,Number(input.capacityCap)||25)),pauseTriggers:list(input.pauseTriggers,PAUSE_TRIGGERS.length,80).filter(x=>PAUSE_TRIGGERS.includes(x)),openingChecklist:list(input.openingChecklist,30,500),closingChecklist:list(input.closingChecklist,30,500),notes:clean(input.notes,5000),createdAt:store.now(),updatedAt:store.now()};
 if(!item.pauseTriggers.length)item.pauseTriggers=['readiness-red','critical-incident','privacy-concern','wrong-portal-routing','profile-trust-concern','support-overload'];
 s.shifts.unshift(item);save(s);store.addAudit({actor,action:'launch_day_shift_created',details:{id:item.id,status:item.status}});return{shift:item};
}
function recordJourney(input,actor='owner-control-center'){
 const s=state();const type=oneOf(input.type,JOURNEY_TYPES,'public-start-to-portal');
 const item={id:store.uid('launch_journey',8),type,status:oneOf(input.status,JOURNEY_STATUSES,'planned'),title:clean(input.title,240)||type,shiftId:clean(input.shiftId,120),operator:clean(input.operator,180),device:clean(input.device,180),startedAt:clean(input.startedAt,80),completedAt:clean(input.completedAt,80),steps:list(input.steps,40,500),evidence:list(input.evidence,30,1000),findings:list(input.findings,30,1000),containsRealUserData:false,notes:clean(input.notes,5000),createdAt:store.now()};
 s.journeys.unshift(item);save(s);store.addAudit({actor,action:'launch_day_journey_recorded',details:{id:item.id,type,status:item.status}});return{journey:item};
}
function recordSupport(input,actor='owner-control-center'){
 const s=state();const summary=clean(input.summary,500);if(!summary)return{error:'Add a short operational summary without legal facts.'};
 const item={id:store.uid('launch_support',8),shiftId:clean(input.shiftId,120),category:oneOf(input.category,SUPPORT_CATEGORIES,'other'),priority:oneOf(input.priority,SUPPORT_PRIORITIES,'routine'),status:oneOf(input.status,SUPPORT_STATUSES,'new'),channel:clean(input.channel,80),owner:clean(input.owner,180),summary,requestedAt:clean(input.requestedAt,80)||store.now(),acknowledgedAt:clean(input.acknowledgedAt,80),resolvedAt:clean(input.resolvedAt,80),nextAction:clean(input.nextAction,1000),resolution:clean(input.resolution,2000),pauseTrigger:bool(input.pauseTrigger),containsLegalNarrative:false,containsSensitiveDocuments:false,containsSurvivorNarrative:false,containsSafeContactChoice:false,containsConfidentialLocation:false,createdAt:store.now(),updatedAt:store.now()};
 s.support.unshift(item);save(s);store.addAudit({actor,action:'launch_day_support_recorded',details:{id:item.id,category:item.category,priority:item.priority,pauseTrigger:item.pauseTrigger}});return{support:item};
}
function minutesBetween(a,b){const x=Date.parse(a),y=Date.parse(b);return Number.isFinite(x)&&Number.isFinite(y)?Math.max(0,Math.round((y-x)/60000)):null}
function ownerView(){
 const s=state();const activation=launchActivation.ownerView();const readiness=serviceReadiness.ownerDiagnostics();
 const openShift=s.shifts.find(x=>x.status==='open')||null;const unresolved=s.support.filter(x=>!['resolved','closed'].includes(x.status));const urgent=unresolved.filter(x=>x.priority==='urgent');
 const passed=new Set(s.journeys.filter(x=>x.status==='passed').map(x=>x.type));const missing=JOURNEY_TYPES.filter(x=>!passed.has(x));
 const target=openShift?.supportTargetMinutes||60;const overdue=unresolved.filter(x=>{const age=minutesBetween(x.requestedAt,store.now());return age!==null&&age>target});
 const pauseReasons=[];if(readiness.selected?.lane?.ready!==true)pauseReasons.push('Selected launch lane is not ready.');if(urgent.length)pauseReasons.push(`${urgent.length} urgent support item(s) remain unresolved.`);if(unresolved.some(x=>x.pauseTrigger))pauseReasons.push('A support item is marked as a pause trigger.');if(activation.summary?.criticalIssues)pauseReasons.push(`${activation.summary.criticalIssues} critical launch issue(s) remain open.`);
 return{standardVersion:STANDARD_VERSION,releaseVersion:TARGET_RELEASE_VERSION,generatedAt:store.now(),shifts:s.shifts,journeys:s.journeys,support:s.support,openShift,summary:{shifts:s.shifts.length,openShifts:s.shifts.filter(x=>x.status==='open').length,journeys:s.journeys.length,passedJourneys:s.journeys.filter(x=>x.status==='passed').length,missingJourneyTypes:missing.length,supportItems:s.support.length,unresolvedSupport:unresolved.length,urgentSupport:urgent.length,overdueSupport:overdue.length,pauseReasons:pauseReasons.length},journeyCoverage:{requiredTypes:JOURNEY_TYPES,passedTypes:[...passed],missingTypes:missing},pauseDecision:{recommended:pauseReasons.length>0,reasons:pauseReasons,authoritative:false},readiness:{lane:readiness.selected?.lane||{},overallStatus:readiness.selected?.lane?.status||'blocked'},activation:{overallStatus:activation.launchCommand?.overallStatus||'NO_GO',p0Blockers:activation.summary?.p0Blockers||0,criticalIssues:activation.summary?.criticalIssues||0},privacyBoundary:{statement:'Record operational categories and short summaries only. Do not enter client stories, legal facts, confidential documents, passwords, payment data, or attorney-client communications.',excluded:['Legal narratives','Intake answers','Documents','Passwords','Payment credentials','IP addresses','Device fingerprints','Survivor narratives','Safe-contact choices','Confidential shelter or service locations']},activationBoundary:{canLaunch:false,reason:'This workbench coordinates a launch shift and recommends pauses. It cannot change readiness checks, approve launch, publish profiles, connect portals, activate payment, or deploy.'},enums:{shiftStatuses:SHIFT_STATUSES,journeyTypes:JOURNEY_TYPES,journeyStatuses:JOURNEY_STATUSES,supportCategories:SUPPORT_CATEGORIES,supportPriorities:SUPPORT_PRIORITIES,supportStatuses:SUPPORT_STATUSES,pauseTriggers:PAUSE_TRIGGERS}};
}
function exportMarkdown(){const v=ownerView();return [`# Smarter Justice Launch-Day Operations Snapshot`,``,`Release: ${v.releaseVersion}`,`Generated: ${v.generatedAt}`,`Readiness: ${v.readiness.overallStatus}`,`Pause recommended: ${v.pauseDecision.recommended?'YES':'NO'}`,``,`## Pause reasons`,...(v.pauseDecision.reasons.length?v.pauseDecision.reasons.map(x=>`- ${x}`):['- None recorded']),``,`## Journey coverage`,`- Passed: ${v.journeyCoverage.passedTypes.length}/${v.journeyCoverage.requiredTypes.length}`, ...v.journeyCoverage.missingTypes.map(x=>`- Missing: ${x}`),``,`## Support`,`- Unresolved: ${v.summary.unresolvedSupport}`,`- Urgent: ${v.summary.urgentSupport}`,`- Overdue: ${v.summary.overdueSupport}`,``,`## Boundary`,v.activationBoundary.reason].join('\n')}
module.exports={STORE_KEY,STANDARD_VERSION,TARGET_RELEASE_VERSION,SHIFT_STATUSES,JOURNEY_TYPES,JOURNEY_STATUSES,SUPPORT_CATEGORIES,SUPPORT_PRIORITIES,SUPPORT_STATUSES,PAUSE_TRIGGERS,ownerView,createShift,recordJourney,recordSupport,exportMarkdown};
