'use strict';

const store = require('./store');
const initialPortalAuthority = require('./initialPortalAuthority');

const STORE_KEY = 'legalPortfolioOperatingSystem.json';
const OPERATING_SYSTEM_VERSION = '1.0.0';
const RELEASE_VERSION = '1.7.61';
const PORTFOLIO_SCOPE = 'Smarter Justice and its independent legal micro-portals only';
const EVIDENCE_STATES = ['EXACT_VERIFIED','OWNER_RECORDED','DEDICATED_HANDOFF_VERIFIED','STALE','PLANNED','UNKNOWN','BLOCKED','CONFLICT'];
const GATE_STATES = ['CLOSED','EVIDENCE_PENDING','READY_FOR_OWNER_DECISION','OPEN','SUSPENDED','ROLLED_BACK'];
const DECISION_STATES = ['ACTIVE','IMPLEMENTED','PENDING_IMPLEMENTATION','SUPERSEDED','REJECTED'];
const DEPENDENCY_STATES = ['NOT_CONFIGURED','CONFIGURED_UNVERIFIED','TESTED_LOCAL','STAGING_VERIFIED','PRODUCTION_VERIFIED','DEGRADED','BLOCKED','NOT_REQUIRED','DORMANT'];
const INCIDENT_STATES = ['OPEN','CONTAINED','RESOLVED','CLOSED'];
const SUPPORT_STATES = ['OPEN','IN_PROGRESS','WAITING','RESOLVED','CLOSED'];

function clean(value,max=1800){return String(value==null?'':value).trim().slice(0,max);}
function clone(value){return JSON.parse(JSON.stringify(value));}
function list(value,maxItems=50,maxLength=500){const source=Array.isArray(value)?value:String(value||'').split(/\r?\n/);return source.map(v=>clean(v,maxLength)).filter(Boolean).slice(0,maxItems);}
function bool(value){return value===true||/^(1|true|yes|on)$/i.test(String(value||''));}
function now(){return store.now();}
function validSha(value){return /^[a-f0-9]{64}$/.test(String(value||''));}
function enumValue(value,allowed,fallback){return allowed.includes(value)?value:fallback;}
function safeId(value,prefix='record'){const id=clean(value,140).toLowerCase().replace(/[^a-z0-9:-]+/g,'-').replace(/^-+|-+$/g,'');return id||store.uid(prefix,6);}

const ROLE_MATRIX = Object.freeze([
  {role:'OWNER',may:['all legal-portfolio control','record owner decisions','approve or deny gates','approve claims and protected profile changes','review billing and exports','authorize rollback and deployment'],mayNot:['bypass exact-artifact evidence','publish or activate entitlements without independent gates','store secrets or confidential legal matters in portfolio records']},
  {role:'OWNER_OPERATOR',may:['maintain non-confidential portfolio metadata','manage support, incidents, dependencies, receipts and action queues','prepare gate evidence'],mayNot:['open commercial, publication or deployment gates','approve credentials','approve refunds outside policy']},
  {role:'PROFILE_REVIEWER',may:['review claims, credential evidence, protected fields, corrections and portal-eligibility evidence'],mayNot:['self-approve credentials','activate payment or deployment','view payment secrets']},
  {role:'BILLING_SUPPORT',may:['review membership, invoice and payment state','apply approved support procedures','record reconciliation'],mayNot:['approve credentials','publish profiles','open deployment gates']},
  {role:'PORTAL_OPERATOR',may:['prepare handoffs','review import receipts','record conflicts','request rollback'],mayNot:['change professional credentials','approve payment','perform automatic portal writes']},
  {role:'FIRM_ADMIN',may:['manage authorized firm details, offices, invitations and seats'],mayNot:['alter another professional’s protected official fields','approve publication or credentials']},
  {role:'PROFESSIONAL',may:['manage own permitted profile, membership, billing and authorized firm relationship'],mayNot:['self-approve claims, credentials, eligibility, publication or ranking']}
]);

const PILOTS = Object.freeze([
  {
    order:1,portalId:'divorce-law-aid',name:'Divorce Law Aid',domain:'divorcelawaid.com',status:'CONTRACT_READY_LOCAL_ONLY',
    artifact:initialPortalAuthority.artifactFor('divorce-law-aid'),
    simpleLaunchScope:['Divorce','Separation','Custody','Child support','Spousal support','Property and financial issues','Searchable attorney directory','Short consultation-preparation path'],
    deferred:['Complex court-form automation','Automatic filing','Live portal writes'],workersCompensationBoundary:'Not applicable'
  },
  {
    order:2,portalId:'estate-law-aid',name:'Estate Law Aid',domain:'estatelawaid.com',status:'CONTRACT_READY_LOCAL_ONLY',
    artifact:initialPortalAuthority.artifactFor('estate-law-aid'),
    simpleLaunchScope:['Wills','Trusts','Probate','Estate administration','Guardianship','Planning information','Searchable attorney directory','Short readiness path'],
    deferred:['Complex document generation','Automatic filing','Live portal writes'],workersCompensationBoundary:'Not applicable'
  },
  {
    order:3,portalId:'personal-injury-law-aid',name:'Personal Injury Law Aid',domain:'personalinjurylawaid.com',status:'CONTRACT_READY_LOCAL_ONLY',
    artifact:initialPortalAuthority.artifactFor('personal-injury-law-aid'),
    simpleLaunchScope:['Vehicle accidents','Pedestrian and bicycle injuries','Premises and slip-and-fall injuries','Construction and worksite third-party injuries','Defective products','Dog bites and other negligence injuries','Wrongful death','Searchable attorney directory','Short evidence-preservation and consultation-preparation path'],
    scopeRules:['Vehicle accidents are included in Personal Injury Law Aid.','Workers’ Compensation and Medical Malpractice remain separate portals.','No claim-value calculator, liability prediction, deadline guarantee, automatic demand package or attorney-acceptance promise is part of the launch.'],
    compatibilityAssets:[{portalId:'car-accident-law-aid',state:'PRESERVED_NOT_SEPARATELY_LAUNCHED',rule:'Keep the separate repository and history. Vehicle-accident discovery and professional participation are coordinated through Personal Injury Law Aid without automatic record reassignment.'}],
    workersCompensationBoundary:'Workers’ Compensation Law Aid remains a separate portal and is not consolidated into Personal Injury Law Aid.'
  },
  {
    order:4,portalId:'domestic-violence-aid',name:'Domestic Violence Aid',domain:'DOMAIN_NOT_OWNER_CONFIRMED',status:'SAFETY_CONTRACT_REQUIRED_LOCAL_ONLY',
    artifact:initialPortalAuthority.artifactFor('domestic-violence-aid'),
    simpleLaunchScope:['Survivor-centered legal information','Attorney and legal-aid discovery','Approved organization and resource discovery','Court and agency navigation','Prevention and education','Safe cross-portal starting paths'],
    profileClasses:['attorney','law-firm','legal-aid-organization','advocate','victim-service-organization','nonprofit','community-organization','public-agency','shelter','service-provider','prevention-education-organization'],
    embeddedInitiative:{name:'The Stop Sign Project',relationship:'A Domestic Violence Aid Community Initiative',domain:'stopsignproject.org',preserveWorkingFeatures:true},
    scopeRules:['Do not automatically reassign legacy domestic-violence or Stop Sign Project records.','Do not expose confidential shelter or service locations.','Do not collect or autosave survivor narratives through launch operations.','Do not send email or SMS without an explicit safe-contact choice.','Emergency and resource information requires dated source-backed acceptance.','Payment cannot buy verification, authority, publication, specialty evidence, trust, or opportunity eligibility.'],
    deferred:['Live portal connection','Organization publication without exact authority contract','Confidential uploads','Automatic notifications','External AI','Paid growth','Sponsored placement','Professional opportunities','Automatic portal writes'],
    workersCompensationBoundary:'Not applicable'
  }
]);

const GATES = Object.freeze([
  ['public-starting-help','Public starting help'],['professional-account-creation','Professional account creation'],['free-profile-claiming','Free profile claiming'],['free-basic-profile-editing','Free basic profile editing'],['staff-verification','Staff verification'],['membership-application','Membership application'],['checkout','Checkout'],['subscriptions','Subscriptions'],['firm-seats','Firm seats'],['public-profiles','Public profiles'],['portal-exports','Portal exports'],['live-portal-imports','Live portal imports'],['paid-sponsored-visibility','Paid sponsored visibility'],['case-opportunity-access','Paid case-opportunity access'],['attorney-advertising-compliance','Attorney-advertising compliance'],['public-inquiries','Public inquiries'],['appointments','Appointments'],['ratings-reviews','Ratings and reviews'],['confidential-uploads','Confidential uploads'],['public-paid-services','Public paid services'],['automatic-portal-writes','Automatic portal writes'],['external-ai','External AI'],['production-deployment','Production deployment'],['neutral-boardroom-future-export','Neutral Boardroom future export']
].map(([id,label])=>({id,label,state:'CLOSED',owner:'Roger',evidence:[],dependencies:[],lastReviewed:'2026-07-28',activationConditions:[],rollbackConditions:[],approval:'NOT_APPROVED',reason:'Closed by default for the v1.7.61 development artifact.',history:[]})));

const DEPENDENCIES = Object.freeze([
  {id:'node-runtime',name:'Node.js 22.x',purpose:'Application runtime',status:'TESTED_LOCAL',launchCriticality:'CRITICAL',failureBehavior:'Application does not start; no unsafe fallback.',manualFallback:'Restore the approved runtime and exact artifact.'},
  {id:'npm-registry',name:'npm package registry access',purpose:'Legitimate clean dependency installation and advisory audit',status:'BLOCKED',launchCriticality:'BUILD_CRITICAL',failureBehavior:'Do not fabricate dependencies or claim a clean install.',manualFallback:'Retry through an approved legitimate registry and record evidence.'},
  {id:'postgresql',name:'PostgreSQL',purpose:'Production durable state and transactional records',status:'NOT_CONFIGURED',launchCriticality:'CRITICAL',failureBehavior:'Production writes fail closed.',manualFallback:'No sensitive or commercial writes until persistence is restored.'},
  {id:'smtp',name:'SMTP provider',purpose:'Verification, recovery, receipts and operational notices',status:'NOT_CONFIGURED',launchCriticality:'CRITICAL',failureBehavior:'Transactional flow remains pending and support state is shown; no false delivery claim.',manualFallback:'Owner-reviewed support process without bypassing email verification.'},
  {id:'stripe',name:'Stripe',purpose:'Central membership and subscription billing',status:'NOT_CONFIGURED',launchCriticality:'COMMERCIAL_CRITICAL',failureBehavior:'Checkout and entitlement activation remain closed.',manualFallback:'No manual entitlement grant based only on a claimed payment.'},
  {id:'dns-tls',name:'DNS and TLS',purpose:'Canonical HTTPS service',status:'CONFIGURED_UNVERIFIED',launchCriticality:'CRITICAL',failureBehavior:'Do not authorize launch on an unverified origin.',manualFallback:'Use staging only after HTTPS verification.'},
  {id:'private-storage',name:'Private file storage',purpose:'Restricted uploads if later enabled',status:'NOT_CONFIGURED',launchCriticality:'CONDITIONAL',failureBehavior:'Confidential uploads remain closed.',manualFallback:'Do not collect files.'},
  {id:'monitoring',name:'Monitoring and alerting',purpose:'Service, database, email, Stripe and integration health',status:'NOT_CONFIGURED',launchCriticality:'CRITICAL',failureBehavior:'Launch remains NO_GO.',manualFallback:'Documented manual checks may support staging only.'},
  {id:'logging',name:'Structured operational logging',purpose:'Errors, security events and audit support',status:'TESTED_LOCAL',launchCriticality:'CRITICAL',failureBehavior:'Sensitive actions fail or are blocked when authoritative audit cannot be recorded.',manualFallback:'No unaudited sensitive action.'},
  {id:'backup-storage',name:'Encrypted backup storage',purpose:'Database and private operational recovery',status:'NOT_CONFIGURED',launchCriticality:'CRITICAL',failureBehavior:'Launch remains NO_GO.',manualFallback:'None for live commercial launch.'},
  {id:'hosting',name:'Hosting and deployment provider',purpose:'Staging and production execution',status:'CONFIGURED_UNVERIFIED',launchCriticality:'CRITICAL',failureBehavior:'No deployment authorization.',manualFallback:'Local development only.'},
  {id:'divorce-portal',name:'Divorce Law Aid',purpose:'Pilot destination portal',status:'CONFIGURED_UNVERIFIED',launchCriticality:'PILOT_CRITICAL',failureBehavior:'Keep export private and preserve last-known-good portal state.',manualFallback:'Smarter Justice claim and account functions remain available without claiming a live portal connection.'},
  {id:'estate-portal',name:'Estate Law Aid',purpose:'Pilot destination portal',status:'CONFIGURED_UNVERIFIED',launchCriticality:'PILOT_CRITICAL',failureBehavior:'Keep export private and preserve last-known-good portal state.',manualFallback:'Smarter Justice claim and account functions remain available without claiming a live portal connection.'},
  {id:'personal-injury-portal',name:'Personal Injury Law Aid',purpose:'Pilot destination covering vehicle accidents and other injury matters',status:'CONFIGURED_UNVERIFIED',launchCriticality:'PILOT_CRITICAL',failureBehavior:'Keep export private and preserve last-known-good portal state.',manualFallback:'Smarter Justice claim and account functions remain available without claiming a live portal connection.'},
  {id:'neutral-boardroom',name:'Neutral Boardroom',purpose:'Optional future non-confidential export only',status:'DORMANT',launchCriticality:'NOT_CRITICAL',failureBehavior:'No effect on Smarter Justice launch, management, billing, profiles, support, monitoring, backup, rollback or portal integration.',manualFallback:'No fallback required; Smarter Justice is authoritative.'}
]);

const DATA_CLASSIFICATION = Object.freeze([
  {class:'PUBLIC_PROFESSIONAL_DATA',examples:['Approved professional and firm fields','Approved portal projection'],control:'Only approved, source-tracked fields may be exported.'},
  {class:'PRIVATE_ACCOUNT_DATA',examples:['Account email','Private drafts','Firm invitations'],control:'Authenticated access; no portal export unless separately approved as public.'},
  {class:'RESTRICTED_VERIFICATION_DATA',examples:['Claim evidence','Credential evidence','Review notes'],control:'Least privilege; never included in portal handoffs.'},
  {class:'RESTRICTED_BILLING_METADATA',examples:['Stripe customer/subscription references','Invoice and payment state'],control:'No card data; no profile handoff.'},
  {class:'RESTRICTED_SUPPORT_OPERATIONS',examples:['Support tickets','Incidents','Import errors','Owner decisions'],control:'Private, auditable and retention-controlled.'},
  {class:'CONFIDENTIAL_USER_MATTER_DATA',examples:['Legal narratives','Documents','Evidence','Deadlines','Communications'],control:'Excluded from professional handoffs, portfolio coordination, analytics and ordinary owner dashboards.'},
  {class:'SECRETS',examples:['Password hashes','MFA secrets','Session secrets','API keys','Database and Stripe credentials'],control:'Never displayed, exported, logged or packaged.'}
]);

const OWNER_DECISIONS = Object.freeze([
  {id:'decision-self-contained-smarter-justice',date:'2026-07-28',decision:'Smarter Justice is the active and self-contained operating and governance system for the legal portfolio. Roger is the final owner authority.',scope:'Initial live-attorney launch and legal portfolio operations',rationale:'Neutral Boardroom will not be launched or used as an operational dependency.',status:'IMPLEMENTED',supersedes:['decision-neutral-boardroom-top-layer'],effectiveVersion:'1.7.43',ownerIdentity:'Roger',implementationComplete:true},
  {id:'decision-neutral-boardroom-dormant',date:'2026-07-28',decision:'Neutral Boardroom is dormant, noncritical, disabled from automatic transmission and retained only as an optional future non-confidential export boundary.',scope:'All launch-critical Smarter Justice operations',rationale:'The legal portfolio must remain operable when Neutral Boardroom is completely unavailable.',status:'IMPLEMENTED',supersedes:[],effectiveVersion:'1.7.43',ownerIdentity:'Roger',implementationComplete:true},
  {id:'decision-pilot-order-divorce-estate-pi',date:'2026-07-28',decision:'Pilot order is Divorce Law Aid first, Estate Law Aid second, and Personal Injury Law Aid third.',scope:'Initial portal integration and New York attorney outreach',rationale:'Use simple, polished portal experiences to prove the central account and read-only distribution model.',status:'IMPLEMENTED',supersedes:['immigration-first rollout'],effectiveVersion:'1.7.43',ownerIdentity:'Roger',implementationComplete:true},
  {id:'decision-personal-injury-includes-vehicle-accidents',date:'2026-07-28',decision:'Personal Injury Law Aid covers vehicle accidents and other personal-injury categories for the pilot.',scope:'Personal Injury pilot discovery, profile participation and integration materials',rationale:'Keep the launch understandable and avoid a separate competing vehicle-accident pilot.',status:'IMPLEMENTED',supersedes:[],effectiveVersion:'1.7.43',ownerIdentity:'Roger',implementationComplete:true},
  {id:'decision-workers-comp-separate',date:'2026-07-28',decision:'Workers’ Compensation Law Aid remains a separate portal and is not consolidated into Personal Injury Law Aid.',scope:'Portal boundaries and routing',rationale:'Workers’ compensation has a distinct benefit system and operational workflow.',status:'IMPLEMENTED',supersedes:[],effectiveVersion:'1.7.43',ownerIdentity:'Roger',implementationComplete:true},
  {id:'decision-portal-first-claim-central-execution',date:'2026-07-28',decision:'Attorneys discover and claim public specialty profiles on the micro-portal, then complete account, verification, profile-management, firm, support and billing actions centrally in Smarter Justice.',scope:'Initial professional enrollment and profile management',rationale:'The portal provides specialty context while one central system prevents duplicate accounts and conflicting core profiles.',status:'IMPLEMENTED',supersedes:[],effectiveVersion:'1.7.43',ownerIdentity:'Roger',implementationComplete:true},
  {id:'decision-complimentary-founding-profile-pilot',date:'2026-07-28',decision:'Smarter Justice may issue owner-approved, time-bounded complimentary Founding Profile Pilot access without creating a false paid membership or bypassing verification, specialty eligibility or publication review.',scope:'Initial in-person attorney demonstrations and controlled profile onboarding',rationale:'Profile demonstrations should not depend on incomplete live billing, but must remain truthful and fail-closed.',status:'SUPERSEDED',supersedes:[],effectiveVersion:'1.7.43',ownerIdentity:'Roger',implementationComplete:true},
  {id:'decision-free-basic-profile-control',date:'2026-07-29',decision:'Attorneys and firms may claim, verify, correct and edit their basic profiles without payment.',scope:'Central professional account and profile control',rationale:'Follow the transparent directory model used by leading competitors while preserving independent verification and staff approval.',status:'IMPLEMENTED',supersedes:['decision-complimentary-founding-profile-pilot'],effectiveVersion:'1.7.44',ownerIdentity:'Roger',implementationComplete:true},
  {id:'decision-paid-growth-products',date:'2026-07-29',decision:'Paid products may add clearly labeled sponsored visibility, enhanced prominence, lead eligibility and access to case or attorney-review opportunities.',scope:'Professional growth and monetization',rationale:'Separate free factual profile control from optional commercial promotion and opportunity access.',status:'IMPLEMENTED',supersedes:[],effectiveVersion:'1.7.44',ownerIdentity:'Roger',implementationComplete:true},
  {id:'decision-fixed-fee-compliance',date:'2026-07-29',decision:'Professional growth charges must be disclosed fixed subscription, advertising or opportunity-access charges and may not be a percentage of legal fees, contingent on retention or outcome, or payment for verification, specialty eligibility, endorsement or organic rank.',scope:'Billing, attorney advertising, opportunity access and compliance',rationale:'Preserve professional independence, truthful advertising and fail-closed legal compliance.',status:'IMPLEMENTED',supersedes:[],effectiveVersion:'1.7.44',ownerIdentity:'Roger',implementationComplete:true},
  {id:'decision-live-gates-closed-v1744',date:'2026-07-29',decision:'Deployment, live billing, paid sponsored visibility, case-opportunity access, public commercial gates, live portal imports and automatic portal writes remain closed.',scope:'v1.7.44 development release',rationale:'External production acceptance and exact rollback approval remain incomplete.',status:'IMPLEMENTED',supersedes:[],effectiveVersion:'1.7.44',ownerIdentity:'Roger',implementationComplete:true},
  {id:'decision-rollback-artifact-required',date:'2026-07-28',decision:'One exact rollback artifact must be explicitly approved before deployment; v1.7.44 does not guess among historical rollback references.',scope:'Deployment authorization',rationale:'Rollback identity is unresolved in the v1.7.41 baseline.',status:'PENDING_IMPLEMENTATION',supersedes:[],effectiveVersion:'future owner approval',ownerIdentity:'Roger',implementationComplete:false}
]);

const ARTIFACTS = Object.freeze([
  {artifactId:'smarter-justice-v1.7.41',productId:'general-smarter-justice-start',version:'1.7.41',filename:'smarter-justice-v1.7.41.zip',sha256:'f7db1b271f3a88314095a471305ff4c913882e6e456be41f48312453064e8b15',sizeBytes:2083467,evidenceState:'HISTORICAL',authority:'Historical exact artifact preserved.',deploymentState:'NOT_DEPLOYED',superseded:true},
  {artifactId:'smarter-justice-v1.7.42',productId:'general-smarter-justice-start',version:'1.7.42',filename:'smarter-justice-v1.7.42.zip',sha256:'b3c265bb6d3ac39ded12fa59e105d8ac55b82f243832a8e48347ad5cabfcc0e9',sizeBytes:2234729,evidenceState:'EXACT_VERIFIED',authority:'Exact uploaded baseline independently verified for the v1.7.44 build.',deploymentState:'NOT_DEPLOYED',superseded:true},
  {artifactId:'smarter-justice-v1.7.43',productId:'general-smarter-justice-start',version:'1.7.43',filename:'smarter-justice-v1.7.43.zip',sha256:'73bb9aa4f20685a2949ea495f5e23c2ca19bb7cf4faa7e121e271b59499e40df',sizeBytes:2322752,evidenceState:'HISTORICAL',authority:'Exact prior artifact preserved as the v1.7.44 rollback candidate pending owner approval.',deploymentState:'NOT_DEPLOYED',superseded:true},
  {artifactId:'smarter-justice-v1.7.44',productId:'general-smarter-justice-start',version:'1.7.44',filename:'smarter-justice-v1.7.44.zip',sha256:'b280f19078b95a006becf970b55a480464fa157d679a98886c2665fb2697c1b3',sizeBytes:2401801,evidenceState:'EXACT_VERIFIED',authority:'Exact uploaded v1.7.44 artifact preserved as historical evidence.',deploymentState:'NOT_DEPLOYED',superseded:true},
  {artifactId:'smarter-justice-v1.7.45',productId:'general-smarter-justice-start',version:'1.7.45',filename:'smarter-justice-v1.7.45.zip',sha256:'2549ada6af5c88080736b3adede32f893b321a8f57682fe9d0538f75024af8b0',sizeBytes:2550227,evidenceState:'EXACT_VERIFIED',authority:'Exact historical artifact preserved; superseded by v1.7.46.',deploymentState:'NOT_DEPLOYED',superseded:true},
  {artifactId:'smarter-justice-v1.7.46',productId:'general-smarter-justice-start',version:'1.7.46',filename:'smarter-justice-v1.7.46.zip',sha256:'d6fa5cb4c7af8686d24081fa69ecb8c1cc1d6f355bb4258ec18af075cb1c5d0e',sizeBytes:2697013,evidenceState:'EXACT_VERIFIED',authority:'Historical exact artifact; superseded by v1.7.47.',deploymentState:'NOT_DEPLOYED',superseded:true},
  {artifactId:'smarter-justice-v1.7.47',productId:'general-smarter-justice-start',version:'1.7.47',filename:'smarter-justice-v1.7.47.zip',sha256:'f7589caec5feebafdaf3ef2ee4d3327e9923ad2f41421d64705603e3dbd65a1e',sizeBytes:2798911,evidenceState:'EXACT_VERIFIED',authority:'Exact uploaded v1.7.47 historical source baseline preserved.',deploymentState:'NOT_DEPLOYED',superseded:true},
  {artifactId:'smarter-justice-v1.7.50',productId:'general-smarter-justice-start',version:'1.7.50',filename:'smarter-justice-v1.7.50.zip',sha256:'72d7b71cedd169cc6d42bdbb49ae1ba5083ef4acc90b196f21474087faee8eef',sizeBytes:3089886,evidenceState:'EXACT_VERIFIED',authority:'Exact verified rollback baseline.',deploymentState:'NOT_DEPLOYED',superseded:true},
  {artifactId:'smarter-justice-v1.7.52',productId:'general-smarter-justice-start',version:'1.7.52',filename:'smarter-justice-v1.7.52.zip',sha256:'33829e486ea38ab3dce60bd1f5f6a5023ba933286bcb380aa4887fc891033c71',sizeBytes:3896700,evidenceState:'EXACT_VERIFIED',authority:'Exact verified rollback baseline for v1.7.53.',deploymentState:'NOT_DEPLOYED',superseded:true},
  {artifactId:'smarter-justice-v1.7.53-exact',productId:'general-smarter-justice-start',version:'1.7.53',filename:'smarter-justice-v1.7.53.zip',sha256:'f6c881faf1f72de44d062b15d3d7701574663a2b22a9d9273a6930580a359cac',sizeBytes:4570546,evidenceState:'EXACT_VERIFIED',authority:'Exact independently verified source and immediate rollback artifact.',deploymentState:'NOT_DEPLOYED',superseded:true},
  {artifactId:'smarter-justice-v1.7.56',productId:'general-smarter-justice-start',version:'1.7.56',filename:'smarter-justice-v1.7.56.zip',sha256:'fe178fc3befc303a1b3a3dd54646a96aafdd55cfb9e0388ed092491d98932681',sizeBytes:4840702,evidenceState:'EXACT_VERIFIED',authority:'Historical exact artifact; superseded by v1.7.57.',deploymentState:'NOT_DEPLOYED',superseded:true},
  {artifactId:'smarter-justice-v1.7.57',productId:'general-smarter-justice-start',version:'1.7.57',filename:'smarter-justice-v1.7.57.zip',sha256:'dbd031c6b35bf1dd107759852c145183316a4005e2604bbd4f106ffda9a0afde',sizeBytes:4931830,evidenceState:'EXACT_VERIFIED',authority:'Exact independently verified source and immediate rollback artifact.',deploymentState:'NOT_DEPLOYED',superseded:false},
  {artifactId:'smarter-justice-v1.7.59',productId:'general-smarter-justice-start',version:'1.7.59',filename:'smarter-justice-v1.7.59.zip',sha256:'f08909fbf879e9005d47b7361f089decc946d78c21c6118471b4be1fb77f9bb0',sizeBytes:5140893,evidenceState:'EXACT_VERIFIED',authority:'Historical exact artifact; superseded by v1.7.60.',deploymentState:'NOT_DEPLOYED',superseded:true},
  {artifactId:'smarter-justice-v1.7.60',productId:'general-smarter-justice-start',version:'1.7.60',filename:'smarter-justice-v1.7.60.zip',sha256:'832ec66ffda5acf0a2cb7f105cbf4c08d150b38d1582c30cea3599b3e1925e0f',sizeBytes:5263896,evidenceState:'EXACT_VERIFIED',authority:'Exact independently reproduced source and immediate rollback artifact for v1.7.61.',deploymentState:'NOT_DEPLOYED',superseded:false},
  {artifactId:'smarter-justice-v1.7.58',productId:'general-smarter-justice-start',version:'1.7.58',filename:'smarter-justice-v1.7.58.zip',sha256:'6a362e8c55f0c60a4668df78b4656ce87a2e592d4f7f60b298cd4e5cbd1fe56e',sizeBytes:5017665,evidenceState:'EXACT_VERIFIED',authority:'Final hash and size are reported externally after deterministic packaging and two exact-artifact test extractions; embedded inventory validates every other packaged file.',deploymentState:'NOT_DEPLOYED',superseded:false},
  ...PILOTS.map(p=>({artifactId:`${p.portalId}-owner-recorded`,productId:p.portalId,version:p.artifact.version,filename:p.artifact.filename,sha256:p.artifact.sha256,sizeBytes:p.artifact.sizeBytes,evidenceState:p.artifact.evidenceState,authority:'Owner-recorded exact identity from the dedicated portal work; reverify the uploaded artifact in its own builder chat before integration.',deploymentState:'NOT_CONFIRMED',superseded:false}))
]);

function seedState(){return {
  schemaName:'smarter-justice-self-contained-legal-portfolio-operating-system',schemaVersion:OPERATING_SYSTEM_VERSION,releaseVersion:RELEASE_VERSION,
  authority:{finalOwner:'Roger',operatingSystem:'Smarter Justice Legal Portfolio Control Center',neutralBoardroom:{status:'DORMANT_OPTIONAL_EXPORT_ONLY',launchCritical:false,runtimeDependency:false,managementDependency:false,sourceOfTruth:false,automaticTransmission:false}},
  scope:PORTFOLIO_SCOPE,roles:clone(ROLE_MATRIX),pilots:clone(PILOTS),gates:clone(GATES),dependencies:clone(DEPENDENCIES),dataClassification:clone(DATA_CLASSIFICATION),
  decisions:clone(OWNER_DECISIONS),artifacts:clone(ARTIFACTS),supportCases:[],incidents:[],integrationReceipts:[],updatedAt:'',updatedBy:''
};}

function normalize(raw){
  const base=raw&&typeof raw==='object'&&!Array.isArray(raw)?raw:{};
  const seeded=seedState();
  const mergeById=(seedRows,savedRows,key)=>{const saved=new Map((Array.isArray(savedRows)?savedRows:[]).filter(Boolean).map(row=>[row[key],row]));return seedRows.map(row=>({...row,...(saved.get(row[key])||{}),[key]:row[key]}));};
  const decisionMap=new Map(seeded.decisions.map(row=>[row.id,row])); for(const row of Array.isArray(base.decisions)?base.decisions:[]) if(row?.id) decisionMap.set(row.id,{...decisionMap.get(row.id),...row,id:row.id});
  const artifactMap=new Map(seeded.artifacts.map(row=>[row.artifactId,row])); for(const row of Array.isArray(base.artifacts)?base.artifacts:[]) if(row?.artifactId) artifactMap.set(row.artifactId,{...artifactMap.get(row.artifactId),...row,artifactId:row.artifactId});
  return {...seeded,...base,schemaName:seeded.schemaName,schemaVersion:OPERATING_SYSTEM_VERSION,releaseVersion:RELEASE_VERSION,authority:seeded.authority,scope:seeded.scope,roles:seeded.roles,pilots:seeded.pilots,
    gates:mergeById(seeded.gates,base.gates,'id'),dependencies:mergeById(seeded.dependencies,base.dependencies,'id'),dataClassification:seeded.dataClassification,
    decisions:[...decisionMap.values()].slice(0,250),artifacts:[...artifactMap.values()].slice(0,250),supportCases:Array.isArray(base.supportCases)?base.supportCases.slice(0,500):[],incidents:Array.isArray(base.incidents)?base.incidents.slice(0,250):[],integrationReceipts:Array.isArray(base.integrationReceipts)?base.integrationReceipts.slice(0,500):[]};
}
function read(){return normalize(store.readJson(STORE_KEY,seedState()));}
function summary(state=read()){
  return {pilotCount:state.pilots.length,pilotOrder:state.pilots.map(row=>row.portalId),openGates:state.gates.filter(row=>row.state==='OPEN').length,closedGates:state.gates.filter(row=>row.state==='CLOSED').length,pendingGateDecisions:state.gates.filter(row=>row.state==='READY_FOR_OWNER_DECISION').length,criticalDependenciesBlocked:state.dependencies.filter(row=>['CRITICAL','COMMERCIAL_CRITICAL','PILOT_CRITICAL'].includes(row.launchCriticality)&&!['STAGING_VERIFIED','PRODUCTION_VERIFIED','NOT_REQUIRED'].includes(row.status)).length,ownerDecisions:state.decisions.length,pendingDecisions:state.decisions.filter(row=>row.status==='PENDING_IMPLEMENTATION').length,artifacts:state.artifacts.length,openSupportCases:state.supportCases.filter(row=>!['RESOLVED','CLOSED'].includes(row.status)).length,openIncidents:state.incidents.filter(row=>!['RESOLVED','CLOSED'].includes(row.status)).length,neutralBoardroomLaunchCritical:false,automaticPortalWrites:false,livePortalConnections:0,launchState:'NO_GO'};
}
function ownerView(){const state=read();return {...clone(state),summary:summary(state)};}

async function recordDecision(input={},actor='owner'){
  const decision=clean(input.decision,2400); if(decision.length<8)return{error:'Add a specific owner decision.'};
  const id=safeId(input.id||`decision-${Date.now()}`,'decision'); const tx=await store.mutateJson(STORE_KEY,seedState(),async raw=>{const state=normalize(raw);const current=state.decisions.find(row=>row.id===id);const row={id,date:clean(input.date,30)||now().slice(0,10),decision,scope:clean(input.scope,1200),rationale:clean(input.rationale,1800),status:enumValue(input.status,DECISION_STATES,current?.status||'ACTIVE'),supersedes:list(input.supersedes),evidence:list(input.evidence),effectiveVersion:clean(input.effectiveVersion,80)||RELEASE_VERSION,ownerIdentity:clean(input.ownerIdentity,120)||'Roger',implementationComplete:bool(input.implementationComplete),updatedAt:now(),updatedBy:clean(actor,120)||'owner'};state.decisions=[row,...state.decisions.filter(item=>item.id!==id)].slice(0,250);state.updatedAt=row.updatedAt;state.updatedBy=row.updatedBy;return{value:state,result:{decision:row}};},{event:r=>({eventType:'owner_decision_recorded',payload:{decisionId:r?.decision?.id,status:r?.decision?.status}})});store.addAudit({actor,action:'owner_decision_recorded',details:{decisionId:id,status:tx.result.decision.status}});return tx.result;
}

async function updateGate(id,input={},actor='owner'){
  const desired=enumValue(input.state,GATE_STATES,''); if(!desired)return{error:'Choose a valid gate state.'};
  const tx=await store.mutateJson(STORE_KEY,seedState(),async raw=>{const state=normalize(raw);const gate=state.gates.find(row=>row.id===id);if(!gate)return{value:state,result:{error:'Unknown launch gate.'}};
    if(desired==='OPEN'){
      const confirmation=clean(input.confirmation,180); const allow=bool(process.env.ALLOW_OWNER_GATE_ACTIVATION);
      if(!allow)return{value:state,result:{error:'This development artifact keeps live gate activation disabled. Set ALLOW_OWNER_GATE_ACTIVATION only after staging evidence and explicit owner approval.'}};
      if(confirmation!==`OPEN ${id}`)return{value:state,result:{error:`Type OPEN ${id} to confirm this sensitive action.`}};
      if(!list(input.evidence).length||clean(input.reason,1200).length<8)return{value:state,result:{error:'Opening a gate requires evidence and a reason.'}};
    }
    const prior=gate.state;gate.state=desired;gate.approval=desired==='OPEN'?'OWNER_APPROVED':desired==='READY_FOR_OWNER_DECISION'?'OWNER_DECISION_REQUIRED':'NOT_APPROVED';gate.evidence=list(input.evidence);gate.dependencies=list(input.dependencies);gate.lastReviewed=now().slice(0,10);gate.reason=clean(input.reason,1500)||gate.reason;gate.history=[{at:now(),actor:clean(actor,120)||'owner',priorState:prior,state:desired,reason:gate.reason},...(gate.history||[])].slice(0,100);state.updatedAt=now();state.updatedBy=clean(actor,120)||'owner';return{value:state,result:{gate:clone(gate)}};
  },{event:r=>r?.gate?({eventType:'launch_gate_updated',payload:{gateId:r.gate.id,state:r.gate.state}}):null});
  if(tx.result?.gate)store.addAudit({actor,action:'launch_gate_updated',details:{gateId:id,state:tx.result.gate.state}});return tx.result;
}

async function registerArtifact(input={},actor='owner'){
  const productId=safeId(input.productId,'product'); const version=clean(input.version,80); const filename=clean(input.filename,300); if(!productId||!version||!filename)return{error:'Product, version and filename are required.'};
  const evidenceState=enumValue(input.evidenceState,EVIDENCE_STATES,'OWNER_RECORDED'); const sha256=clean(input.sha256,80); const sizeBytes=Math.max(0,Number(input.sizeBytes)||0);
  if(evidenceState==='EXACT_VERIFIED'&&!((validSha(sha256)&&sizeBytes>0)||(sha256==='DETACHED_AFTER_PACKAGING'&&sizeBytes===0)))return{error:'Exact-verified artifacts require a valid hash and size, except the detached current artifact identity.'};
  const artifactId=safeId(input.artifactId||`${productId}-${version}`,'artifact'); const tx=await store.mutateJson(STORE_KEY,seedState(),async raw=>{const state=normalize(raw);const current=state.artifacts.find(row=>row.artifactId===artifactId)||{};const row={...current,artifactId,productId,version,filename,sha256,sizeBytes,evidenceState,authority:clean(input.authority,1600)||'Owner-recorded; dedicated exact artifact remains authoritative.',deploymentState:clean(input.deploymentState,120)||'NOT_CONFIRMED',inventoryIdentity:clean(input.inventoryIdentity,180),testEvidence:list(input.testEvidence),rollbackCompatibility:clean(input.rollbackCompatibility,1200),superseded:bool(input.superseded),recordedAt:current.recordedAt||now(),updatedAt:now(),updatedBy:clean(actor,120)||'owner'};state.artifacts=[row,...state.artifacts.filter(item=>item.artifactId!==artifactId)].slice(0,250);state.updatedAt=row.updatedAt;return{value:state,result:{artifact:row}};},{event:r=>({eventType:'artifact_registry_updated',payload:{artifactId:r?.artifact?.artifactId,evidenceState:r?.artifact?.evidenceState}})});store.addAudit({actor,action:'artifact_registry_updated',details:{artifactId,evidenceState}});return tx.result;
}

async function updateDependency(id,input={},actor='owner'){
  const tx=await store.mutateJson(STORE_KEY,seedState(),async raw=>{const state=normalize(raw);const row=state.dependencies.find(item=>item.id===id);if(!row)return{value:state,result:{error:'Unknown dependency.'}};row.status=enumValue(input.status,DEPENDENCY_STATES,row.status);row.owner=clean(input.owner,160)||row.owner||'Owner';row.configurationSource=clean(input.configurationSource,500);row.monitoring=clean(input.monitoring,800);row.supportContact=clean(input.supportContact,500);row.testEvidence=list(input.testEvidence);row.notes=clean(input.notes,1500);row.updatedAt=now();row.updatedBy=clean(actor,120)||'owner';state.updatedAt=row.updatedAt;return{value:state,result:{dependency:clone(row)}};},{event:r=>({eventType:'launch_dependency_updated',payload:{dependencyId:r?.dependency?.id,status:r?.dependency?.status}})});if(tx.result?.dependency)store.addAudit({actor,action:'launch_dependency_updated',details:{dependencyId:id,status:tx.result.dependency.status}});return tx.result;
}

async function recordSupportCase(input={},actor='owner'){
  const summaryText=clean(input.summary,1600); if(summaryText.length<6)return{error:'Add a support summary.'}; const id=safeId(input.id||store.uid('support',6),'support'); const tx=await store.mutateJson(STORE_KEY,seedState(),async raw=>{const state=normalize(raw);const row={id,category:clean(input.category,160)||'general',status:enumValue(input.status,SUPPORT_STATES,'OPEN'),priority:clean(input.priority,40)||'medium',portalId:clean(input.portalId,140),professionalId:clean(input.professionalId,180),summary:summaryText,assignee:clean(input.assignee,160),dueDate:clean(input.dueDate,30),resolution:clean(input.resolution,1800),createdAt:now(),updatedAt:now(),createdBy:clean(actor,120)||'owner'};state.supportCases=[row,...state.supportCases.filter(item=>item.id!==id)].slice(0,500);state.updatedAt=row.updatedAt;return{value:state,result:{supportCase:row}};},{event:r=>({eventType:'portfolio_support_case_recorded',payload:{supportCaseId:r?.supportCase?.id,status:r?.supportCase?.status}})});store.addAudit({actor,action:'portfolio_support_case_recorded',details:{supportCaseId:id}});return tx.result;
}

async function recordIncident(input={},actor='owner'){
  const summaryText=clean(input.summary,1800); if(summaryText.length<8)return{error:'Add an incident summary.'}; const id=safeId(input.id||store.uid('incident',6),'incident'); const tx=await store.mutateJson(STORE_KEY,seedState(),async raw=>{const state=normalize(raw);const row={id,severity:clean(input.severity,40)||'medium',status:enumValue(input.status,INCIDENT_STATES,'OPEN'),service:clean(input.service,200),summary:summaryText,userImpact:clean(input.userImpact,1600),dataImpact:clean(input.dataImpact,1600),containment:clean(input.containment,1600),resolution:clean(input.resolution,1800),owner:clean(input.owner,160)||'Roger',createdAt:now(),updatedAt:now(),createdBy:clean(actor,120)||'owner'};state.incidents=[row,...state.incidents.filter(item=>item.id!==id)].slice(0,250);state.updatedAt=row.updatedAt;return{value:state,result:{incident:row}};},{event:r=>({eventType:'portfolio_incident_recorded',payload:{incidentId:r?.incident?.id,status:r?.incident?.status}})});store.addAudit({actor,action:'portfolio_incident_recorded',details:{incidentId:id}});return tx.result;
}

async function recordIntegrationReceipt(input={},actor='owner'){
  const portalId=clean(input.portalId,140); const batchId=clean(input.batchId,180); if(!portalId||!batchId)return{error:'Portal and batch ID are required.'}; const resultState=clean(input.result,120)||'LOCAL_FIXTURE_ONLY';
  const id=safeId(input.id||`receipt-${portalId}-${batchId}`,'receipt'); const tx=await store.mutateJson(STORE_KEY,seedState(),async raw=>{const state=normalize(raw);const row={id,portalId,batchId,schemaVersion:clean(input.schemaVersion,80)||'1.4.0',digest:clean(input.digest,100),receivedAt:clean(input.receivedAt,60)||now(),processedAt:clean(input.processedAt,60)||now(),upsertPrivateCount:Math.max(0,Number(input.upsertPrivateCount)||0),upsertPublicCount:Math.max(0,Number(input.upsertPublicCount)||0),suppressionCount:Math.max(0,Number(input.suppressionCount)||0),rejectedCount:Math.max(0,Number(input.rejectedCount)||0),conflictCount:Math.max(0,Number(input.conflictCount)||0),lastKnownGood:bool(input.lastKnownGood),adapterVersion:clean(input.adapterVersion,80),operator:clean(input.operator,160)||clean(actor,120)||'owner',result:resultState,errorSummary:clean(input.errorSummary,1600),rollbackAvailable:bool(input.rollbackAvailable),environment:clean(input.environment,80)||'local',liveConnection:false,automaticWrites:false};state.integrationReceipts=[row,...state.integrationReceipts.filter(item=>item.id!==id)].slice(0,500);state.updatedAt=now();return{value:state,result:{receipt:row}};},{event:r=>({eventType:'portal_integration_receipt_recorded',payload:{receiptId:r?.receipt?.id,portalId:r?.receipt?.portalId,result:r?.receipt?.result}})});store.addAudit({actor,action:'portal_integration_receipt_recorded',details:{receiptId:id,portalId,result:resultState}});return tx.result;
}

function exportBundle(){const state=ownerView();return{...state,exportedAt:now(),exportRules:['Non-confidential legal-portfolio metadata only.','No legal matter narratives, private documents, secrets, payment-card data or credential evidence.','Dedicated exact portal artifacts remain authoritative.','Neutral Boardroom is not a recipient or dependency unless a future export is separately approved.']};}
function markdown(){const view=ownerView();return `# Smarter Justice Self-Contained Legal Portfolio Operating System\n\nRelease: ${view.releaseVersion}\nAuthority: Roger through Smarter Justice\nLaunch state: ${view.summary.launchState}\nNeutral Boardroom: dormant optional export only; not launch-critical\n\n## Pilot order\n\n${view.pilots.map(p=>`${p.order}. ${p.name} (${p.portalId})`).join('\n')}\n\n## Owner decisions\n\n${view.decisions.map(d=>`- **${d.id}** [${d.status}] ${d.decision}`).join('\n')}\n\n## Launch gates\n\n${view.gates.map(g=>`- ${g.label}: ${g.state}`).join('\n')}\n\n## Dependencies\n\n${view.dependencies.map(d=>`- ${d.name}: ${d.status}; ${d.launchCriticality}`).join('\n')}\n`;}

module.exports={OPERATING_SYSTEM_VERSION,RELEASE_VERSION,EVIDENCE_STATES,GATE_STATES,DECISION_STATES,DEPENDENCY_STATES,ROLE_MATRIX,PILOTS,ownerView,summary,recordDecision,updateGate,registerArtifact,updateDependency,recordSupportCase,recordIncident,recordIntegrationReceipt,exportBundle,markdown};
