const store = require('./store');

const STORE_KEY='paidPilotOperations.json';
const STANDARD_VERSION='1.0.0';
const STRIPE_EVENT_STATUSES=['received','processing','handled','ignored','failed'];
const ISSUE_STATUSES=['open','investigating','waiting','resolved','closed'];
const INCIDENT_STATUSES=['draft','open','contained','recovering','resolved','closed'];
const APPROVAL_STATUSES=['pending','approved','rejected','revoked','expired'];

function clean(value,max=4000){return String(value==null?'':value).trim().slice(0,max);}
function oneOf(value,allowed,fallback){return allowed.includes(value)?value:fallback;}
function list(value,maxItems=100,maxLength=300){const source=Array.isArray(value)?value:String(value||'').split(/\r?\n|,/);return [...new Set(source.map(x=>clean(x,maxLength)).filter(Boolean))].slice(0,maxItems);}
function clone(value){return JSON.parse(JSON.stringify(value));}
function now(){return store.now();}
function initialState(){return {schemaVersion:'1.0.0',standardVersion:STANDARD_VERSION,stripeEvents:[],billingIssues:[],incidents:[],ownerApprovals:[],environmentSnapshots:[],updatedAt:'',stateRevision:0};}
function normalize(raw){const base=raw&&typeof raw==='object'&&!Array.isArray(raw)?raw:{};return {...initialState(),...base,stripeEvents:Array.isArray(base.stripeEvents)?base.stripeEvents:[],billingIssues:Array.isArray(base.billingIssues)?base.billingIssues:[],incidents:Array.isArray(base.incidents)?base.incidents:[],ownerApprovals:Array.isArray(base.ownerApprovals)?base.ownerApprovals:[],environmentSnapshots:Array.isArray(base.environmentSnapshots)?base.environmentSnapshots:[],stateRevision:Number.isFinite(Number(base.stateRevision))?Number(base.stateRevision):0};}
function readState(){return normalize(store.readJson(STORE_KEY,initialState()));}
function stamp(state){state.schemaVersion='1.0.0';state.standardVersion=STANDARD_VERSION;state.stateRevision=(Number(state.stateRevision)||0)+1;state.updatedAt=now();return state;}
async function mutate(mutator,eventFactory){const tx=await store.mutateJson(STORE_KEY,initialState(),async raw=>{const state=normalize(raw);const result=await mutator(state);return {value:stamp(state),result};},{event:(result,next)=>eventFactory?eventFactory(result,next):null});return tx.result;}
function safeStripeObject(object={}){return {id:clean(object.id,240),object:clean(object.object,120),status:clean(object.status,120),paymentStatus:clean(object.payment_status,120),customer:clean(typeof object.customer==='string'?object.customer:object.customer?.id,240),subscription:clean(typeof object.subscription==='string'?object.subscription:object.subscription?.id,240),invoice:clean(typeof object.invoice==='string'?object.invoice:object.invoice?.id,240),amountTotal:Number.isFinite(Number(object.amount_total))?Number(object.amount_total):null,currency:clean(object.currency,20),accountId:clean(object.metadata?.accountId,180),membershipKind:clean(object.metadata?.membershipKind,80),membershipId:clean(object.metadata?.membershipId,180),planId:clean(object.metadata?.planId,120),billingCadence:clean(object.metadata?.billingCadence,40),seatCount:Number.isFinite(Number(object.metadata?.seatCount))?Number(object.metadata.seatCount):null};}
async function beginStripeEvent(event={}){
  const eventId=clean(event.id,240); if(!eventId)return {error:'Stripe event ID is required.'};
  return mutate(state=>{const existing=state.stripeEvents.find(item=>item.eventId===eventId);if(existing){if(existing.status==='failed'){existing.status='processing';existing.attemptCount=(existing.attemptCount||1)+1;existing.lastError='';existing.updatedAt=now();return {duplicate:false,retry:true,event:clone(existing)};}return {duplicate:true,event:clone(existing)};}const record={id:store.uid('stripeevt',9),eventId,type:clean(event.type,180),status:'processing',attemptCount:1,object:safeStripeObject(event.data?.object||{}),receivedAt:now(),handledAt:'',lastError:'',resultSummary:'',updatedAt:now()};state.stripeEvents.unshift(record);state.stripeEvents=state.stripeEvents.slice(0,3000);return {duplicate:false,event:clone(record)};},result=>result?.event?{eventType:'stripe_event_received',action:'stripe_event_received',stripeEventId:result.event.eventId,stripeType:result.event.type}:null);
}
async function completeStripeEvent(eventId,input={}){
  return mutate(state=>{const record=state.stripeEvents.find(item=>item.eventId===clean(eventId,240));if(!record)return {error:'Stripe event ledger record not found.'};record.status=oneOf(input.status,STRIPE_EVENT_STATUSES,'handled');record.handledAt=now();record.updatedAt=now();record.resultSummary=clean(input.resultSummary,3000);record.lastError=clean(input.lastError,3000);return {event:clone(record)};},result=>result?.event?{eventType:'stripe_event_completed',action:'stripe_event_completed',stripeEventId:result.event.eventId,status:result.event.status}:null);
}
async function recordBillingIssue(input={}){
  return mutate(state=>{const dedupeKey=clean(input.dedupeKey,300);if(dedupeKey){const existing=state.billingIssues.find(item=>item.dedupeKey===dedupeKey&&!['resolved','closed'].includes(item.status));if(existing){existing.occurrences=(existing.occurrences||1)+1;existing.lastOccurredAt=now();existing.updatedAt=now();return {issue:clone(existing),deduplicated:true};}}const issue={id:store.uid('billingissue',9),dedupeKey,type:clean(input.type,140)||'billing-exception',status:'open',severity:oneOf(input.severity,['low','medium','high','critical'],'medium'),accountId:clean(input.accountId,180),membershipKind:clean(input.membershipKind,80),membershipId:clean(input.membershipId,180),stripeEventId:clean(input.stripeEventId,240),summary:clean(input.summary,3000),ownerNotes:'',resolution:'',occurrences:1,createdAt:now(),lastOccurredAt:now(),updatedAt:now(),resolvedAt:''};state.billingIssues.unshift(issue);state.billingIssues=state.billingIssues.slice(0,1500);return {issue:clone(issue),deduplicated:false};},result=>result?.issue?{eventType:'billing_issue_recorded',action:'billing_issue_recorded',billingIssueId:result.issue.id,severity:result.issue.severity}:null);
}
async function updateBillingIssue(id,input={}){return mutate(state=>{const issue=state.billingIssues.find(item=>item.id===id);if(!issue)return {error:'Billing issue not found.'};issue.status=oneOf(input.status,ISSUE_STATUSES,issue.status);issue.severity=oneOf(input.severity,['low','medium','high','critical'],issue.severity);issue.ownerNotes=clean(input.ownerNotes,5000);issue.resolution=clean(input.resolution,5000);issue.updatedAt=now();if(['resolved','closed'].includes(issue.status))issue.resolvedAt=now();return {issue:clone(issue)};},result=>result?.issue?{eventType:'billing_issue_updated',action:'billing_issue_updated',billingIssueId:result.issue.id,status:result.issue.status}:null);}
async function createIncident(input={}){return mutate(state=>{const incident={id:store.uid('incident',9),title:clean(input.title,240),category:clean(input.category,160),severity:oneOf(input.severity,['low','medium','high','critical'],'medium'),status:oneOf(input.status,INCIDENT_STATUSES,'draft'),summary:clean(input.summary,5000),affectedSystems:list(input.affectedSystems,100,200),containment:clean(input.containment,5000),recovery:clean(input.recovery,5000),owner:clean(input.owner,180),createdAt:now(),updatedAt:now(),resolvedAt:''};if(!incident.title)return {error:'Incident title is required.'};state.incidents.unshift(incident);state.incidents=state.incidents.slice(0,1000);return {incident:clone(incident)};},result=>result?.incident?{eventType:'pilot_incident_created',action:'pilot_incident_created',incidentId:result.incident.id,severity:result.incident.severity}:null);}
async function updateIncident(id,input={}){return mutate(state=>{const incident=state.incidents.find(item=>item.id===id);if(!incident)return {error:'Incident record not found.'};for(const field of ['title','category','summary','containment','recovery','owner'])if(Object.prototype.hasOwnProperty.call(input,field))incident[field]=clean(input[field],['summary','containment','recovery'].includes(field)?5000:240);if(Object.prototype.hasOwnProperty.call(input,'affectedSystems'))incident.affectedSystems=list(input.affectedSystems,100,200);incident.severity=oneOf(input.severity,['low','medium','high','critical'],incident.severity);incident.status=oneOf(input.status,INCIDENT_STATUSES,incident.status);incident.updatedAt=now();if(['resolved','closed'].includes(incident.status))incident.resolvedAt=now();return {incident:clone(incident)};},result=>result?.incident?{eventType:'pilot_incident_updated',action:'pilot_incident_updated',incidentId:result.incident.id,status:result.incident.status}:null);}
async function recordOwnerApproval(input={}){return mutate(state=>{const scope=clean(input.scope,240);const approvalType=clean(input.approvalType,160);if(!scope||!approvalType)return {error:'Approval type and scope are required.'};const current=state.ownerApprovals.find(item=>item.scope===scope&&item.approvalType===approvalType&&item.status==='approved');if(current&&input.status==='approved')return {approval:clone(current),alreadyApproved:true};const approval={id:store.uid('approval',9),approvalType,scope,status:oneOf(input.status,APPROVAL_STATUSES,'pending'),decision:clean(input.decision,3000),conditions:list(input.conditions,100,300),evidenceReferences:list(input.evidenceReferences,100,500),approvedBy:clean(input.approvedBy,180),effectiveAt:clean(input.effectiveAt,100)||now(),expiresAt:clean(input.expiresAt,100),createdAt:now(),updatedAt:now()};state.ownerApprovals.unshift(approval);state.ownerApprovals=state.ownerApprovals.slice(0,1500);return {approval:clone(approval)};},result=>result?.approval?{eventType:'owner_approval_recorded',action:'owner_approval_recorded',approvalId:result.approval.id,approvalType:result.approval.approvalType,status:result.approval.status}:null);}
async function recordEnvironmentSnapshot(input={}){return mutate(state=>{const snapshot={id:store.uid('readiness',9),label:clean(input.label,220)||'Paid pilot operating-readiness snapshot',checks:Array.isArray(input.checks)?input.checks.slice(0,200).map(item=>({key:clean(item.key,140),label:clean(item.label,300),ready:Boolean(item.ready),status:clean(item.status,140),detail:clean(item.detail,1200)})):[],source:clean(input.source,120),createdAt:now()};state.environmentSnapshots.unshift(snapshot);state.environmentSnapshots=state.environmentSnapshots.slice(0,200);return {snapshot:clone(snapshot)};},result=>result?.snapshot?{eventType:'operating_readiness_snapshot_recorded',action:'operating_readiness_snapshot_recorded',snapshotId:result.snapshot.id}:null);}
function summary(state=readState()){const openBilling=state.billingIssues.filter(item=>!['resolved','closed'].includes(item.status));const openIncidents=state.incidents.filter(item=>!['resolved','closed'].includes(item.status));return {stripeEventCount:state.stripeEvents.length,failedStripeEvents:state.stripeEvents.filter(item=>item.status==='failed').length,openBillingIssues:openBilling.length,criticalBillingIssues:openBilling.filter(item=>item.severity==='critical').length,openIncidents:openIncidents.length,criticalIncidents:openIncidents.filter(item=>item.severity==='critical').length,approvedOwnerDecisions:state.ownerApprovals.filter(item=>item.status==='approved').length,latestSnapshotAt:state.environmentSnapshots[0]?.createdAt||''};}
function ownerView(state=readState()){return {standardVersion:STANDARD_VERSION,summary:summary(state),stripeEvents:clone(state.stripeEvents),billingIssues:clone(state.billingIssues),incidents:clone(state.incidents),ownerApprovals:clone(state.ownerApprovals),environmentSnapshots:clone(state.environmentSnapshots),stateRevision:state.stateRevision,updatedAt:state.updatedAt};}
function exportMarkdown(){const data=ownerView();return ['# Paid Pilot Operating Evidence','','Standard version: '+STANDARD_VERSION,'',`- Stripe events recorded: ${data.summary.stripeEventCount}`,`- Failed Stripe events: ${data.summary.failedStripeEvents}`,`- Open billing issues: ${data.summary.openBillingIssues}`,`- Open incidents: ${data.summary.openIncidents}`,`- Owner approvals: ${data.summary.approvedOwnerDecisions}`,'','## Billing issues',...data.billingIssues.map(item=>`- ${item.id} — ${item.severity} — ${item.status} — ${item.summary}`),'','## Incidents',...data.incidents.map(item=>`- ${item.id} — ${item.severity} — ${item.status} — ${item.title}`),'','## Owner approvals',...data.ownerApprovals.map(item=>`- ${item.id} — ${item.approvalType} — ${item.scope} — ${item.status}`),''].join('\n');}
module.exports={STORE_KEY,STANDARD_VERSION,readState,ownerView,summary,exportMarkdown,beginStripeEvent,completeStripeEvent,recordBillingIssue,updateBillingIssue,createIncident,updateIncident,recordOwnerApproval,recordEnvironmentSnapshot};
