'use strict';

const store=require('./store');
const marketplace=require('./professionalMarketplace');
const {resolveProfessionalPortalId}=require('../data/professionalPortalAliases');
const {PORTAL_PROFESSIONAL_CONTRACT_VERSION}=require('../data/professionalNetworkStandard');
const {PORTAL_PROFILE_STANDARD_VERSION,getInitialPortalProfileStandard,listInitialPortalProfileStandards,isInitialPortalProfilePortal}=require('../data/initialPortalProfileStandards');

const STORE_KEY='portalPresenceManagement.json';
const SCHEMA_VERSION='1.0.0';
const REVIEW_STATES=['draft','submitted','changes-pending-review','approved','changes-requested','rejected','withdrawn'];
const PARTICIPATION_STATES=['draft','application-submitted','specialty-approved','export-withheld','export-eligible','exported','update-pending','suppressed','removed'];
const CHECK_STATES=['NOT_TESTED','PASS','FAIL','BLOCKED','NOT_APPLICABLE'];
const MATURITY_STATES=['D0_NOT_STARTED','D1_CONTRACT_IDENTIFIED','D2_SCHEMAS_FIXTURES_AND_TESTS_PASS','D3_ADAPTER_TESTS_PASS','D4_STAGING_VERIFIED','D5_PRODUCTION_VERIFIED'];
const REQUIRED_ACCEPTANCE_CHECKS=['canonicalPage','specialtySearch','claimLink','manageLink','correctionRemoval','mobile','accessibility','importReceipt','lastKnownGood','rollback'];

function clean(value,max=2000){return String(value==null?'':value).trim().slice(0,max);}
function list(value,maxItems=50,maxLength=300){const source=Array.isArray(value)?value:String(value||'').split(/\r?\n|,/);return [...new Set(source.map(item=>clean(item,maxLength)).filter(Boolean))].slice(0,maxItems);}
function now(){return store.now();}
function clone(value){return JSON.parse(JSON.stringify(value));}
function oneOf(value,allowed,fallback){return allowed.includes(value)?value:fallback;}
function targetKey(kind,id,portalId){return `${kind}:${id}:${portalId}`;}
function initialState(){return {schemaVersion:SCHEMA_VERSION,standardVersion:PORTAL_PROFILE_STANDARD_VERSION,contractVersion:PORTAL_PROFESSIONAL_CONTRACT_VERSION,portalProfiles:[],acceptanceRecords:[],updatedAt:''};}
function normalizeProfile(row={}){
  return {
    id:clean(row.id,500),targetKind:row.targetKind==='firm'?'firm':'professional',targetId:clean(row.targetId,220),portalId:clean(row.portalId,180),
    profileRevision:Math.max(1,Number(row.profileRevision)||1),submittedRevision:Math.max(0,Number(row.submittedRevision)||0),reviewedRevision:Math.max(0,Number(row.reviewedRevision)||0),
    reviewStatus:oneOf(row.reviewStatus,REVIEW_STATES,'draft'),participationStatus:oneOf(row.participationStatus,PARTICIPATION_STATES,'draft'),
    specialtyBiography:clean(row.specialtyBiography,6000),practiceAreas:list(row.practiceAreas,50,220),matterTypes:list(row.matterTypes,50,220),geographicServiceAreas:list(row.geographicServiceAreas,100,220),
    languages:list(row.languages,40,120),consultationPreferences:list(row.consultationPreferences,30,180),contactPreferences:list(row.contactPreferences,30,180),qualifications:list(row.qualifications,50,500),specialtyEvidence:list(row.specialtyEvidence,50,800),
    centralSourceRevision:Math.max(1,Number(row.centralSourceRevision)||1),submittedAt:clean(row.submittedAt,80),reviewedAt:clean(row.reviewedAt,80),reviewedBy:clean(row.reviewedBy,120),reviewNotes:clean(row.reviewNotes,4000),
    createdAt:clean(row.createdAt,80),updatedAt:clean(row.updatedAt,80),updatedBy:clean(row.updatedBy,120)
  };
}
function normalizeChecks(checks={}){const out={};for(const key of [...REQUIRED_ACCEPTANCE_CHECKS,'reciprocalFirmLink'])out[key]=oneOf(checks[key],CHECK_STATES,'NOT_TESTED');return out;}
function normalizeAcceptance(row={}){
  return {
    id:clean(row.id,500),targetKind:row.targetKind==='firm'?'firm':'professional',targetId:clean(row.targetId,220),portalId:clean(row.portalId,180),
    maturity:oneOf(row.maturity,MATURITY_STATES,'D0_NOT_STARTED'),acceptanceStatus:clean(row.acceptanceStatus,120)||'NOT_STARTED',checks:normalizeChecks(row.checks),
    localProfileId:clean(row.localProfileId,220),publicProfileUrl:clean(row.publicProfileUrl,1500),relatedFirmProfileUrl:clean(row.relatedFirmProfileUrl,1500),
    acceptedCentralSourceRevision:Math.max(0,Number(row.acceptedCentralSourceRevision)||0),acceptedPortalProfileRevision:Math.max(0,Number(row.acceptedPortalProfileRevision)||0),
    importReceiptId:clean(row.importReceiptId,220),importReceiptDigest:clean(row.importReceiptDigest,128),adapterVersion:clean(row.adapterVersion,120),contractVersion:clean(row.contractVersion,120)||PORTAL_PROFESSIONAL_CONTRACT_VERSION,
    lastKnownGoodReference:clean(row.lastKnownGoodReference,1000),rollbackReference:clean(row.rollbackReference,1000),evidenceRefs:list(row.evidenceRefs,100,1000),
    productionActivationAuthorized:Boolean(row.productionActivationAuthorized),ownerApprovedAt:clean(row.ownerApprovedAt,80),ownerApprovedBy:clean(row.ownerApprovedBy,120),notes:clean(row.notes,5000),createdAt:clean(row.createdAt,80),updatedAt:clean(row.updatedAt,80)
  };
}
function normalize(raw){const source=raw&&typeof raw==='object'&&!Array.isArray(raw)?raw:{};return {...initialState(),...source,schemaVersion:SCHEMA_VERSION,standardVersion:PORTAL_PROFILE_STANDARD_VERSION,contractVersion:PORTAL_PROFESSIONAL_CONTRACT_VERSION,portalProfiles:Array.isArray(source.portalProfiles)?source.portalProfiles.map(normalizeProfile):[],acceptanceRecords:Array.isArray(source.acceptanceRecords)?source.acceptanceRecords.map(normalizeAcceptance):[]};}
function readState(){return normalize(store.readJson(STORE_KEY,initialState()));}
function writeState(state){const next={...normalize(state),updatedAt:now()};store.writeJson(STORE_KEY,next);return next;}
function getTarget(kind,id){const owner=marketplace.getOwnerData();return kind==='firm'?(owner.firms||[]).find(row=>row.id===id):(owner.professionals||[]).find(row=>row.id===id);}
function canonicalRequestedPortals(target){const ids=new Set();for(const raw of target?.portalEligibility||[]){const resolved=resolveProfessionalPortalId(raw);if(resolved.canonicalPortalId)ids.add(resolved.canonicalPortalId);}return ids;}
function centralRevision(target){return Math.max(1,Number(target?.profileRevision)||1);}
function blankProfile(kind,id,portalId,target){const timestamp=now();return normalizeProfile({id:targetKey(kind,id,portalId),targetKind:kind,targetId:id,portalId,profileRevision:1,centralSourceRevision:centralRevision(target),createdAt:timestamp,updatedAt:timestamp,updatedBy:'system'});}
function ensureProfile(state,kind,id,portalId,target){let row=state.portalProfiles.find(item=>item.id===targetKey(kind,id,portalId));if(!row){row=blankProfile(kind,id,portalId,target);state.portalProfiles.push(row);}return row;}
function validateTargetAndPortal(kind,id,portalId){
  if(!['professional','firm'].includes(kind))return {error:'Target kind must be professional or firm.'};
  const standard=getInitialPortalProfileStandard(portalId);if(!standard)return {error:'Portal-specific profile management is limited to the four initial launch portals in this release.'};
  const target=getTarget(kind,id);if(!target)return {error:`${kind==='firm'?'Firm':'Professional'} record not found.`};
  const requested=canonicalRequestedPortals(target);if(!requested.has(portalId))return {error:'Select this portal in the central profile before creating its specialty profile section.'};
  return {target,standard};
}
function readiness(row,standard){
  const missing=[];if(row.specialtyBiography.length<80)missing.push('Specialty biography of at least 80 characters');if(!row.practiceAreas.length)missing.push('At least one relevant practice area');if(row.targetKind==='professional'&&!row.matterTypes.length)missing.push('At least one matter type handled');if(!row.geographicServiceAreas.length)missing.push('At least one geographic service area');
  const excluded=[];for(const value of row.matterTypes){for(const pattern of standard.excludedMatterPatterns||[])if(pattern.test(value))excluded.push(value);}
  return {readyForReview:missing.length===0&&excluded.length===0,missingRequired:missing,excludedMatterTypes:[...new Set(excluded)],profileRevision:row.profileRevision,submittedRevision:row.submittedRevision,reviewedRevision:row.reviewedRevision,currentRevisionSubmitted:row.submittedRevision===row.profileRevision&&['submitted','approved'].includes(row.reviewStatus),currentRevisionApproved:row.reviewedRevision===row.profileRevision&&row.reviewStatus==='approved'};
}
function publicRecord(row){const standard=getInitialPortalProfileStandard(row.portalId);return {...clone(row),portal:standard?{portalId:standard.portalId,name:standard.name,domain:standard.domain,allowedMatterTypes:standard.allowedMatterTypes,publicProfileAuthority:standard.publicProfileAuthority}:null,readiness:standard?readiness(row,standard):null,basicProfileControlPriceCents:0,paymentRequiredForEdit:false,publicProfileAuthority:'destination micro-portal'};}
function listProfilesForTargets(professionalIds=[],firmIds=[]){const state=readState();const allowed=new Set([...professionalIds.map(id=>`professional:${id}`),...firmIds.map(id=>`firm:${id}`)]);return state.portalProfiles.filter(row=>allowed.has(`${row.targetKind}:${row.targetId}`)).map(publicRecord);}
function viewForAccount(account){const professionalIds=account?.professionalIds||[];const firmIds=account?.firmIds||[];const state=readState();const profiles=listProfilesForTargets(professionalIds,firmIds);const acceptances=state.acceptanceRecords.filter(row=>(row.targetKind==='professional'?professionalIds:firmIds).includes(row.targetId)).map(clone);return {standardVersion:PORTAL_PROFILE_STANDARD_VERSION,contractVersion:PORTAL_PROFESSIONAL_CONTRACT_VERSION,portals:listInitialPortalProfileStandards().map(row=>({...row,excludedMatterPatterns:undefined})),profiles,acceptances,freeBasicProfileControl:true,automaticPortalWrites:false,livePortalConnections:false};}
function updatePortalProfile(kind,id,portalId,input={},actor='professional-account'){
  const validation=validateTargetAndPortal(kind,id,portalId);if(validation.error)return validation;const {target,standard}=validation;const state=readState();const row=ensureProfile(state,kind,id,portalId,target);
  if(input.expectedRevision!=null&&Number(input.expectedRevision)!==Number(row.profileRevision))return {conflict:true,error:'This portal-specific profile changed in another session. Refresh before saving so newer information is not overwritten.',currentRevision:row.profileRevision};
  const next={...row,specialtyBiography:clean(input.specialtyBiography,row.targetKind==='firm'?6000:6000),practiceAreas:list(input.practiceAreas,50,220),matterTypes:row.targetKind==='firm'?[]:list(input.matterTypes,50,220),geographicServiceAreas:list(input.geographicServiceAreas,100,220),languages:list(input.languages,40,120),consultationPreferences:list(input.consultationPreferences,30,180),contactPreferences:list(input.contactPreferences,30,180),qualifications:list(input.qualifications,50,500),specialtyEvidence:list(input.specialtyEvidence,50,800),centralSourceRevision:centralRevision(target)};
  const comparable=key=>JSON.stringify(row[key])!==JSON.stringify(next[key]);const changed=['specialtyBiography','practiceAreas','matterTypes','geographicServiceAreas','languages','consultationPreferences','contactPreferences','qualifications','specialtyEvidence','centralSourceRevision'].some(comparable);
  if(!changed)return {profile:publicRecord(row),unchanged:true,message:'No portal-specific changes were detected.'};
  next.profileRevision=row.profileRevision+1;next.updatedAt=now();next.updatedBy=clean(actor,120)||'professional-account';if(['submitted','approved'].includes(row.reviewStatus))next.reviewStatus='changes-pending-review';if(row.reviewStatus==='approved')next.participationStatus='update-pending';
  const index=state.portalProfiles.findIndex(item=>item.id===row.id);state.portalProfiles[index]=normalizeProfile(next);writeState(state);store.addAudit({actor:clean(actor,120)||'professional-account',action:'portal_specific_profile_updated',details:{targetKind:kind,targetId:id,portalId,profileRevision:next.profileRevision,paymentRequired:false,automaticPortalWrite:false}});
  return {profile:publicRecord(state.portalProfiles[index]),message:`${standard.name} specialty information saved privately. Review and portal publication remain separate.`};
}
function submitPortalProfile(kind,id,portalId,expectedRevision,actor='professional-account'){
  const validation=validateTargetAndPortal(kind,id,portalId);if(validation.error)return validation;const {target,standard}=validation;const state=readState();const row=ensureProfile(state,kind,id,portalId,target);if(expectedRevision!=null&&Number(expectedRevision)!==Number(row.profileRevision))return {conflict:true,error:'The portal-specific revision changed before submission. Refresh and submit the current revision.',currentRevision:row.profileRevision};
  const check=readiness(row,standard);if(!check.readyForReview){const excluded=check.excludedMatterTypes.length?' Workers’ Compensation and Medical Malpractice must use separate portal paths.':'';return {error:`Complete the required specialty fields before submission.${excluded}`,readiness:check};}
  row.submittedRevision=row.profileRevision;row.reviewStatus='submitted';row.participationStatus='application-submitted';row.submittedAt=now();row.updatedAt=row.submittedAt;row.updatedBy=clean(actor,120)||'professional-account';writeState(state);store.addAudit({actor:clean(actor,120)||'professional-account',action:'portal_specific_profile_submitted',details:{targetKind:kind,targetId:id,portalId,submittedRevision:row.submittedRevision,paymentRequired:false,automaticPortalWrite:false}});return {profile:publicRecord(row),message:`The exact ${standard.name} specialty-profile revision was submitted for review. Nothing was published or charged.`};
}
function ownerReviewPortalProfile(kind,id,portalId,input={},actor='owner-control-center'){
  const validation=validateTargetAndPortal(kind,id,portalId);if(validation.error)return validation;const {target,standard}=validation;const state=readState();const row=ensureProfile(state,kind,id,portalId,target);const expected=Math.max(0,Number(input.expectedRevision)||0);if(expected!==row.profileRevision)return {conflict:true,error:'Owner review must target the exact current portal-specific revision.',currentRevision:row.profileRevision};if(row.submittedRevision!==row.profileRevision)return {error:'The current portal-specific revision has not been submitted for review.'};
  const decision=oneOf(input.decision,['approved','changes-requested','rejected'],'');if(!decision)return {error:'Choose approved, changes-requested, or rejected.'};const check=readiness(row,standard);if(decision==='approved'&&!check.readyForReview)return {error:'The specialty profile does not meet the current review requirements.',readiness:check};
  row.reviewStatus=decision;row.reviewedRevision=decision==='approved'?row.profileRevision:0;row.participationStatus=decision==='approved'?'specialty-approved':'draft';row.reviewedAt=now();row.reviewedBy=clean(actor,120)||'owner-control-center';row.reviewNotes=clean(input.reviewNotes,4000);row.centralSourceRevision=centralRevision(target);row.updatedAt=row.reviewedAt;row.updatedBy=row.reviewedBy;writeState(state);store.addAudit({actor:row.reviewedBy,action:'portal_specific_profile_reviewed',details:{targetKind:kind,targetId:id,portalId,decision,reviewedRevision:row.reviewedRevision,centralSourceRevision:row.centralSourceRevision,automaticPortalWrite:false}});return {profile:publicRecord(row),message:`${standard.name} specialty-profile review recorded for exact revision ${row.profileRevision}. Export eligibility remains separately controlled.`};
}
function approvedProjection(kind,id,portalId,currentCentralRevision){const state=readState();const row=state.portalProfiles.find(item=>item.id===targetKey(kind,id,portalId));if(!row)return {state:'NO_PORTAL_SPECIFIC_PROFILE',profile:null};if(row.reviewStatus!=='approved'||row.reviewedRevision!==row.profileRevision)return {state:'WITHHELD_PENDING_PORTAL_PROFILE_APPROVAL',profile:null,portalProfileRevision:row.profileRevision,reviewStatus:row.reviewStatus};if(Number(row.centralSourceRevision)!==Number(currentCentralRevision))return {state:'WITHHELD_STALE_CENTRAL_SOURCE_REVISION',profile:null,portalProfileRevision:row.profileRevision,approvedCentralSourceRevision:row.centralSourceRevision,currentCentralSourceRevision:currentCentralRevision};return {state:'APPROVED_EXACT_REVISION',portalProfileRevision:row.profileRevision,approvedCentralSourceRevision:row.centralSourceRevision,profile:{specialtyBiography:row.specialtyBiography,practiceAreas:[...row.practiceAreas],matterTypes:[...row.matterTypes],geographicServiceAreas:[...row.geographicServiceAreas],languages:[...row.languages],consultationPreferences:[...row.consultationPreferences],contactPreferences:[...row.contactPreferences],qualifications:[...row.qualifications],specialtyEvidence:[...row.specialtyEvidence]}};}
function safePortalUrl(value,portalId){const standard=getInitialPortalProfileStandard(portalId);if(!value)return '';try{const url=new URL(value);const host=url.hostname.toLowerCase().replace(/^www\./,'');if(url.protocol!=='https:'||host!==standard.domain)return '';return url.toString();}catch{return '';}}
function acceptanceStatus(record,target,portalProfile){const checks=record.checks||{};if(Object.values(checks).some(value=>value==='FAIL'||value==='BLOCKED'))return 'BLOCKED';const required=[...REQUIRED_ACCEPTANCE_CHECKS];if(target?.firmId||record.targetKind==='firm')required.push('reciprocalFirmLink');const allPass=required.every(key=>['PASS','NOT_APPLICABLE'].includes(checks[key]));if(record.maturity==='D5_PRODUCTION_VERIFIED'&&allPass&&record.productionActivationAuthorized)return 'PRODUCTION_ACTIVE';if(record.maturity==='D4_STAGING_VERIFIED'&&allPass&&record.localProfileId&&record.publicProfileUrl&&record.importReceiptId&&/^[a-f0-9]{64}$/i.test(record.importReceiptDigest)&&record.lastKnownGoodReference&&record.rollbackReference&&record.evidenceRefs?.length&&record.acceptedCentralSourceRevision===centralRevision(target)&&portalProfile?.reviewStatus==='approved'&&portalProfile.reviewedRevision===portalProfile.profileRevision&&record.acceptedPortalProfileRevision===portalProfile.profileRevision)return 'STAGING_ACCEPTED';if(record.maturity==='D3_ADAPTER_TESTS_PASS')return 'LOCAL_ADAPTER_ACCEPTED';if(Object.values(checks).some(value=>value==='PASS'))return 'IN_PROGRESS';return 'NOT_STARTED';}
function upsertAcceptance(kind,id,portalId,input={},actor='owner-control-center'){
  const validation=validateTargetAndPortal(kind,id,portalId);if(validation.error)return validation;const {target}=validation;const state=readState();const key=targetKey(kind,id,portalId);const current=state.acceptanceRecords.find(row=>row.id===key)||normalizeAcceptance({id:key,targetKind:kind,targetId:id,portalId,createdAt:now()});const portalProfile=state.portalProfiles.find(row=>row.id===key);
  const publicProfileUrl=input.publicProfileUrl==null?current.publicProfileUrl:safePortalUrl(input.publicProfileUrl,portalId);if(input.publicProfileUrl&&!publicProfileUrl)return {error:'Public profile URL must use HTTPS and the exact destination portal domain.'};const relatedFirmProfileUrl=input.relatedFirmProfileUrl==null?current.relatedFirmProfileUrl:safePortalUrl(input.relatedFirmProfileUrl,portalId);if(input.relatedFirmProfileUrl&&!relatedFirmProfileUrl)return {error:'Related firm profile URL must use HTTPS and the exact destination portal domain.'};
  const next=normalizeAcceptance({...current,...input,id:key,targetKind:kind,targetId:id,portalId,checks:{...current.checks,...(input.checks||{})},publicProfileUrl,relatedFirmProfileUrl,acceptedCentralSourceRevision:input.acceptedCentralSourceRevision??current.acceptedCentralSourceRevision,acceptedPortalProfileRevision:input.acceptedPortalProfileRevision??current.acceptedPortalProfileRevision,updatedAt:now()});
  if(next.maturity==='D4_STAGING_VERIFIED'){
    const tempStatus=acceptanceStatus(next,target,portalProfile);if(tempStatus!=='STAGING_ACCEPTED')return {error:'D4 staging requires exact accepted revisions, all required checks, an import receipt, last-known-good evidence, and rollback evidence.',acceptanceStatus:tempStatus};
  }
  if(next.maturity==='D5_PRODUCTION_VERIFIED'){
    const enabled=String(process.env.PORTAL_PRODUCTION_ACTIVATION_ENABLED||'').toLowerCase()==='true';if(!enabled||input.confirmation!=='ACTIVATE PORTAL PROFILE PRODUCTION')return {error:'Production activation is disabled. D5 requires the server activation control and exact confirmation.'};next.productionActivationAuthorized=true;next.ownerApprovedAt=now();next.ownerApprovedBy=clean(actor,120)||'owner-control-center';
  } else next.productionActivationAuthorized=false;
  next.acceptanceStatus=acceptanceStatus(next,target,portalProfile);const index=state.acceptanceRecords.findIndex(row=>row.id===key);if(index>=0)state.acceptanceRecords[index]=next;else state.acceptanceRecords.push(next);writeState(state);store.addAudit({actor:clean(actor,120)||'owner-control-center',action:'portal_profile_acceptance_updated',details:{targetKind:kind,targetId:id,portalId,maturity:next.maturity,acceptanceStatus:next.acceptanceStatus,productionActivationAuthorized:next.productionActivationAuthorized}});return {acceptance:clone(next),message:'Portal-profile acceptance record saved. No portal write or deployment occurred.'};
}
function ownerView(){const state=readState();const owner=marketplace.getOwnerData();return {schemaVersion:SCHEMA_VERSION,standardVersion:PORTAL_PROFILE_STANDARD_VERSION,contractVersion:PORTAL_PROFESSIONAL_CONTRACT_VERSION,portals:listInitialPortalProfileStandards().map(row=>({...row,excludedMatterPatterns:undefined})),portalProfiles:state.portalProfiles.map(publicRecord),acceptanceRecords:state.acceptanceRecords.map(row=>{const target=row.targetKind==='firm'?(owner.firms||[]).find(x=>x.id===row.targetId):(owner.professionals||[]).find(x=>x.id===row.targetId);const portalProfile=state.portalProfiles.find(x=>x.id===row.id);return {...clone(row),acceptanceStatus:acceptanceStatus(row,target,portalProfile)};}),targets:{professionals:(owner.professionals||[]).map(row=>({id:row.id,name:row.displayName,profileRevision:centralRevision(row),firmId:row.firmId||'',portalIds:[...canonicalRequestedPortals(row)].filter(isInitialPortalProfilePortal)})),firms:(owner.firms||[]).map(row=>({id:row.id,name:row.name,profileRevision:centralRevision(row),portalIds:[...canonicalRequestedPortals(row)].filter(isInitialPortalProfilePortal)}))},automaticPortalWrites:false,livePortalConnections:false,productionActivationEnabled:String(process.env.PORTAL_PRODUCTION_ACTIVATION_ENABLED||'').toLowerCase()==='true'};}

module.exports={STORE_KEY,SCHEMA_VERSION,PORTAL_PROFILE_STANDARD_VERSION,REVIEW_STATES,PARTICIPATION_STATES,CHECK_STATES,MATURITY_STATES,REQUIRED_ACCEPTANCE_CHECKS,readState,viewForAccount,listProfilesForTargets,updatePortalProfile,submitPortalProfile,ownerReviewPortalProfile,approvedProjection,upsertAcceptance,ownerView,readiness};
