'use strict';
const fs=require('fs');const path=require('path');const ROOT=path.join(__dirname,'..');
const contract=require('../RELEASE_EVIDENCE_COVERAGE_CONTRACT_V1.7.83.json');const defaultPlan=require('../CONTINUOUS_SELF_IMPROVEMENT_AND_INNOVATION_PLAN_V1.7.83.json');const defaultReport=require('../PRODUCT_AND_PROMPT_DUAL_IMPROVEMENT_REPORT_V1.7.83.json');const defaultLearning=require('../CROSS_VERSION_LEARNING_LEDGER_V1.7.83.json');const defaultNext=require('../NEXT_VERSION_IMPROVEMENT_LIST.json');const defaultPkg=require('../package.json');const defaultManifest=require('../portal-manifest.json');const defaultTruth=require('../CURRENT_RELEASE_TRUTH_V1.7.83.json');
function clone(v){return JSON.parse(JSON.stringify(v));}function text(v){return String(v??'').trim();}function exists(name){return typeof name==='string'&&name.length>0&&fs.existsSync(path.join(ROOT,name));}
function referencedFiles(report){const out=[];for(const row of report.product_platform_improvements||[])out.push(...(row.affected_files_records_or_systems||[]),...(row.tests_and_acceptance_evidence||[]));for(const row of report.builder_prompt_system_improvements||[])out.push(...(row.affected_files_or_artifacts||[]),...(row.tests_and_acceptance_evidence||[]));return[...new Set(out)];}
function referencedTests(report){return referencedFiles(report).filter(x=>/^tests\/.+\.test\.js$/.test(x));}
function validate(overrides={}){const pkg=overrides.pkg||defaultPkg,manifest=overrides.manifest||defaultManifest,plan=overrides.plan||defaultPlan,report=overrides.report||defaultReport,learning=overrides.learning||defaultLearning,next=overrides.next||defaultNext,truth=overrides.truth||defaultTruth,c=overrides.contract||contract;const errors=[];
 if(c.release_version!=='1.7.83'||pkg.version!=='1.7.83'||manifest.currentDevelopmentVersion!=='1.7.83'||plan.product?.target_version!=='1.7.83'||report.product?.version!=='1.7.83'||learning.product?.current_version!=='1.7.83'||next.releaseVersion!=='1.7.83'||truth.releaseVersion!=='1.7.83')errors.push('current-version');
 if(plan.product?.starting_version!=='1.7.82'||plan.product?.starting_artifact_sha256!==c.source_artifact.sha256||next.baselineArtifact!==c.source_artifact.filename||next.baselineSha256!==c.source_artifact.sha256||truth.selectedBase?.sha256!==c.source_artifact.sha256)errors.push('exact-source-identity');
 if(plan.governing_packet?.sha256!==c.governing_packet_sha256||truth.currentPromptPack?.packetSha256!==c.governing_packet_sha256)errors.push('governing-packet');
 const commandCount=String(pkg.scripts?.test||'').split(' && ').filter(Boolean).length;if(commandCount!==c.expected_dependency_independent_commands||manifest.dependencyIndependentTestParts!==c.expected_dependency_independent_commands||manifest.testSuiteParts!==c.expected_total_readiness_parts)errors.push('test-counts');
 const refs=referencedFiles(report);for(const file of refs)if(!exists(file))errors.push(`missing-evidence:${file}`);const testCommand=String(pkg.scripts?.test||'');for(const test of referencedTests(report))if(!testCommand.includes(`node ${test}`))errors.push(`test-not-in-suite:${test}`);
 const currentIds=new Set((next.items||[]).map(x=>x.id));const resolved=new Set(c.resolved_prior_backlog_ids||[]);for(const id of c.required_prior_backlog_ids||[])if(!currentIds.has(id)&&!resolved.has(id))errors.push(`dropped-backlog:${id}`);if((next.items||[]).length<(c.required_prior_backlog_ids||[]).length)errors.push('backlog-count-regression');
 const limitationIds=new Set((report.prior_limitations_reviewed||[]).filter(x=>text(x.disposition)&&text(x.evidence)).map(x=>x.id));for(const id of c.required_prior_limitation_ids||[])if(!limitationIds.has(id))errors.push(`unreviewed-prior-limitation:${id}`);for(const file of c.required_current_evidence_files||[])if(!exists(file))errors.push(`missing-current-record:${file}`);
 for(const lesson of learning.lessons||[])for(const field of ['source_version_or_wave','test_or_evidence_that_revealed_it','product_change_made','builder_prompt_system_change_made','future_candidate_selection_effect','future_testing_or_recovery_effect'])if(!text(lesson[field]))errors.push(`learning:${lesson.lesson_id||'unknown'}:${field}`);
 if(truth.sourcePackage?.filename!=='smarter-justice-v1.7.83.zip'||truth.sourcePackage?.dependencyIndependentParts!==c.expected_dependency_independent_commands)errors.push('source-package-truth');if(truth.finalArchive?.sha256!==null||truth.finalArchive?.sizeBytes!==null||truth.finalArchive?.identityState!=='REPORTED_AFTER_IMMUTABLE_PACKAGING')errors.push('detached-final-boundary');if(truth.candidateArtifact?.sha256&&truth.candidateArtifact.sha256===c.source_artifact.sha256)errors.push('candidate-source-sha-reuse');if(truth.candidateArtifact?.filename!=='smarter-justice-v1.7.83-candidate-a.zip')errors.push('candidate-filename');if(report.hard_constraints_preserved!==true||plan.hard_constraints_preserved!==true)errors.push('hard-constraints');if(truth.deploymentAuthorized!==false||truth.production?.deploymentAuthorized!==false||manifest.sensitiveTrafficApproved!==false)errors.push('closed-gates');
 return{ok:errors.length===0,errors,currentVersion:'1.7.83',sourceVersion:'1.7.82',referencedFileCount:refs.length,referencedTestCount:referencedTests(report).length,requiredBacklogCount:(c.required_prior_backlog_ids||[]).length,currentBacklogCount:(next.items||[]).length,priorLimitationsReviewed:limitationIds.size,deploymentAuthorized:false,productionRequestSent:false};}
function ownerView(){return{contract:clone(contract),validation:validate(),deploymentAuthorized:false,productionRequestSent:false};}module.exports={referencedFiles,referencedTests,validate,ownerView};
