'use strict';
const data=require('../data/reusableBuildGovernanceV1775');
const ownerActionReadiness=require('./ownerActionReadiness');
const portalAuthorityDiscovery=require('./portalAuthorityDiscovery');
const commercialTerms=require('./commercialTerms');
const publicFreemium=require('./publicFreemium');
const fifthPassGovernance=require('./fifthPassGovernance');
const eighthPassGovernance=require('./eighthPassGovernance');
const coordinatedPromptPack=require('./coordinatedPromptPack');
const professionalIdentityEvidenceRegistry=require('./professionalIdentityEvidenceRegistry');
function clone(v){return JSON.parse(JSON.stringify(v));}
function validate(){const errors=[];const i=data.intake,l=data.launchMatrix,o=data.ownerActions,g=data.learning,c=data.commercial,m=data.matterAi,n=data.newestLearning,a=ownerActionReadiness.validate(),p=portalAuthorityDiscovery.validate(),ct=commercialTerms.validate(),f=publicFreemium.validate(),e=eighthPassGovernance.validate(),pack=coordinatedPromptPack.validate(),registry=professionalIdentityEvidenceRegistry.validate();
 if(i.releaseVersion!=='1.7.75'||i.implementationTruthSource!=='smarter-justice-v1.7.73.zip'||i.nextVersionDerived!=='1.7.75')errors.push('intake-version'); if(!i.prompt?.openingMarkerVerified||!i.prompt?.finalMarkerVerified)errors.push('prompt-integrity'); if(i.prompt?.sha256!=='5dad361bae18b25dc8193ce32ca4263a72b12ce90316d6b97dbd191ce2b74223')errors.push('prompt-sha'); if(i.durableRuleCount!==86||i.currentPackId!=='SJP-2026-08-02-C15-P37-D11-V13'||i.canonicalPackCommitProven!==false)errors.push('pack-intake');
 if(l.overallState!=='NO_GO'||l.tiers?.length!==5||l.deployment?.authorized!==false)errors.push('launch-matrix'); if(!Array.isArray(o.requests)||o.requests.length<9)errors.push('owner-actions'); if(!a.ok)errors.push(...a.errors.map(x=>`owner-action:${x}`)); if(!p.ok)errors.push(...p.errors.map(x=>`portal:${x}`)); if(!ct.ok)errors.push(...ct.errors.map(x=>`commercial:${x}`)); if(!f.ok)errors.push(...f.errors.map(x=>`freemium:${x}`)); if(!e.ok)errors.push(...e.errors.map(x=>`eighth-pass:${x}`)); if(!pack.ok)errors.push(...pack.errors.map(x=>`pack:${x}`)); if(!registry.ok)errors.push(...registry.errors.map(x=>`registry:${x}`));
 if(!Array.isArray(g.items)||g.items.length<6)errors.push('learning-lineage'); if(n.source?.artifact!=='smarter-justice-v1.7.73.zip'||n.source?.evidenceState!=='CURRENT_CHAT_REPRODUCED')errors.push('newest-learning'); if(c.currentMonthlyStructure?.attorneyCents!==1500||c.currentMonthlyStructure?.firmProfileCents!==1500||c.currentMonthlyStructure?.firmCoveredAttorneySeatCents!==1500)errors.push('commercial-prices'); if(c.publicCheckout!==false||c.liveBilling!==false)errors.push('commercial-gate'); if(m.aiAssistance?.externalProviderRequiredForTierA!==false||m.aiAssistance?.liveExternalAi!==false)errors.push('ai-gate'); const fp=fifthPassGovernance.validate();if(!fp.ok)errors.push(...fp.errors.map(x=>`fifth-pass-history:${x}`));return{ok:errors.length===0,errors,releaseVersion:'1.7.75',launchState:l.overallState,ownerActionCount:o.requests.length,requestableOwnerActionCount:a.requestableCount,learningCount:g.items.length,activePairReceiptId:e.activeReceiptId};}
function ownerView(){return{releaseVersion:'1.7.75',validation:validate(),intake:clone(data.intake),launchMatrix:clone(data.launchMatrix),ownerActions:clone(data.ownerActions),ownerActionReadiness:ownerActionReadiness.ownerView(),portalAuthorityDiscovery:portalAuthorityDiscovery.ownerView(),commercialTerms:commercialTerms.ownerView(),publicFreemium:publicFreemium.ownerView(),fifthPassHistoricalGovernance:fifthPassGovernance.ownerView(),eighthPassGovernance:eighthPassGovernance.ownerView(),newestLearning:clone(data.newestLearning),learning:clone(data.learning),commercial:clone(data.commercial),matterAi:clone(data.matterAi),evidenceManifest:clone(data.evidenceManifest),continuity:clone(data.continuity),coordinatedPromptPack:coordinatedPromptPack.ownerView(),professionalIdentityEvidenceRegistry:professionalIdentityEvidenceRegistry.ownerView(),buildPacketIntake:clone(data.buildPacketIntake),continuationMatch:clone(data.continuationMatch)};}
module.exports={validate,ownerView};
