'use strict';
const crypto=require('crypto');
const contract=require('../V14_EVIDENCE_COLLECTION_PACKET_CONTRACT_V1.7.83.json');
const readiness=require('./v14EvidenceReadinessPlanner');
const connectorContract=require('../V14_LIVE_EVIDENCE_CONNECTOR_CONTRACT_V1.7.83.json');
function clone(v){return JSON.parse(JSON.stringify(v));}
function stable(value){if(Array.isArray(value))return value.map(stable);if(value&&typeof value==='object'){const out={};for(const key of Object.keys(value).sort())out[key]=stable(value[key]);return out;}return value;}
function digest(value){const copy=clone(value);delete copy.packet_digest;return crypto.createHash('sha256').update(JSON.stringify(stable(copy))).digest('hex');}
function iso(value){const d=new Date(value);return Number.isFinite(d.getTime())?d.toISOString():null;}
function create(batch,options={}){
 const planned=readiness.plan(batch,options);const errors=[];
 if(!planned.validation.ok)errors.push(...planned.validation.errors.map(x=>`readiness:${x}`));
 const gap=planned.plan.gaps[0]||null;if(!gap)errors.push('no-evidence-gap');
 const now=iso(options.now||'2026-08-03T19:45:00-04:00');if(!now)errors.push('invalid-created-at');
 const validity=Math.max(1,Math.min(contract.maximum_packet_validity_hours,Number(options.validityHours||contract.maximum_packet_validity_hours)));
 const expires=now?new Date(new Date(now).getTime()+validity*3600000).toISOString():null;
 const rule=(connectorContract.component_rules||[]).find(x=>x.component_id===gap?.component_id)||null;if(!rule)errors.push('unknown-component');
 if(errors.length)return{ok:false,errors,plan:planned.plan,packet:null,text:null};
 const packet={schema_id:'SJP-V14-EVIDENCE-COLLECTION-PACKET-2026-08-03-V1',packet_id:`SJP-V14-EVIDENCE-COLLECTION-${gap.component_id.toUpperCase()}-${planned.plan.plan_digest.slice(0,16).toUpperCase()}`,release_version:contract.release_version,source_artifact:clone(contract.exact_source_artifact),governing_packet:clone(contract.governing_packet),component_id:gap.component_id,evidence_type:rule.evidence_type,owner_action:gap.owner_action,required_nonsecret_identifiers:clone(contract.component_nonsecret_identifiers[gap.component_id]||[]),required_checks:clone(rule.required_checks||[]),dependency_receipts:(gap.missing_dependencies||[]).map(component_id=>({component_id,status:'REQUIRED_BEFORE_PROMOTION'})),forbidden_inputs:clone(contract.forbidden_inputs),verification_criteria:{receipt_schema_id:connectorContract.receipt_schema_id,environment:'staging_or_production_as_reviewed',all_required_checks_must_pass:true,receipt_digest_required:true,source_artifact_sha256:contract.exact_source_artifact.sha256,release_version:contract.release_version,secrets_allowed:false,writes_allowed:false,activation_allowed:false},created_at:now,expires_at:expires,preview_only:true,external_calls:false,persists_data:false,mutates_live_state:false,applies_promotions:false,owner_go_inferred:false,deployment_authorized:false,launch_state:'NO_GO'};
 packet.packet_digest=digest(packet);const text=renderText(packet);if(Buffer.byteLength(JSON.stringify(packet))>contract.maximum_packet_bytes)return{ok:false,errors:['packet-too-large'],plan:planned.plan,packet:null,text:null};
 return{ok:true,errors:[],plan:planned.plan,packet,text};
}
function validate(packet){const errors=[];for(const field of contract.required_packet_fields)if(packet?.[field]===undefined||packet?.[field]===null)errors.push(`missing:${field}`);if(packet?.release_version!==contract.release_version)errors.push('release-version');if(packet?.source_artifact?.sha256!==contract.exact_source_artifact.sha256)errors.push('source-artifact');if(packet?.governing_packet?.sha256!==contract.governing_packet.sha256)errors.push('packet-identity');if(packet?.packet_digest!==digest(packet))errors.push('packet-digest');if(packet?.preview_only!==true||packet?.external_calls!==false||packet?.persists_data!==false||packet?.mutates_live_state!==false||packet?.deployment_authorized!==false||packet?.launch_state!=='NO_GO')errors.push('closed-boundary');const scan=clone(packet||{});delete scan.forbidden_inputs;const serialized=JSON.stringify(scan).toLowerCase();for(const prohibited of ['openai_api_key','authorization: bearer','database_url=','smtp_password=','private_key'])if(serialized.includes(prohibited))errors.push(`secret-pattern:${prohibited}`);const created=Date.parse(packet?.created_at),expires=Date.parse(packet?.expires_at);if(!Number.isFinite(created)||!Number.isFinite(expires)||expires<=created||expires-created>contract.maximum_packet_validity_hours*3600000)errors.push('validity-window');return{ok:errors.length===0,errors,packetDigest:packet?.packet_digest||null,componentId:packet?.component_id||null,deploymentAuthorized:false,launchState:'NO_GO'};}
function renderText(packet){return[`SMARTER JUSTICE V14 NONSECRET EVIDENCE COLLECTION PACKET`,`Packet: ${packet.packet_id}`,`Component: ${packet.component_id}`,`Created: ${packet.created_at}`,`Expires: ${packet.expires_at}`,``,`ONE OWNER ACTION`,`- ${packet.owner_action}`,``,`COLLECT ONLY THESE NONSECRET IDENTIFIERS`,...(packet.required_nonsecret_identifiers||[]).map(x=>`- ${x}`),``,`REQUIRED PASS CHECKS`,...(packet.required_checks||[]).map(x=>`- ${x}`),``,`DO NOT ENTER OR SHARE`,...(packet.forbidden_inputs||[]).map(x=>`- ${x}`),``,`BOUNDARIES`,`- Preview only; no provider call, persistence, state mutation, deployment authorization, or production activation.`,`- Packet digest: ${packet.packet_digest}`].join('\n')+'\n';}
function ownerView(){return{contract:clone(contract),state:'READY_FOR_NONSECRET_FIRST_GAP_PACKET',externalCalls:false,persistence:false,stateMutation:false,deploymentAuthorized:false,launchState:'NO_GO'};}
module.exports={stable,digest,create,validate,renderText,ownerView};
