'use strict';
const fs=require('fs');const path=require('path');const crypto=require('crypto');
const ROOT=path.join(__dirname,'..');
const config=require('../V14_RELEASE_RECEIPT_AUTOMATION_V1.7.83.json');
function sha(bytes){return crypto.createHash('sha256').update(bytes).digest('hex');}
function walk(root=ROOT){const out=[];function visit(dir){for(const name of fs.readdirSync(dir).sort((a,b)=>a.localeCompare(b))){const full=path.join(dir,name),rel=path.relative(root,full).split(path.sep).join('/');const st=fs.lstatSync(full);if(st.isSymbolicLink())throw new Error(`symlink:${rel}`);if(st.isDirectory())visit(full);else if(st.isFile())out.push(rel);}}visit(root);return out;}
function generatePayloadInventory(root=ROOT){const excluded=new Set(config.payload_exclusions);return walk(root).filter(p=>!excluded.has(p)).sort((a,b)=>a.localeCompare(b)).map(p=>`${sha(fs.readFileSync(path.join(root,p)))}  ${p}`).join('\n')+'\n';}
function parseOwnerReceipt(text){const fields={};for(const line of String(text||'').split(/\r?\n/)){const m=line.match(/^([A-Z0-9_]+):\s*(.*)$/);if(m)fields[m[1]]=m[2].trim();}return fields;}
function validate(root=ROOT){const errors=[];const expected=generatePayloadInventory(root);const actual=fs.readFileSync(path.join(root,config.payload_inventory),'utf8');if(actual!==expected)errors.push('payload-inventory-drift');const fields=parseOwnerReceipt(fs.readFileSync(path.join(root,config.owner_receipt),'utf8'));if(fields.PRODUCT_VERSION!=='1.7.83')errors.push('owner-version');if(fields.RELEASE_PAYLOAD_INVENTORY_SHA256!==sha(Buffer.from(actual)))errors.push('owner-inventory-sha');if(Number(fields.RELEASE_PAYLOAD_INVENTORY_RECORD_COUNT)!==actual.trimEnd().split('\n').filter(Boolean).length)errors.push('owner-inventory-count');if(fields.FINAL_DELIVERY_ZIP_IDENTITY!=='REPORTED_AFTER_PACKAGING')errors.push('outer-identity');if('FINAL_DELIVERY_ZIP_SHA256' in fields||'FINAL_DELIVERY_ZIP_SIZE_BYTES' in fields)errors.push('self-reference');for(const p of config.payload_exclusions)if(actual.includes(`  ${p}\n`))errors.push(`excluded:${p}`);return{ok:errors.length===0,errors,payloadInventorySha256:sha(Buffer.from(actual)),payloadInventoryRecords:actual.trimEnd().split('\n').filter(Boolean).length,outerZipIdentityEmbedded:false,deploymentAuthorized:false,launchState:'NO_GO'};}
module.exports={sha,walk,generatePayloadInventory,parseOwnerReceipt,validate};
