'use strict';
const fs=require('fs');const path=require('path');const crypto=require('crypto');const child=require('child_process');
function sha(value){return crypto.createHash('sha256').update(value).digest('hex');}
function stable(value){if(Array.isArray(value))return value.map(stable);if(value&&typeof value==='object'){const out={};for(const key of Object.keys(value).sort())out[key]=stable(value[key]);return out;}return value;}
function splitTestChain(script){return String(script||'').split(/\s+&&\s+/).map(x=>x.trim()).filter(Boolean);}
function commandId(command,index){const match=String(command).match(/(?:tests|scripts)\/([A-Za-z0-9._-]+)\.js/);return match?match[1]:`command-${String(index+1).padStart(3,'0')}`;}
function manifestFromPackage(pkg,{releaseVersion='1.7.83',sourceArtifact=null,packet=null}={}){const commands=splitTestChain(pkg?.scripts?.test);return{schema_id:'SJP-V14-SEGMENTED-ACCEPTANCE-MANIFEST-2026-08-03-V1',release_version:releaseVersion,source_artifact:sourceArtifact,governing_packet:packet,expected_command_count:commands.length,commands:commands.map((command,index)=>({index:index+1,id:commandId(command,index),command})),stable_log_format:'SJP-V14-ACCEPTANCE-LOG-V1',fail_fast:true,per_command_timeout_ms:120000,postgres_dependent_parts_excluded:1};}
function validateManifest(manifest,pkg){const errors=[];const commands=Array.isArray(manifest?.commands)?manifest.commands:[];if(manifest?.schema_id!=='SJP-V14-SEGMENTED-ACCEPTANCE-MANIFEST-2026-08-03-V1')errors.push('schema');if(manifest?.release_version!==pkg?.version)errors.push('release-version');if(manifest?.expected_command_count!==commands.length)errors.push('manifest-count');const packageCommands=splitTestChain(pkg?.scripts?.test);if(packageCommands.length!==commands.length)errors.push('package-count');const ids=new Set();commands.forEach((item,index)=>{if(item.index!==index+1)errors.push(`index:${index+1}`);if(!item.id||ids.has(item.id))errors.push(`id:${item.id||'missing'}`);ids.add(item.id);if(item.command!==packageCommands[index])errors.push(`command:${index+1}`);});return{ok:errors.length===0,errors,commandCount:commands.length,manifestSha256:sha(JSON.stringify(stable(manifest)))};}
function runManifest(manifest,{cwd=process.cwd(),timeoutMs=manifest?.per_command_timeout_ms||120000,env=process.env}={}){const records=[];let failed=false;for(const item of manifest.commands||[]){if(failed&&manifest.fail_fast)break;const result=child.spawnSync('/bin/sh',['-lc',item.command],{cwd,env,encoding:'utf8',timeout:timeoutMs,maxBuffer:32*1024*1024});const stdout=String(result.stdout||'').replace(/\r\n/g,'\n');const stderr=String(result.stderr||'').replace(/\r\n/g,'\n');const status=Number.isInteger(result.status)?result.status:(result.error?.code==='ETIMEDOUT'?124:1);records.push({index:item.index,id:item.id,command:item.command,status,signal:result.signal||null,stdout,stderr});if(status!==0)failed=true;}
 const log=records.map(r=>[`=== ${String(r.index).padStart(3,'0')} ${r.id} ===`,`COMMAND ${r.command}`,`STATUS ${r.status}`,r.stdout.trimEnd(),r.stderr.trimEnd()].filter(x=>x!=='').join('\n')).join('\n')+'\n';return{ok:!failed&&records.length===(manifest.commands||[]).length,records,completedCommandCount:records.length,expectedCommandCount:(manifest.commands||[]).length,log,logSha256:sha(log),stableLog:true};}
function ownerView(manifest){return{state:'CANONICAL_SEGMENTED_ACCEPTANCE_READY',releaseVersion:manifest.release_version,expectedCommandCount:manifest.expected_command_count,manifestSha256:sha(JSON.stringify(stable(manifest))),stableLogFormat:manifest.stable_log_format,postgresDependentPartsExcluded:manifest.postgres_dependent_parts_excluded,deploymentAuthorized:false,launchState:'NO_GO'};}
module.exports={sha,stable,splitTestChain,commandId,manifestFromPackage,validateManifest,runManifest,ownerView};
